---------------------------------------------------------------------------
-- Changelog data.
--
-- Kept in its own file: it only ever grows, and it is data, not layout.
-- Rendered by the Changelog page in Options.lua.
---------------------------------------------------------------------------
local _, ns = ...

ns.CHANGELOG = {
    {
        version = "4.32.2",
        date = "2026-08-08",
        lines = {
            "THE BAR IN THE PREVIEW IS AS LONG AS YOUR BAR NOW. It was drawn part-full, so that the card read as a bar rather than as a block of colour - and that one decision has now caused three complaints in a row. First the bar looked shorter than it really is. Then the faint mark added behind it to show the true length was drawn in your own bar colour and read as a second setting you had chosen. Then, with that gone and a black backdrop invisible against a black card, the gap at the end was simply back.",
            "So the card shows the whole bar. That is what it is being asked - how big is it, what colour, which texture, where does the name sit - and the honest answer to all of it is a full bar. The one thing it can no longer show is which way the fill runs, and the Direction setting already draws four arrows saying exactly that.",
        },
    },
    {
        version = "4.32.1",
        date = "2026-08-08",
        lines = {
            "THE EMPTY PART OF A BAR IN THE PREVIEW WAS THE WRONG COLOUR, and it was the card's own invention. It washed the unfilled run in your bar's own colour at 16%, so a green bar previewed as bright green and then dark green - where on screen it is bright green and then whatever your backdrop is. Nothing on screen has ever drawn that second colour.",
            "It was put there for a real reason: with the backdrop switched off there is nothing behind a part-full fill at all, so the bar simply looked shorter than it is. That still holds - so the mark is still drawn, but only when the backdrop is not already showing the length, and in the settings window's own grey rather than in your bar's colour. It reads as the editor saying \"the bar reaches to here\" instead of as a colour somebody chose.",
            "",
            "AND THE PREVIEW CAN FILL UPWARDS NOW. Direction offers four ways for a bar to run and the card only ever knew two of them: set to fill bottom-to-top or top-to-bottom, the bar stood up on screen and went on lying down in the preview.",
        },
    },
    {
        version = "4.32.0",
        date = "2026-08-08",
        lines = {
            "THE EXTRA 0 BESIDE A CHARGE COUNT IS GONE. It was the STACK count, not the charge count. On this patch a stack count arrives as a protected number that an addon may not compare to anything - so \"is it more than one\" could not be asked, and a nought printed exactly like a real count. The game CAN ask it, and answers by hiding its own counter; the addon now reads that answer instead of trying to make the comparison itself.",
            "",
            "THE CARD IN THE EDITOR AND THE BAR ON SCREEN DISAGREED, three ways. It ignored the Direction setting entirely - it was still reading a switch that was replaced two versions ago and that nothing writes any more, so every bar in the card filled left to right whatever you picked. It drew a flat fill under a gradient backdrop, because the gradient work rewired everything except the card. And at any scale other than 100% it spaced the cells wrong and measured the bar short, which then made the whole card scale itself off a wrong number.",
            "",
            "THE CO-TANK PANEL IS MOVED IN EDIT MODE NOW, like everything else this addon draws. The button on the settings page is gone: a display you move from a button in a window is moved blind, because the window is sitting over the place you are trying to put it. It comes out while you are in edit mode even when it is switched off, it drags like a bar, and it snaps to your bars and to the middle of the screen - hold Alt to put it exactly where you want it instead.",
            "",
            "FOUR THINGS WERE BADLY BROKEN AND ARE NOT ANY MORE.",
            "The co-tank health bar was PINNED AT FULL for anybody whose health this client protects - which is everybody, in a fight. The bar was being handed the number without ever being told the range it belonged to, so a value in the millions clamped to the end. It read 100% for the whole pull.",
            "Reading a group member's CLASS could take the whole panel down. On someone out of range the game answers with a protected value, and using one of those to look something up is not allowed - it throws, and it would have thrown ten times a second at exactly the moment somebody walked away.",
            "TEST MODE DID NOTHING unless you had already switched the panel on. So did asking to move it. Both are requests to SEE the thing, and both were being refused by the master switch above them.",
            "And the PREVIEW on the settings page was empty every time you opened it. It was showing the real panel, correctly - but nothing ever asked that panel to draw itself in the card, so it was a nought-by-nought frame full of hidden rows.",
            "",
            "THE INDICATORS ARE YOURS NOW. Raid marker, leader crown, role mark and a new IN COMBAT mark: each one gets shown, size, one of nine positions, and a nudge each way. The name and the health text keep out of their way automatically - a marked tank's name used to start underneath the skull.",
            "The target marker is called a BORDER, because that is what it is. It also had never once been visible: it was drawn on the row underneath the health bar, which covers it completely.",
            "",
            "SHIELDS GET THEIR OWN TEXTURE, and their own explanation. A shield drawn in the same material as the health under it reads as more health, which is the one thing it must not do. \"Healing taken away\" is now \"Healing blocked\", and the panel says what the two actually are: a shield is damage they can take for free and sits past the end of the fill; healing blocked is a debuff eating their incoming heals and sits inside it.",
            "\"Plate\" is now \"Behind the bar\", which is what it is.",
            "",
            "CLASS COLOUR ON THE HEALTH TEXT DOES SOMETHING. The switch was there and the renderer never read it.",
            "",
            "THE AURAS TAB OPENED WITH NO EXPLANATION ON IT. Its note - the one that says live aura strips need next Monday's patch, which is the single most important sentence on that page - had been quietly filed into a collapsed section belonging to the previous tab. Fixed for every tab, not just that one.",
            "",
            "AND THE GRADIENT REACHED THE PER-CELL SETTINGS. A cell given its own fill colour could not be given the ramp that goes with it - the whole-bar page grew the control and this one did not.",
            "",
            "Smaller: the role mark was drawing a corner of Blizzard's icon sheet with a slice of the next role in it. The fade slider under a bar's visibility rules stored the wrong number when you typed into it. And the 12.1 aura strips will wrap where the preview says they wrap.",
        },
    },
    {
        version = "4.31.1",
        date = "2026-08-08",
        lines = {
            "THE CO-TANKS PAGE HAD NO CONTROLS ON IT. Labels, lines between them, and nothing to set. They were all there - four hundred units off the right-hand side of the window, where you could not see them.",
            "Every page in this window was being built at the width of the WIDE middle column - the one you get when a page has no third column beside it. A page that HAS a third column is shown in the narrower middle instead, so its rows were built half again as wide as the space they were put in. The labels sit on the left, so those showed. Every control sits at the right-hand end of its row, so none of them did.",
            "",
            "SETTINGS HAD THE SAME HOLE, and has had it for a long time: its two font pickers are full-width rows and have never once been on screen. Half-width rows fit either way, which is why nobody caught it - the page was half working, and half working reads as a design rather than as a fault.",
            "",
            "AND THREE OF THE FOUR TABS ON THE RIGHT WERE INVISIBLE. Look, Text, Auras and Rules all existed; only Look could be reached, because the strip that holds them was never told to divide itself between them, so all four had no width. The strip does that itself now, and again whenever it is resized - a thing that needs to be reminded to be visible will eventually be built without the reminder.",
            "",
            "THE PREVIEW LOST ITS PARAGRAPH OF EXPLANATION. It described how the preview works rather than what you are looking at, and it pushed the picture down the page.",
            "",
            "CUSTOM COLOUR AND THE THREE HEALTH COLOURS now only appear when the mode that uses them is picked. A colour picker sitting under \"By class\" changes nothing, and this panel is not allowed to have controls that do nothing.",
            "",
            "AND SWITCHING A GRADIENT ON NOW SHOWS ITS TWO ROWS IMMEDIATELY, rather than on the next thing that happened to redraw the page.",
        },
    },
    {
        version = "4.31.0",
        date = "2026-08-08",
        lines = {
            "CO-TANKS. A new section in the window, and the first thing in this addon that is about somebody other than you: a row for every tank in your group, with their health, their name, their shields, and - once patch 12.1 lands on Monday - everything on them and everything they have running.",
            "It answers the four things you actually need from the other tank, at a glance: are they alive, are they low, are they in range, and do they still have a cooldown. Blizzard's raid frames answer none of them quickly, because the other tank is one box among twenty and looks exactly like the other nineteen.",
            "",
            "THERE IS A TEST MODE, and it is the second control on the page rather than something buried at the bottom. Nobody sits in a raid to line up a panel. Switch it on and the display fills with tanks that do not exist - five classes, one dead, one disconnected, one out of range, one that is your target - and their health MOVES, so the texture, the fill direction, the colour ramp and the shield overlay can all actually be judged. It survives a reload, and it is off again from the same switch or with /zs tanks test.",
            "",
            "It is not a drawing of the display. It IS the display, with invented numbers going in - one renderer, two sources. Every preview in this addon that drew itself has ended up disagreeing with the thing it was previewing, twice in one session, and the only fix that holds is to have nothing that can drift.",
            "",
            "THE PREVIEW IN THE MIDDLE OF THE PAGE IS THE PANEL ITSELF, borrowed from your screen while you are looking at it and put back when you leave.",
            "",
            "WHAT YOU CAN SET: the bar's texture; whether it is coloured by class, by one colour of your choosing, or by how much health is left; which way it fills, in all four directions; the plate behind it, its border, and the faint track under the fill. Shields are drawn over the health where they actually sit rather than as a separate strip somewhere else, and healing that has been taken away is drawn inside it. Name and health text each get the same nine positions, two nudges, font, size, colour, outline and a class-colour switch - and the health text can read a percent, what is left, both, or what is missing.",
            "Plus a ring when that tank is your target, the raid marker, the leader crown, the role mark, and a fade each for out of range, dead and disconnected. One fade wins rather than all three multiplying together - a dead, disconnected tank who is out of range came out invisible, which is exactly when you want to see that there is one.",
            "",
            "THE AURA STRIPS NEED PATCH 12.1, AND THE PAGE SAYS SO INSTEAD OF SHOWING YOU AN EMPTY ROW. On this client an aura on another player is a protected value: no addon may read its icon, its stacks or its time left, and there is no way round that. Blizzard's own aura engine can, it arrives on Monday, and this addon already speaks to it. Until then the strips draw in test mode - so every one of those fourteen settings can be set up now and will be right the moment the patch lands.",
            "",
            "EVERY COLOUR THAT CAN BE A GRADIENT NOW OFFERS ONE. The bar fill, the backdrop, the border and each stack band: a second colour and one of four directions. A new look, Deep, uses two of them, so it can be seen without being built first.",
            "The three that cannot are not offered, and that is deliberate. The cooldown sweep takes exactly one colour, a charge mark is a single pixel wide, and a line of text has no gradient at all - the game does not provide one. A control that silently did nothing would be the fourth of those found in two days, and three missing rows are better than three lies.",
            "",
            "EDIT MODE MOVED TO THE TOP OF THE LEFT-HAND LIST, on its own, above everything. It was filed under Bars, which reads as one of the bar pages - and it is not a page. Every other entry opens something inside the window; that one closes the window and puts you on the screen with your bars in your hands.",
        },
    },
    {
        version = "4.30.0",
        date = "2026-08-08",
        lines = {
            "THE BARS COULD STOP MOVING ENTIRELY, and this is why: while working out which talent is behind which proc, the addon asks the game to load a talent's description. The game sometimes answers on the spot, and that answer clears a list the addon is in the middle of writing - so the next line wrote into nothing and threw. That happens inside the startup step that starts the clock, so the bars were drawn and then never moved again. If you have ever seen \"Bars failed to start\" in chat, that was this.",
            "",
            "FOUR CONTROLS THAT DID NOTHING NOW DO SOMETHING. Countdown position and nudge, stack position and nudge, the spell name's position and nudge, and the spark. All reported by the owner in one sitting, and all four turned out to be different faults that happened to look identical from the chair.",
            "",
            "THE SPARK WAS NEVER ON SCREEN. Not on any bar, in any direction, since it was added. It was pinned by its top AND its bottom to the same point - the middle of the fill's leading edge - so both of its own edges landed on one line: ten pixels wide and nothing tall.",
            "It rides that edge properly now, and it brings its own picture. The one the game ships keeps its glow in the middle of a lot of empty space, so a spark stretched to the height of your bar still looked like a short stub in the middle of it. Ours is a bright line in a soft halo that runs the whole height, whatever height that is.",
            "",
            "THE COUNTDOWN NUMBER WAS BEING STYLED BEFORE IT EXISTED. The game draws that number itself and does not create it until a cooldown is actually running - and settings are applied when the bar is drawn, which is when almost nothing is on cooldown. So there was nothing there to move, and the moment a cooldown started the game made one in its own place. The setting is remembered against the frame now and re-applied the instant a cooldown is set on it.",
            "",
            "THE STACK AND CHARGE COUNTS MOVE AS A WHOLE. Their number is written by the game's own layout, which puts it back where it wants it; the counter around it is not, so that is what moves. And it is now found in both of the two places the game keeps it - on some frames it hangs off the icon rather than the frame, and looking in one place only meant the setting quietly did nothing on half your icons.",
            "",
            "THE SPELL NAME'S POSITION WAS SIMPLY NOT READ. Both renderers anchored it hard to the left and threw the setting away. All nine positions and both nudges work now, inside the space the icon leaves it - and the name hangs off both ends of that space instead of being given a fixed width, so it follows the bar when you make the bar wider.",
            "",
            "THE COUNTDOWN ON A TRACKING BAR was never the number on the icon. A bar takes its timing from the game's own bar, so it has no clock of its own to hand that number to and copies the text into a line of ours instead - which was nailed to the right end. It goes where you put it now.",
            "",
            "AND THE STACK COUNT HAD NOWHERE TO APPEAR. On an adopted icon it is the game's own; on a bar this addon draws there was no stack number at all, so the whole Stacks section was driving something that did not exist.",
            "",
            "THE CARD SHOWED YOUR BAR SHORTER THAN IT IS. Its fill is drawn part-full so the card reads as a bar rather than a block of colour - which only makes sense with a backdrop behind it, and with the backdrop off there was nothing there at all. A faint track in your own fill colour now runs the whole length underneath, so the card shows the bar's real dimensions whatever else is switched off.",
            "",
            "AND THE NOTES IN THE PANEL COULD LAND ON TOP OF EACH OTHER. How tall a note is depends on the font it is set in, and fonts arrive late - another addon registering one, or you changing the panel font. Measured once when the note was written, everything below it was then laid out too high. They measure themselves every time the page is laid out now.",
            "",
            "THE CHARGE COUNT IS ITS OWN SETTING, and on the cells this addon draws it is there at all for the first time. A charge spell on one of our own bars showed no number while the same spell on an adopted icon beside it did - that was the gap.",
            "It gets the same seven controls as every other text element: on, font, size, colour, outline, one of nine positions, and a nudge each way. Stacks and charges used to share one entry, because the game never puts both numbers on one frame - but \"charges top left, stacks bottom right\" is an ordinary thing to want, and one setting for two numbers cannot say it.",
            "",
            "If you had moved or recoloured the stack count, your charges inherit exactly that. Nothing on your screen moves on this update.",
            "",
            "HOW IT CAN BE SHOWN AT ALL: on this patch the live count is a protected value that no addon may read - not compare, not add to, not even test. It CAN be handed straight to the game's own text setter, which formats and draws it without ever letting the addon see it. That is the one door, and this addon never reads the number: at full charges the answer is simply the maximum, and below that the count goes from the game to the font string without passing through us.",
            "",
            "ZWOELFSTUFF IS IN THE GAME MENU, under the last of Blizzard's own entries. Escape, then click it. It steps aside while you are in combat: pressing it closes the pause menu, and the game does not let an addon do that mid-fight - a button that did nothing when pressed would be worse than no button. Off with one tick in Settings.",
            "It is appended below the last entry rather than slipped into the middle, which is why nothing of Blizzard's moves: the menu re-anchors every one of its own buttons each time it opens, and an addon inserting itself in that stack has to fight it on every pass, for ever.",
            "It carries no artwork of its own - just the word, in the font the menu is already using, whichever skin you run. Blizzard's button template comes with a red plate that you never see on the real entries because every one of them gets restyled afterwards; ours is not in that pool, so it wore the plate. A bare frame has nothing left over to look wrong.",
        },
    },
    {
        version = "4.29.0",
        date = "2026-08-08",
        lines = {
            "DISCORD IS IN THE LEFT COLUMN, above the version. Clicking it opens the invite in a box with the whole link already selected - one Ctrl+C and it goes in your browser. No addon can open a browser for you; the client has no call for it, on purpose, and a row that looked like a link and did nothing would be worse than no row at all.",
        },
    },
    {
        version = "4.27.0",
        date = "2026-08-08",
        lines = {
            "THE FILL RUNS WHICHEVER WAY YOU WANT NOW - left to right, right to left, bottom to top, top to bottom. One setting with four answers, where it used to be two switches you had to combine in your head, neither of which named the thing you actually wanted to say.",
            "TWO OF THE FOUR ARE NEW. A status bar's reverse flag only ever flips a HORIZONTAL bar, so a vertical fill was not reachable at all, whichever way the old switch was thrown. The spark rides the right edge on a vertical bar now, and the charge marks lie across it instead of running down it - three lines parallel to the fill divide nothing.",
            "",
            "A bar you had set to start from the right keeps doing that: it becomes \"right to left\" when the profile is read, once, and nothing is lost.",
            "",
            "STACK COLOURS: THE ROWS SAID \"At ... stacks\", which reads as a label that has been cut off - that is what an ellipsis in the middle of a phrase looks like. They say \"From\", and the number is in the control beside them where it always was.",
            "",
            "/ZS REPORT OPENS A BOX YOU CAN COPY OUT OF. Every proc this addon has watched you set off, on this character and spec, with the addon version and the client build so the list means something later. Select-all is already done; Ctrl+C takes the lot. It used to print to the chat frame, which is not a way to hand anything over - you cannot select chat text, and thirty lines scroll off the top. If you are testing this for me, that is the command: play normally, then /zs report and paste it back.",
        },
    },
    {
        version = "4.26.0",
        date = "2026-08-08",
        lines = {
            "THE TEXTURE LIST IS THE ONE FROM THE DESIGN NOW. Wider, with a search box at the top and the keys explained at the bottom, and it groups: everything this addon ships first, everything your other addons brought after. Deliberately not alphabetical across the two - at forty-odd entries that is the difference between finding and searching.",
            "",
            "TYPE TO FILTER. Any part of a name, upper or lower case. A group whose entries have all been filtered away loses its heading with them.",
            "",
            "THE PREVIEW STRIPS ARE IN THE BAR'S OWN FILL COLOUR. They were orange - the addon's accent - which tells you nothing about the bar you are actually setting up. And they are the full 132 by 14 the design draws, instead of a 76-wide chip.",
            "",
            "AND THE ONE YOU ARE ON IS OBVIOUS. It had orange text, which in a list of grey text is a difference you have to look for. Now it has a raised ground, an orange bar down its left edge and a tick on the right.",
            "",
            "The list fades out at the bottom instead of being cut off mid-row, so it is clear there is more below.",
        },
    },
    {
        version = "4.25.0",
        date = "2026-08-08",
        lines = {
            "RIGHT CLICK THE MINIMAP BUTTON TO MOVE THE BARS. It used to toggle the co-tank panel - a module parked until 12.1, so the branch was switched off and right click quietly did the same thing as left click. Moving the bars is the one thing you come to that button for that is not \"open the window\", and it was two clicks deep.",
            "",
            "SNAPPING IS NOT A SETTING ANY MORE. It is what dragging does. The switch is gone from the tools panel, because a switch whose off position makes a feature silently do nothing is the switch that gets left off by accident and then reported as a broken feature - which is exactly what happened. Hold Alt while you drag to place a bar freehand; that is the escape hatch, and it is per drag rather than per profile.",
            "",
            "AND THE ARITHMETIC CAN BE TESTED NOW. Snapping went wrong three times, and every single diagnosis was reading the code and reasoning about it, because none of it could be RUN - the maths was welded to live frames and saved settings. It is split in two now: one half measures the bars on screen, the other half is plain numbers in and plain numbers out. /zs test puts two bars four pixels apart and asserts where the second one lands, including the case that never existed - one bar sitting flush against another.",
        },
    },
    {
        version = "4.24.0",
        date = "2026-08-08",
        lines = {
            "SNAP TO GRID WAS NEVER ON, AND COULD NOT BE TURNED ON PROPERLY. Edit mode fills in any setting your profile is missing - and it carried its own list of four keys next to the seven the profile actually declares. snapToGrid was in one list and not the other, so on any profile older than that key it read as nothing at all: switched off, with no way to tell it had never been on. It fills from the one list now, and grid snapping is on by default.",
            "",
            "AND THE GRID NEVER DREW A LINE WHEN IT CAUGHT. Snapping to another bar showed you the line it lined up with; the grid, which is the one kind that always pulls, showed nothing - so the snapping that was working looked like the snapping that was not. It draws its line too.",
            "",
            "BARS SNAP AGAINST EACH OTHER NOW, NOT JUST INTO LINE WITH EACH OTHER. Every target used to be an ALIGNMENT - your left edge onto their left edge, your middle onto their middle. So two bars could line up but never sit flush side by side, which is how a row of bars is actually built. Your edge against their edge is a target now, on both axes.",
            "",
            "AND THE SCREEN EDGES CATCH. Pushing a bar into a corner had nothing to snap to at all.",
            "",
            "THE OVERLAY SAYS WHAT SNAPPING IS DOING. The state lives on two switches in a panel you have to open first, and the line above them explained how to hold Alt to suspend snapping - while snapping was switched off. It now says what it snaps to, or that it is off and where the switch is.",
        },
    },
    {
        version = "4.23.0",
        date = "2026-08-08",
        lines = {
            "EVERY BAR CAN BE PINNED ON ITS OWN. A padlock sits under the cog on each one. A pinned bar still selects, still opens its settings, still takes a cell - it just does not move, by drag, by the arrow buttons or by the arrow keys. The bar you have finished placing and the bar you are still placing are on screen together, and the finished one is exactly what a stray drag lands on. The same switch is in the bar's own settings, so you can see which are pinned without going in and looking at each one.",
            "",
            "CLICKING A BAR OPENS ITS SETTINGS. The tools panel already followed whichever bar was selected, but you had to know that and press Tools first - so clicking a bar looked like it did nothing.",
            "",
            "THE NUDGE ARROWS ARE ONE ROW ON A TAB ABOVE THE BAR. As a four-way pad inside the box they sat on top of the bar's own name and whatever it was drawing, and a small chevron over a spell icon is not readable at any colour. Now they have their own strip, flush on the top edge, with the same fill and outline as the box: left, right, up, down. One pixel a click, ten with Shift, unchanged.",
            "",
            "THE MINIMAP BUTTON IS ACTUALLY ROUND. Its rim and plate were a solid colour with a circular mask over them - and a mask works by multiplying a TEXTURE's transparency, which a colour fill does not have. So the mask did nothing to those two layers and everything to the icon, and the square corners of the plate stuck out around the round icon. Both are a real round file now, tinted where they are used, the same way the window's icons work.",
        },
    },
    {
        version = "4.22.0",
        date = "2026-08-08",
        lines = {
            "THE REST OF THE DESIGN'S ICONS ARE IN. Sixty-eight were drawn and rendered; the last release used eleven of them. Now the plus and minus on every stepper, the close cross, the three-dot overflow, the chevron on every dropdown and the cross that deletes a saved entry are all the design's own marks instead of typed characters. A hyphen and a plus sign sit on different baselines in any font, which is why that pair never looked like one control.",
            "",
            "THE LISTS THAT PICK A SHAPE NOW SHOW THE SHAPE. Arrangement, fill order, across, down, and the bar's kind draw their mark in front of the word - in the open list and on the closed field. \"Staggered\" and \"Puzzle\" are both just words until you have seen each one once.",
            "",
            "SO DO THE ROWS THAT REPEAT. The six places a bar may show, the four conditions, the effects and the media rows each carry their own mark. Six rows that differ by one word are a list you read from the top every time; with a mark you find the raid switch without reading any of them. Ordinary settings rows do NOT get one - a mark next to everything is decoration, and decoration next to a real signal makes the signal worth less.",
            "",
            "EDIT MODE: DONE WAS SITTING ON TOP OF SPELLS. The tool bar was 360 wide, the bottom row of buttons ran to 332, and Done - anchored to the right edge - started at 276. The two shared 56 pixels whenever you were in build mode, which is the only mode where Spells is shown. The bar is 460 now and they no longer touch.",
            "",
            "The cog on each bar is the design's gear, Done wears a padlock, and Move bars and Build carry the same two marks in edit mode that they carry in the window - so the pair is recognisable in both places.",
            "",
            "THE AURA DISPLAY PAGE IS GONE FOR GOOD. It was in the design and never in the addon; the auras the Cooldown Manager does not carry are handled where the bars are and need no page of their own.",
            "",
            "AND A CHECK THAT CATCHES A MISSING MARK. An unknown icon name never threw - it quietly fell back to four rectangles, which is exactly how the wrong icons shipped in the first place. /zs test now walks every list that names one and fails if it does not resolve.",
        },
    },
    {
        version = "4.21.0",
        date = "2026-08-08",
        lines = {
            "THE WINDOW WAS REDRAWN, PROPERLY. You had it designed - colours, sizes, spacing, every screen - and this is that design built. The complaint it answers is the one you started with: \"unuebersichtlich, sieht altbacken aus\".",
            "",
            "THE SIDE COLUMNS ARE NOW DARKER THAN THE MIDDLE, not lighter. That one inversion is most of it: the thing you are working on sits on TOP of the window instead of in a trench between two raised walls. The whole palette went deeper with it, and orange now appears at most once per column - so when it does appear, it means something.",
            "",
            "THERE ARE NO SLIDERS LEFT. Every number is a stepper: minus, the value, plus. A slider standing in for a range is only as precise as the pixels it happens to be wide, and on a 0-to-1 opacity in a narrow column no exact value was reachable by hand. You can still type into the box, and the wheel over it still steps.",
            "",
            "THE LEFT COLUMN IS GROUPED - Bars, System, Info - under the addon's mark and wordmark, with the version and your client build along the bottom. Seven flat entries is a list you read from the top every time.",
            "",
            "THE CARDS SAY WHAT THEY ARE. A numbered chip, the name, and a badge for the kind. Rows, Columns and Arrangement moved into a column BESIDE the preview instead of a strip under it, so two cards fit where one and a half did. Delete moved into the overflow menu, where an action with no undo belongs.",
            "",
            "THE RIGHT COLUMN HAS THREE TABS - Look, Behaviour, Reuse - instead of nine sections in one long scroll. And on Settings it is never empty any more: point at a setting and the third column explains it. That text used to be a wrapped grey paragraph under every single row, which was the largest single consumer of space on the page.",
            "",
            "THE PANEL HAS ITS OWN FONT, and that was the single biggest reason it did not look like the design. Every string in the window took the CLIENT's face - wide and round - while the design is drawn in a narrow grotesk and Settings had a font picker that only ever reached the bars. Panel font and bar text are now two settings, because a face that is right over a moving 3D scene is rarely right for forty rows of settings.",
            "",
            "THE SPELL LIST IS ONE LINE PER SPELL. The grey second line carrying \"on this bar, cell 2\" and the spell ID is gone; what an entry has to say on the right is one short thing - which cell it sits in, how long its cooldown is, or that your build does not have it. The ID is in the tooltip, where you look when you are asking about one of them rather than scanning all of them.",
            "",
            "THE ICONS ARE THE DESIGN'S OWN NOW. Every mark in the window used to be built from filled rectangles, which is why they never matched: the design draws OUTLINES at 1.4 pixels with round ends - four EMPTY squares for Cooldowns, a real circle for About, real diagonals for Edit mode. Rectangles cannot draw a circle.",
            "The client loads neither SVG nor PNG, so the design's 68 drawings are rasterised and shipped as TGA - and rendered at the size they are shown at rather than scaled between sizes, because a 1.4 pixel stroke does not survive being resized. They are white and tinted where they are used, so one file serves the dim, the bright and the accent state.",
            "",
            "AND THEY ARE SHARP AT YOUR INTERFACE SCALE. Your interface is not at 1:1 - one unit is closer to 1.8 real pixels - so a mark drawn at 14 was being stretched to 25 and every fine stroke went soft. Each one now exists at the design size AND at double, and the client picks the nearer one and scales DOWN instead of up.",
            "",
            "NEW LOGO, and the minimap button wears it.",
        },
    },
    {
        version = "4.20.0",
        date = "2026-08-08",
        lines = {
            "THE NAVIGATION IS STRAIGHTENED OUT. You said it was a muddle - where the buttons are, what they are called - and you were right. It had grown rather than been designed.",
            "",
            "What was wrong, plainly: \"Done\" and \"Just this one\" sat on the SAME spot in the top right and swapped places depending on what you were doing, which reads as the window moving under your hand. \"Options\" meant this bar, \"Just this one\" meant this cell, and nothing said how the two were related. And from a cell you could not get to its bar at all - Done always threw you back to the spell list.",
            "",
            "EACH CARD NOW CARRIES ITS OWN THREE TABS: Spells, Bar, and the cell's own name. The thing you are looking at chooses what is being edited, and the answer appears beside it. Only the card you are working on lights a tab, because three lit cards would claim three things are being edited at once. The Cell tab shows the spell it would edit, so you know what it means before you press it.",
            "\"Options\" is gone - the tab replaced it. Build on screen and Delete stay on the right of the header, so a click that changes the view and a click that changes the bar are never neighbours.",
            "",
            "A PATH UNDER THE HEADING shows the way back: Spells > Bars 2. Every part is clickable, so a cell can reach its bar without going through the spell list. It shows only where you can GO, never where you already are - the heading below says that, and printing the same word twice one line apart is how the old one got confusing.",
            "",
            "AND THE CELL SETTINGS ARE IN EDIT MODE TOO. Colour, size and the fill direction now sit in the tool panel, where you are looking at the real bar instead of a preview - a colour is something you judge against the screen it will live on. Both places write the same setting through the same code, so neither can know a value the other does not. A star next to the name means that cell wears something of its own.",
        },
    },
    {
        version = "4.19.0",
        date = "2026-08-08",
        lines = {
            "EVERY SLIDER CAN BE TYPED INTO. Click the number, type it, press Enter. It was read-only, which meant an exact value could only be reached by dragging until the display agreed - and on a 0.05 step that is a game of patience, not a setting.",
            "The unit comes off what you type: \"85%\", \"85\" and \"85 s\" all mean the same thing, because people re-type over a value they can see and what they can see has a unit on it. Escape puts it back. Both kinds of slider - the big ones in the settings and the small Rows and Columns ones on the cards.",
            "The \"x\" is gone from the size sliders. 1.00 says it.",
            "",
            "EDIT MODE IS THE FIRST ENTRY IN THE LEFT COLUMN. It was called Unlock Mode and it was a lone button at the bottom of the rail, on the argument that it is a thing you DO rather than a place you go. True, and beside the point - it is the thing this window exists to get you to, and it was the one item on the left that did not look like the others.",
        },
    },
    {
        version = "4.18.0",
        date = "2026-08-08",
        lines = {
            "NEW: EVERY CELL CAN BE EDITED ON ITS OWN. Click a cell in a bar card and press \"Just this one\" - colour, opacity, texture, which end the fill starts at, whether it fills up, border, backdrop, spark, charge marks, size, shape, and its own stack colours. So Bone Shield can be red with bands at five and ten while the two bars under it stay exactly as they were.",
            "",
            "EVERYTHING FOLLOWS THE BAR UNTIL YOU TOUCH IT. Change the bar's colour and every cell that has not been given its own follows along, including cells you edited something ELSE on - a cell that owns its colour still follows the bar for everything it does not own. \"Follow the bar again\" at the bottom hands the whole cell back.",
            "There is no per-setting inherit switch on purpose. Twenty rows each with two states to read is a panel nobody can use; one clear way back is better.",
            "",
            "The overrides belong to the SLOT, not to the spell sitting in it - the same rule as the size and the nudge. Drag Bone Shield to the top of the bar and the red stays where it was, because that is what lets a layout be handed to another character at all.",
            "",
            "The card previews it. A cell wearing its own colour is drawn in that colour in the editor, not just on screen.",
            "",
            "Text is deliberately not per-cell yet: three elements times seven controls each is a panel that cannot be read, and a bar whose cells use four fonts is not a design. If one cell needs its own countdown, say so and it gets added.",
        },
    },
    {
        version = "4.17.0",
        date = "2026-08-08",
        lines = {
            "DRAG A SPELL TO SORT A BAR. You asked for drag and drop in the bar cards - it was already there, and it was doing the wrong thing, which is very likely why it did not feel like sorting.",
            "It SWAPPED the two cells. Drag the third spell onto the first and you got third, second, first: the spell you never touched had moved as well. That is right for 'these two are in each other's places' and useless for putting a list in order - sorting four spells that way takes six drags and a plan.",
            "It reorders now. The spell you drag lands where you dropped it and everything else keeps its own order, one place along. Sorting a bar is one drag per spell.",
            "Hold SHIFT while dropping for the old swap. Both are worth having; only one of them can be the plain drag, and sorting is what you asked for.",
            "",
            "A gap in a bar counts as a position and travels with the sequence rather than being quietly filled, so a deliberate hole stays a hole.",
            "The cell's LOOK does not travel. Scale, nudge and kind belong to the slot, so a spell dragged to the front wears the front slot's look - which is the whole point of a slot having one.",
            "",
            "The tooltip on a filled cell now says all of this, since a drag nobody knows about is a drag nobody uses.",
        },
    },
    {
        version = "4.16.0",
        date = "2026-08-07",
        lines = {
            "NEW: SPARK. A bright line riding the moving edge of a tracking bar's fill. Under Bar fill.",
            "It costs nothing per frame, which is the small nice part: it is anchored to the fill's TEXTURE rather than positioned by hand, so the game moves it along with the clock and this addon never touches it again.",
            "",
            "NEW: CHARGE MARKS. One line across the fill per boundary between charges - three charges get two lines, at a third and two thirds. Its own colour, under Bar fill.",
            "They only appear on a spell that actually HAS more than one charge, so you can leave the setting on for a whole bar without marking everything on it. And they are anchored to the bar rather than to the fill, so they stay where they are while the fill moves past them - the exact opposite of the spark, on purpose.",
            "",
            "NOT BUILT, and here is why: keybind text on an icon. It reads like a small thing next to these two and it is not. Getting the key for a spell means walking every action bar and every binding name, resolving each slot to a spell - through macros as well - and then following the bar PAGE as it changes with your stance, your form and any vehicle you sit in. That is a subsystem, not a setting, and it is the wrong thing to start two days before the basics are due. Say the word and it gets built properly after.",
            "",
            "That is all four you picked out of the reference addon.",
        },
    },
    {
        version = "4.15.0",
        date = "2026-08-07",
        lines = {
            "NEW: GLOW IN THE REFRESH WINDOW. The tail of an aura where recasting it wastes nothing - pandemic, if you know the word. Under Effects, with its own colour.",
            "",
            "THIS ADDON DOES NOT WORK THE WINDOW OUT, and that is the interesting part. Doing so means dividing the time left by the full duration, and on this patch both of those numbers can be protected - dividing one protected number by another is exactly the thing that taints an addon and breaks it. So it is not calculated. Blizzard already knows where the window is, because its own Cooldown Manager marks it, and this addon simply asks. The question stops being arithmetic and becomes a fact somebody else worked out inside the game, where the numbers are readable.",
            "The catch is honest and the panel says it: it only lights for the spells you have switched pandemic alerts on for in Blizzard's own Cooldown Manager settings. Nothing here can turn that on for you.",
            "",
            "It outranks the plain glows, because it is the one that means press this now, and gives way to the last-seconds warning, which is more urgent still.",
            "",
            "Third of the four you picked. The small ones - charge marks, keybind text, the spark - are what is left.",
        },
    },
    {
        version = "4.14.0",
        date = "2026-08-07",
        lines = {
            "NEW: ACTIVE FOR. Some things the Cooldown Manager only ever shows as a cooldown - a trinket's use effect, a potion, a racial. It knows exactly when they come back and nothing at all about how long they LAST, so the one number you actually want mid-fight is on screen nowhere. Say how long it lasts once, and the cell runs that window every time you press it: our sweep, our fill, our timer.",
            "Settings, under Auras. The list offers the spells that are on your bars, because those are the only ones where declaring a window changes anything you can see. Zero switches it off.",
            "It is remembered for the whole ACCOUNT rather than the character, for the same reason the recorded procs are: how long a trinket lasts is a fact about the trinket, identical on every alt. It is not a piece of user interface.",
            "",
            "A spell the Cooldown Manager already tracks as a buff is left alone. Its own clock is measured inside the game and beats a number somebody typed, every time.",
            "The window follows a spell into its other form, so a state set before a talent transforms the spell still fires afterwards.",
            "",
            "BLIZZARD'S ICON IS NEVER TOUCHED - not its transparency, not its cooldown, not its parent. The window is drawn on a layer above it and taken away again, so if this addon is ever unloaded mid-window what is left behind is Blizzard's display exactly as it was. That is the reference addon's arrangement and it is the only one that cannot leave a mess.",
            "",
            "Second of the four you picked. Pandemic glow and the small ones - charge marks, keybind text, the spark - are still to come.",
        },
    },
    {
        version = "4.13.0",
        date = "2026-08-07",
        lines = {
            "NEW: STACK COLOURS. A tracking bar changes colour once the stack count reaches a number you pick, with three bands. This is the Bone Shield setting, and it is the thing the reference addon has that was worth having most.",
            "Below the lowest band the bar wears its normal Bar fill colour - so the way to say 'warn me under five' is a red fill with a band at 5 in your usual colour. There is no separate 'below' mode to get the wrong way round. Set a band's count to 0 to switch it off.",
            "",
            "WHY THIS WORKS AT ALL, because it is not obvious and it is the reason nobody else's addon does it on this patch: since 12.0 the stack count can arrive as a protected value. An addon may pass one along but may never compare it, add to it, or even test it for true - doing so taints the addon. So this addon does not compare it. Each band is a bar whose range is set to exactly the number you chose, the count is handed to the game, and the GAME decides whether it has been crossed. The comparison happens where it is allowed to happen.",
            "With several bands crossed at once, which colour wins cannot be decided by an if - there is nothing an addon may look at. It is decided by what is painted last: each band sits on top of the one below it, so the highest one you have crossed covers the rest. The approach is EllesmereUI's and it is the only legal way to do this.",
            "",
            "This is the first of four things you picked out of that addon. Custom active states, pandemic glow and the small ones - charge marks, keybind text, the spark - are next.",
        },
    },
    {
        version = "4.12.0",
        date = "2026-08-07",
        lines = {
            "You asked us to take the reference addon's Cooldown Manager apart instead of guessing. Its spell picker turned out to describe both of the things you reported - the list being wrong and the tracking being wrong - and it names five separate causes. All five are fixed here.",
            "",
            "FIXED, reported: the list mixed the groups together. Every group was numbered from 1, so the first Cooldown and the first Utility both scored 1 and the tie fell through to the name - which interleaved them alphabetically. Each group owns its own range now, and can never reach into the next one.",
            "FIXED, and this is the bigger half: the icons actually on your screen contributed no order at all. Their order was taken from a static list instead, when every one of those frames carries its own layout position - the number Blizzard lays the row out by. That number is now what the picker sorts by, so the list reads in the order you are looking at.",
            "FIXED: the list offered spells you had already removed. Spells dragged to 'Not Displayed' in Blizzard's own Cooldown Manager settings stay in the static category list forever, so they kept turning up here. The arrangement is read from Blizzard's settings directly now - what you hid stays hidden, and the order you dragged things into is the order you get.",
            "",
            "FIXED, reported: 'so many tracking errors'. A spell that a talent replaces changes the ID its frame reports - Frostbolt becoming Glacial Spike is the everyday case - and a cell holding the old ID simply stopped finding it. The spell was on screen and the cell went blank. A spell is now indexed under every form of itself, so a cell keeps it through the transform.",
            "FIXED: an override left behind by a talent you no longer have was still believed. Blizzard keeps reporting one after the talent is gone, so a cell would show a spell you cannot cast, with the wrong name and the wrong icon. It is only taken now when the game agrees you actually have it.",
            "FIXED, and this one was invisible until you knew where to look: while a buff was UP, its frame answers with a protected value that no addon may read - so resolution fell through to a generic entry for your spec. The icon changed into something unrecognisable for exactly as long as the buff lasted, then changed back. The last readable answer is remembered per cooldown and reused, which also means it corrects itself the moment you respec.",
            "",
            "The self test grew a 'Spell identity' section covering all of it - twenty more checks, two of which read your live Cooldown Manager without touching it. They were confirmed by putting the old bugs back and watching the suite go red.",
        },
    },
    {
        version = "4.11.1",
        date = "2026-08-07",
        lines = {
            "FIXED, reported: the spell list was sorted alphabetically, and alphabetical matched nothing. The panel says 'From your Cooldown Manager' at the top - and the Cooldown Manager has an order of its own, the one you arranged in Blizzard's Edit Mode and the one the icons appear in on screen. The list uses that order now. What you cannot cast still goes last in its group; names only break ties.",
            "FIXED: the counter at the bottom called everything 'cooldowns'. Four of the six groups in that list are not cooldowns.",
            "",
            "EVERY SETTING IS NOW SAVED UNDER THE CHARACTER AND REALM THAT MADE IT. Your rule, and your reason for it was the right one: keying by class or spec cannot work, because two characters of the same class write over each other. Your existing settings become the profile of whichever character you are on when this version first loads.",
            "The per-spec split from the last version survives INSIDE a profile: the spec you are in decides which spells its bars hold, so an offspec keeps its own picks without touching your main spec's.",
            "NEW, and the other half of the same idea: 'Take a layout from' in Settings. Pick another character and their bars arrive here - arrangements, sizes, looks, rules, positions - with every cell EMPTY. The spells stay behind on purpose: a Death Knight's cooldowns are not castable on a Paladin, and copying them is the exact bug this split exists to prevent.",
            "The recorded procs stay shared by the whole account. They are not a UI setting - they are measurements that take hours of playing to collect and are identical for anyone of that class and spec. Filing them per character would make every alt start the recording from nothing.",
            "FIXED: the first fight on a new character read as a wall of errors. Every proc the recorder had never seen printed its own line. Nothing was wrong - that is the recorder doing exactly its job - but announcing each discovery in the middle of a pull is not the way to say so. They are collected now and reported once.",
        },
    },
    {
        version = "4.10.0",
        date = "2026-08-07",
        lines = {
            "FIXED, reported: switch to another character and you were still looking at Death Knight cooldowns. The saved settings are account-wide, so every character got whatever the last one had picked.",
            "Your rule, and it is the right one - the layout is saved, the spells are not. So a bar is two things now. Everything about how it LOOKS and where it sits - the arrangement, the sizes, the colours, the rules, the per-cell overrides - stays shared by every character, because that is a user interface you built once and want everywhere. What each cell HOLDS is filed per class and spec.",
            "Two characters of the same class and spec share their picks. That is help rather than harm: they can cast the same things, and it is the same key the recorded procs have always used. Bars you already built are adopted by the first character that can identify its own spec - which is the character that built them.",
            "CHANGED, and it follows from the rule: a cell's own look now belongs to the SLOT rather than to the spell sitting in it. A slot scaled to 150% is part of a layout every character sees, so dragging a spell on one of them must not rearrange the bar for the rest. Moving a cell moves the spell and leaves the slot alone.",
            "REMOVED: the expanding proc ring. It went with the single-aura window back in 4.4.0 and nothing has called it since - 117 lines being loaded on every login for nothing.",
        },
    },
    {
        version = "4.9.0",
        date = "2026-08-07",
        lines = {
            "You asked whether we could look at how EllesmereUI solves this. We did, and it changed the architecture rather than a setting.",
            "TRACKING BARS ARE DRAWN NOW, not adopted. Blizzard's tracked-bar template is a whole bar - its own border, its own fill, its own two font strings - and none of it is ours to restyle. That is why what you saw never matched the preview, and why a border stayed on a bar whose thickness you had set to zero. There is no amount of stripping that turns somebody else's template into your design.",
            "So Blizzard's frame is kept alive as a DATA SOURCE at alpha 0, and the bar is drawn here with its value taken straight from Blizzard's status bar - passed through, never inspected, which is what keeps it legal with secret values. Blizzard's timer text comes across with it, so nothing is lost. This is exactly what the reference addon does, and the reason its tracking bars look like its own work.",
            "ICONS ARE STILL ADOPTED, on purpose. There the frame IS the art: Blizzard's icon is the right one for the talents you have, its swipe and charges are already correct, and drawing our own would mean reading aura data - which this patch forbids. The two halves are different problems and now get different answers.",
            "FIXED, reported: 'Fill up' moved the bar to the other end instead of making it fill up. It was one setting doing the wrong one of two jobs - the label promised a direction in TIME and the code asked for a direction in SPACE. Two settings now: Start on the right, and Fill up. If you had the old one switched on you get Fill up, because that is what its label told you it was.",
        },
    },
    {
        version = "4.8.0",
        date = "2026-08-07",
        lines = {
            "FIXED, reported: a picked texture never reached an adopted buff bar. Blizzard's tracked-bar template carries its own status bar and this addon had never touched it - so what was on screen was Blizzard's gradient, and no setting here could change it. It takes the bar fill's texture, colour and opacity now, which means the bar Blizzard draws and the bar we draw finally wear the same settings.",
            "The backdrop section now says where its plate is actually visible. It sits BEHIND the icon, and spell art is opaque - so on a square icon you will never see it whatever texture you pick. That was the other half of the same complaint, and it is a fact about the layer rather than a bug. For the coloured part of a bar, use Bar fill.",
            "REMOVED: Arc and Diagonal. They threw errors and did not look good, and neither was worth the six settings it cost. Any bar still on one moves onto Grid with everything on it intact. The geometry was correct and tested, so if they ever come back the fault to look for is in the panel around them.",
            "REMOVED: the Build on screen row in the settings panel. It was a second button for what the bar card already does, on a page you have to open first, and its control sat on top of its own text. The card's button is called Build on screen now and is the only way in.",
            "FIXED: the Cooldown Manager could only ever be found once. A negative answer was cached for the whole session - and the usual reason for that answer is the one the addon then tells you to fix, so doing what it asked changed nothing until a reload.",
            "FIXED, and this one was rude: releasing a frame left Blizzard's own display stripped. Every decoration this addon silences was pinned at zero by a hook that never stopped, so switching the takeover off handed Blizzard back a Cooldown Manager with no borders and no range veil until a reload. What each part looked like before is recorded and restored now, rounded corners included.",
            "FIXED: a spell that left a bar and came back had no border for the rest of the session. Releasing hid the frame the border is painted into, and nothing ever turned it back on.",
            "FIXED: Centre on screen did not centre a bar pinned by an edge - it put that EDGE on the centre line. Hiding the overlay was a dead end, because it hides the movers you would need to bring it back. And picking a bar with fewer cells than the last one left the selection reading slot 9 of 6.",
        },
    },
    {
        version = "4.7.0",
        date = "2026-08-07",
        lines = {
            "FIXED, and it is the one that was reported: switching pattern scattered the bar and never gave it back. Entering the puzzle wrote each cell's spread-out POSITION into the same two fields a nudge uses - and every other arrangement adds a nudge on top of the slot it worked out. So coming back to a grid displaced every cell by wherever the puzzle had put it, for ever, with nothing anywhere that would take it off again.",
            "The puzzle has two coordinate fields of its own now. Neither arrangement can see the other's, and the gain is not only that the grid comes back: you can move a bar into the puzzle, arrange it, go back to a grid and return - and find the puzzle exactly as you left it.",
            "FIXED: the Columns slider destroyed the arrangement. Every change compacted every spell to the front, so a deliberate hole in a row was gone after one drag with no way back. Cells keep their index now: 6 to 12 and back to 6 gives you exactly what was there.",
            "FIXED: the Columns slider DELETED spells. Shrinking a grid dropped whatever no longer had a cell. Anything that does not fit is parked now and comes back to its own slot the moment the bar is big enough again. A slider you drag to see what it looks like must not be able to lose your work.",
            "FIXED: moving into the puzzle flattened every arrangement that was not a grid - an arc arrived as a line. It is seeded from where the cells actually are now. And coming back no longer re-shapes the lattice: a 3x2 grid used to return as a row of six.",
            "FIXED: the Opacity slider moved half a bar. It reached the icons adopted from the Cooldown Manager and not the cells this addon draws itself, so a mixed bar faded unevenly.",
            "FIXED: a swapped spell arrived lit up, with the previous spell's sweep still running and a flash for a transition that belonged to a spell no longer on the bar. A cell is reused for whatever ends up at its index; the clock and the effect state now go with it.",
            "FIXED: effects were backwards on auras this addon draws. 'Ready' was read as 'the buff is NOT up', so the ready glow lit every proc that was down, and the ready flash fired when one ran out instead of when it landed.",
            "FIXED: the editor named a reason the renderer did not apply. In a kind of instance this addon has never heard of, the visibility panel said 'not in this kind of place' while the bar was - correctly - on screen.",
            "FIXED: turning one cell of an icon bar into a tracking bar hid the settings it needs. Width, height, the spell name and the fill were all on the other side of a test that asked about the BAR rather than about its cells.",
            "NEW: tracking bars this addon draws have a fill. They had none - a bar-shaped aura was a square icon and a hole beside it. It is a real status bar, it wears any LibSharedMedia texture including the twenty shipped here, and it drains on the clock this addon owns. Colour, opacity, texture and a fill-up direction. Buff bars adopted from Blizzard bring their own and ignore all of it, which the panel now says.",
            "NEW: /zs test. Forty-eight checks that can only be run inside the game, which is every check this addon has - arrangement geometry, the two coordinate systems, pattern round trips, the sliders, and the visibility rules against their own explanations. It runs on throwaway bars and never touches yours. Against the code as it stood this morning it reports eight failures, which is the entire point of it.",
            "NEW: Straighten, under Arrangement, and only offered when there is something to undo. Puts every cell back where the pattern wants it - and leaves the puzzle's own positions alone, because those belong to the other pattern.",
        },
    },
    {
        version = "4.6.0",
        date = "2026-08-07",
        lines = {
            "A bar is no longer a row of icons. It is an ARRANGEMENT, and there are five: Grid, Staggered, Arc, Diagonal and Puzzle. All five come out of one engine, and the preview in the window asks that same engine - so an arc curves in the editor too, and what you see there is what lands on screen.",
            "Arc puts the cells around a circle: set the span, where it starts and the radius, and a full 360 closes the ring. Leave the radius on auto and it works itself out from the cell size and how many there are, so four big icons and twelve small ones are both evenly spaced.",
            "Puzzle is the one to try. No lattice at all - every cell sits exactly where you dragged it. And it is not a separate mode bolted on: every arrangement adds each cell's own offset on top of whatever the lattice worked out, so nudging one icon out of a neat row and building a free-form layout are the same edit.",
            "With them: fill rows first or columns first, read left-to-right or right-to-left, top-to-bottom or bottom-to-top, and choose WHICH POINT of the bar stays put when it changes size. Pinned by the centre a bar spreads both ways when it gains a row; pin an edge and it grows away from that edge. That is the setting people mean by grow direction.",
            "NEW: per-cell overrides. Any single cell can carry its own scale, its own offset, its own kind and its own visibility. One icon in a row at 150%. A tracking bar in among the icons. A slot hidden while you decide. The settings travel with the SPELL - drag a cell somewhere else and they come along.",
            "NEW: BUILD MODE. /zs build, or the Build button on any bar card. The bar's panel shrinks out of the way and every cell gets a handle: drag it, scroll to scale it, Tab through the slots, arrows to nudge, Delete to empty, right click for kind, hide and reset. Dragging snaps to the bar's own raster; hold Alt for free hand.",
            "The spell palette opens beside it. Click a slot, click a spell, and the selection walks on to the next slot - so filling a bar is one click each instead of a trip through a window. Everything your Cooldown Manager knows is in there, greyed when it is not talented, so you can build a bar for the spec you are about to switch into.",
            "NEW: effects, all off until you ask. A FLASH when a cooldown lands, with a pulse count and a colour. An EDGE while the spell is up, optionally only in combat. A NAG: a spell that has been ready for six seconds in combat starts pulsing - for the defensive you keep forgetting. A last-seconds warning, a glow while a tracked aura is up, and greying out while a cooldown runs.",
            "What drives the effects is Blizzard's own answer to 'is this on a real cooldown', global cooldown excluded. Without that exclusion every spell in the game comes off cooldown every 1.5 seconds and the flash is a strobe.",
            "NEW: rules for when a bar is on screen at all. Combat, group size, target, rested area, and six kinds of place - world, dungeon, raid, scenario or delve, battleground, arena. Every rule has to agree, and every one of them starts on 'any', so a rule you have not set can never be the reason something is missing. Out of condition a bar is gone, or dimmed to whatever you choose - which is what you want while you are still arranging it.",
            "The window is denser and quieter. Every setting used to be a filled card with a gap around it, and forty of those is a brick wall. Rows are flat now, separated by a hairline, and only the row under the cursor gets a surface - the same page shows a third more of itself and reads as a list instead of a stack of boxes.",
            "New look to start from: Reactive. Clean, plus the things that move.",
        },
    },
    {
        version = "4.5.0",
        date = "2026-08-06",
        lines = {
            "Every icon on a bar now looks the way YOU want it, not four different ways. Blizzard's item frames are not one design - each of its four viewers decorates its own, with different masks, a shared overlay that lightens some and not others, a border here and a shadow there. All of that is stripped, and one set of settings is applied instead.",
            "NEW: fonts and textures from LibSharedMedia. That is not a design decision reversed - it is a registry, not a look. Every UI addon on your machine registers what it ships into it, so the fonts and bar textures you already have from ElvUI, WeakAuras or EllesmereUI turn up in our pickers under the names you already know. Ship our own instead and you would get a second, smaller, unfamiliar set with the one you wanted missing.",
            "The pickers show what they offer: a font renders its own name in itself, a texture draws a swatch behind it. A list of names would tell you nothing about either.",
            "Full styling per bar. Icon: crop and opacity. Border: thickness, colour, and a texture. Backdrop: on, colour, opacity, texture. Cooldown sweep: colour, opacity, leading edge. And each of the three text elements - countdown, stacks and charges, spell name - gets the same seven: on, font, size, colour, outline, one of nine positions, and a nudge in each direction.",
            "Same seven for all three on purpose. 'The countdown can be moved but the stack count cannot' is the kind of arbitrary limit that sends people looking for another addon.",
            "Four ready-made looks to start from - Clean, Blizzard, Heavy, Bare. Thirty-odd settings is what people ask for and nobody wants to build a look out of thirty-odd settings from nothing. They carry only what they are about: your grid, sizes and spacing are never touched.",
            "The whole styling block is folded away by default. The grid, the spells and the sizes are what you come back to; the knobs are set once and are one click from being out of the way.",
            "One font for everything, in Settings. Every piece of text on every bar follows it, and any single one of them can still be given its own - its font picker just offers 'Same as everywhere' at the top, which is what it starts on.",
            "Fonts and textures registered by a slower addon after login now reach your bars by themselves instead of waiting for a reload.",
            "Fixed, all found by looking at it running: the seven styling sections were laid out correctly and invisible, because a block placed by the grid gets a position and no width - notes set their own, which is why the note showed and the headings did not. The hovered menu entry was the one you could not read, because its highlight sat on a layer that draws above the text. And the window gave its width to the column with nothing to say: the rail is narrower, the settings column wider, so labels stop being clipped to 'T...'.",
            "Fixed: adopted icons came out at six sizes sitting at six offsets while the cells behind them were an even grid. Sizing the FRAME was never enough - each of Blizzard's four viewers anchors its own icon texture its own way, so the art has to be told to fill the frame too. Measured with /zs skin rather than guessed.",
        },
    },
    {
        version = "4.4.0",
        date = "2026-08-06",
        lines = {
            "The addon is called ZwoelfStuff now. DKstuff was never right - this is not about Death Knights, it is about cooldowns. It is named after the character it was written on: Zwoelf, EU Destromath. Your settings came with it.",
            "NEW: the bars actually render. A cell holds one of exactly two things, and they work in completely different ways.",
            "A Cooldown Manager cooldown is NOT drawn - Blizzard's own frame is adopted and moved onto your cell. That frame has the right icon, swipe, charges, stacks and timing, all computed inside the game where secret values are not a problem. Drawing our own would mean reading aura data, which this patch forbids outright.",
            "An aura proc has no frame to adopt - that is the whole reason the aura list exists - so its icon is drawn here and the clock is ours, started by the glow on the ability the aura empowers and running for the duration that was measured rather than assumed.",
            "Because an adopted icon stays Blizzard's child, it does not inherit our scale or our opacity. So a bar's Scale is a size multiplier rather than a frame scale, and its opacity is pushed into the icon itself. Anything else would have applied to half a bar and skipped the other half.",
            "It takes Blizzard's display over, and Settings says what that costs: Blizzard lays its row out without knowing an icon moved onto your bar, so it leaves a hole where that one used to be. There is no version of this where the original row still looks right, so cooldowns you did not place are hidden as well. Switch 'Take the display over' off to get that row back, holes included.",
            "NEW: Unlock Mode, built to work the way EllesmereUI's does - because that is what this addon is used next to, and a second set of rules for 'how do I move a thing' is a tax, not a feature.",
            "Every bar gets a panel with its live coordinates. Drag it, or select it and nudge with the arrow keys - Shift for 10. It snaps to the screen centre and to the other bars' centres and edges, with a guide line showing what it snapped to, and Alt switches snapping off while you drag.",
            "A cog on each panel: attach the bar to another one, centre it, open its options, switch it off. Shift + Right Click hides the overlay so you can see what is underneath - the panel stays, or that would be a one-way door. There is a grid, and Escape leaves.",
            "Bars can be ATTACHED to each other. Snapping puts a bar next to another one once; attaching keeps it there - move the one it hangs on and it comes along, resize it and the other stays flush. That is the difference between arranging a layout and rearranging it every time you change your mind. Dragging an attached bar adjusts its offset, and the same menu switches the side.",
            "NEW: the proc database is its own file, Core/KnownProcs.lua. It ships with the addon, so a fresh install already knows what a spec's procs are, and /zs auras export prints a block that pastes straight into it.",
            "/zs auras forget works on shipped entries too now. Deleting one the addon carries could only last until the file loaded again, so it is remembered as thrown away instead. /zs auras remember puts them all back.",
            "REMOVED: the Aura Display page and the single-buff window behind it. An aura is a cell on a bar now, so a second window showing one buff on its own was two answers to the same question. Every setting and command that only fed it is gone rather than left to rot.",
            "Fixed before it ever ran: EditMode reads the design system while it loads and was listed above the file that defines it - an instant crash at login. Also: dragging could stick to the cursor when you let go outside the panel, the aura catalogue was rebuilt once per cell instead of once per pass, and a hidden cell still answered the glow driving it.",
            "The minimap button shows the addon's own icon instead of whichever aura was being tracked. That changed under you and made the button hard to find again on a busy minimap.",
        },
    },
    {
        version = "4.3.0",
        date = "2026-08-06",
        lines = {
            "NEW: an Auras group in the spell list. What is shown is the aura's own icon; what drives it underneath is the action button that lights up when the aura is active. You see Boiling Point, the addon watches Blood Boil.",
            "It fills itself. Every proc this character raises is recorded, per class and spec, while you play - no learn mode, no button, no timing. A proc nobody knew about says so once in chat and is in the list from then on.",
            "The duration is MEASURED, and it knows when it is guessing. The time between the glow appearing and disappearing is the duration - but only when the glow ran out on its own. If you cast the ability just before it went out, the reading is a floor, not a fact: green means confirmed, orange with a > means at least that long.",
            "Which answers a question no amount of game knowledge would: a proc that never runs out by itself is a 'cast me' hint, not an aura. Nothing to look up, nothing to remember.",
            "A glow set belongs to a class and a spec, not to a player. /zs auras export prints this spec's set as a pasteable block, so one person playing one spec once is enough for everybody who plays it.",
            "Ready for 12.1: an entry carries three separate things - the ability that lights up (drives it today), the icon to show (a choice), and the aura's real ID (drives it on 12.1 through Blizzard_AuraContainer). The route switches by itself the moment that frame type exists. Set the aura ID with /zs auras bind <glowID> <auraID>.",
            "Tooltips on every spell, in the list and on the cells - the game's own tooltip, not a copy of it, so it stays current by itself. Under it goes only what the game cannot know: where that spell already sits on your bar, what actually drives an aura, and what a click would do.",
            "Three bugs the static check could not see, found by running it on a real character: every aura reported 'no route' so nothing could ever have displayed; the export read the raw recording instead of the merged view and would have shipped Blood Boil as Hemostasis, overwriting the one correct entry; and a measured duration overwrote the shipped one, dropping Boiling Point from 15s to 4s. Every measurement is a floor - casting the empowered ability ends the glow early - so the longest wins.",
            "Fixed: an error on every login. ADDON_LOADED called a seeding function the Auras module never had. Nothing was lost - it was the last line of the block - but it threw each time. There is no seeding step by design: the recorder registers itself, and the shipped set is merged when the list is read, so an update brings new data instead of being shadowed by an old copy in your saved variables.",
            "Fixed: /zs reset no longer erases recorded procs. Those are measurements that take hours of playing to collect and cannot be typed back in, so they are not settings. /zs auras forget <glowID> is how they go away.",
            "The one thing NOT done: a hardcoded table of aura-to-ability links. There is no API for that relationship, and writing one from memory is exactly what already produced two wrong spell IDs here. Everything shipped was observed and exported.",
            "Tried and rejected: reading the link out of talent descriptions. It works mechanically but answers the wrong question - the text names the ability a talent MODIFIES, not the one that lights up. On the only case that could be checked it returned Heart Strike where the truth is Blood Boil. The description scan is kept, demoted to suggesting a caption, where being wrong costs nothing.",
        },
    },
    {
        version = "4.2.0",
        date = "2026-08-06",
        lines = {
            "Two buttons at the bottom of the stack instead of one: Icon bar and Tracking bar. The two are a different thing to build, not a setting you change afterwards - they want different sizes, a different default grid and a different place on screen, so choosing up front means the first one is already right.",
            "The spell list is grouped: Cooldowns, Utility, Buffs, Buff bars, each under its own heading with a count, and filter buttons above to jump straight to one of them.",
            "Spells already on the bar you have selected are marked green, with a stripe down the left edge and the cell they sit in - so 'have I got that one already' is answered without reading a word.",
            "Spells your current talent build does not have are greyed out and sorted to the end of their group. They stay pickable, because a bar is often built for the build you are about to switch into.",
            "No more duplicates. The list is keyed by spell now, not by cooldown: several cooldown entries can point at one spell, and seeing Anti-Magic Shell three times was noise.",
            "One rule under every heading, across the whole window, at the same height in all three columns - including under ZwoelfStuff itself. Three separate lines with three sets of padding never quite agree, and the eye reads the disagreement as sloppiness.",
            "Modernised: a graphite palette with more space between the surface levels, empty cells recessed like wells rather than raised like buttons, the selected function marked with an accent bar instead of a block of tinted orange, and the add buttons quietened down so the bars are what you look at.",
        },
    },
    {
        version = "4.1.0",
        date = "2026-08-06",
        lines = {
            "The window is an app now, in three fixed columns: what you are working on (left), what you are working on it with (middle), and what you put into it (right).",
            "The middle shows EVERY bar you own, under each other, scrollable. Each one is a card that is the bar itself - the same grid, the same order - with Rows and Columns as two sliders right underneath it, and 'Add new bar' at the bottom of the stack where the next one appears.",
            "The left column no longer lists your bars. It lists what the addon does: Cooldowns, Aura Display, Settings, Diagnostics, About, Changelog. Listing bars there meant picking one before you could see any of them.",
            "The right column lists every cooldown your Cooldown Manager knows, all the time, with a search box. Click a cell, click a spell - and it moves on to the next empty cell by itself, so filling a bar is click, click, click.",
            "Press Options on a bar's header and that same right column becomes the settings for that bar: name, shape, sizes, spacing, scale, opacity, border. Done takes you back to the spells.",
            "NEW: a look can be reused. Copy it from another bar in one click, or save it as a named preset and apply it to any bar later. Only sizes, spacing and colours travel - the spells and the grid always stay with their own bar.",
            "Nothing in the window is see-through any more. Translucent panels over a moving 3D world are unreadable; the layering is done with distinct opaque surfaces instead, which is also what makes the depth actually read.",
            "Self-built throughout, as ever: the compact slider, the cards, the navigation marks and the scrollbar are all drawn from colour textures, so no art path and no Blizzard template can break them.",
            "Fixed: the command list offered commands that no longer exist, and the minimap tooltip advertised a panel that is parked until 12.1.",
            "Still nothing rendered on screen from bars - the operation comes first, on purpose.",
        },
    },
    {
        version = "4.0.0",
        date = "2026-08-06",
        lines = {
            "Different approach. Everything before this tried to track auras itself, which cannot work on patch 12.0: aura data is secret, and the sanctioned replacement (Blizzard_AuraContainer) does not exist until 12.1 - measured on this client, creating one fails outright.",
            "Blizzard's Cooldown Manager already does all of it. It knows the spells, binds the auras and has the timing. Every addon that does cooldowns on this patch works the same way: it takes Blizzard's item frames and restyles them. ZwoelfStuff does that now too.",
            "NEW: bars. A bar is a grid of cells; each cell holds one spell. Set rows and columns and the grid in the options changes with them - that grid IS the bar, same rows, same columns, same order.",
            "Click an empty cell to choose a spell (the list comes from your own Cooldown Manager), drag one cell onto another to swap, right click to clear. Changing rows or columns re-flows what is there instead of scrambling or dropping it.",
            "The whole aura-tracking stack is parked until 12.1 - Engine, Groups, Catalog, CoTanks, Probe. The code is correct, it simply cannot run on a 12.0 client. The reason is written into the TOC next to them.",
            "The proc-glow display for Boiling Point stays: that buff is not in the Cooldown Manager data set, so it remains the only way to see it.",
            "On screen nothing is rendered from bars yet - the editor comes first, on purpose.",
        },
    },
    {
        version = "3.4.0",
        date = "2026-08-05",
        lines = {
            "THE BIG ONE: the aura engine reported itself unavailable on every client, so every engine-backed feature was dead - the display's aura slot, the co-tank aura strips, and every tracking group. Only the proc-glow route ever worked.",
            "Cause: the availability check tried to LoadAddOn('Blizzard_AuraContainer') first and gave up when that failed. There is no such addon. The AuraContainer frame type is built into the client - every reference implementation just calls CreateFrame. The gate could never open.",
            "The check now builds a container and looks at it, which is the only honest test, and reports WHY when it says no instead of a bare 'not available'.",
            "NEW: /zs group status - per spell, one of: slot refused (a bug here, with the error), registered but never seen (the ID is wrong or the aura was never up), or bound. Turns 'only one icon shows' into an answer.",
            "Slots that the engine refuses now say so in chat instead of vanishing into a pcall, and they keep their place in the order rather than silently closing the gap.",
        },
    },
    {
        version = "3.3.0",
        date = "2026-08-05",
        lines = {
            "NEW: /zs probe <spellID> - does that ID actually bind? A hidden slot is bound to the ID and the engine shows it exactly while that aura is on you, so the answer comes from your own client instead of from a database or from memory.",
            "It reports every bind and unbind with a timestamp, which is what tells a CAST spell apart from the aura it applies - the trap that cost this project two rounds on Boiling Point and another on Death and Decay.",
            "Nothing is read from the aura or even from the button: the show and hide handlers are registered inside the initializer, the one window where touching an engine button is legal, and the engine does the telling.",
            "Also on the Diagnostics page: type an ID, press Enter, watch for 20 seconds.",
        },
    },
    {
        version = "3.2.0",
        date = "2026-08-05",
        lines = {
            "Fixed: nothing could be dragged into place. The aura containers lay over their own anchor frames and swallowed every click - engine containers come mouse-enabled, and only the buttons had been told otherwise. Unlocking looked like it did nothing at all.",
            "Fixed: an unlocked group with no active auras was an invisible rectangle. Unlocked groups now show a tinted drag surface and stay visible even when switched off, so they can be placed before they ever light up.",
            "The spell list is now a row of icons. Click + to add, drag an icon to move it, right click to remove it. What you see is the order the group renders in - no more arrow buttons on a list of text rows.",
            "The group picker now creates and deletes groups itself: pick a group, or use '+ New icon group' / '+ New bar group' at the bottom of the same menu, with a delete on every entry.",
            "The spell browser opens with the cursor already in the search box - type the name, click the hit.",
        },
    },
    {
        version = "3.1.0",
        date = "2026-08-05",
        lines = {
            "The settings window was rebuilt. It was a flat list of steppers and checkboxes; it is now a proper panel - a sidebar of modules, a titled content area, settings as two-column cards, and a footer that stays put.",
            "New controls, all self-built and all matching: on/off switches instead of checkboxes, real sliders with a numeric readout, dropdown menus instead of button rows, and colour swatches that open the game's colour picker.",
            "Blizzard's slider, dropdown and checkbox templates have been renamed repeatedly across expansions and cannot be styled to match a custom panel, so none of them are used. Nothing here can break on a template rename.",
            "Pages are built on first view instead of at login, so the panel costs only what you actually open.",
            "New Diagnostics page: the check, dump, scan and catalogue commands as buttons, plus whether the aura engine is available on this client.",
            "New General page: the minimap button toggles and a two-step reset-everything.",
            "Rows that do not apply to your current settings are dropped from the layout rather than left visible, so the page closes up instead of showing gaps.",
        },
    },
    {
        version = "3.0.1",
        date = "2026-08-05",
        lines = {
            "Fixed: tracking groups threw at login. ns.CreateBorder returns a table of four textures, not a frame, so it never had Hide/Show/SetShown - and the group anchor called Hide() on its outline.",
            "Fixed: that one error disabled every feature after it. The login handler ran the features in one straight line, so a broken group meant no co-tank panel and no minimap button either. Each feature now starts on its own and a failure is reported by name.",
            "In fixed mode the slot container is sized to its group anchor instead of staying 1x1, so nothing can clip the buttons.",
            "The spell browser now repopulates itself after a respec or spec switch.",
        },
    },
    {
        version = "3.0.0",
        date = "2026-08-05",
        lines = {
            "NEW: tracking groups. As many as you like, icons or bars, each with its own spells, position, size and colours.",
            "Arrange them any way: grows left or right, rows up or down, fill by rows or by columns, wrap after any number for a grid. All of it applies live, in combat included.",
            "Two ordering modes. 'My order' gives every spell one fixed place that never moves, so muscle memory holds and bars can show spell names. 'Auto' lets the game pick and sort, which stays compact but moves things around.",
            "NEW: spell browser. Your talents, your whole spellbook including the specs you are NOT playing, and Blizzard's Cooldown Manager set - all read out of the live client, so it follows every respec and every patch by itself. Nothing is hardcoded. Manual spell IDs still work.",
            "NEW: bars can now actually drain. button:SetDurationBar hands a StatusBar to the game engine, which drains it from the aura's own duration - so a bar works even for auras no addon may read.",
            "Fixed, and this is the big one: the engine slot never bound anything. It used AddAuraFilter/AddAuraFrame, which do not exist. The real API is AddAuraGroup/AddAuraSlot with an initializeFrame callback - verified against four working 12.1 addons on this machine rather than guessed.",
            "Fixed: the container was given its unit BEFORE its content. Unit assignment re-evaluates event registrations, and those are gated on the container already having groups, so UNIT_AURA stayed unregistered and the container silently never updated.",
        },
    },
    {
        version = "2.1.0",
        date = "2026-08-05",
        lines = {
            "Minimap button: left click opens the settings, right click toggles the co-tank panel, drag moves it around the minimap edge. Self-built, no LibDBIcon.",
            "The addon now has an icon in the AddOn list and the addon compartment.",
            "Toggle both from the options, or with /zs minimap.",
        },
    },
    {
        version = "2.0.0",
        date = "2026-08-05",
        lines = {
            "NEW: co-tank panel. One row per tank in the group - health bar, name, health percent, every debuff on them and every buff they carry.",
            "Auras on other players are secret exactly like your own, so an addon cannot read a co-tank's boss debuff stacks at all. The panel hands the widgets to the game engine, which binds and times them itself.",
            "NEW: engine aura slot for the tracked buff. Blizzard_AuraContainer can bind a secret aura by spell ID and render it - real icon, real duration, real stacks. This replaces the proc-glow proxy where it works.",
            "The proc glow stays as the fallback and still drives the proc flash. Switch with /zs source engine or /zs source glow.",
            "Fixed: the options window clipped its last section - the proc glow row was added without raising the window height.",
            "Fixed: reserved aura rows left a large empty gap; three rows instead of five.",
            "Fixed: the inactive greyed-out state dimmed the whole frame, which would have dimmed the engine's aura button too. Only the placeholder dims now.",
        },
    },
    {
        version = "1.4.0",
        date = "2026-08-05",
        lines = {
            "Measured in game: every single buff on the player came back secret (0 readable, 18 secret). No addon can identify an aura this way - not Boiling Point, not any other.",
            "The cooldown viewers do hand out plain data, but only for buffs the Cooldown Manager tracks, and Boiling Point is not one of them.",
            "So the buff itself cannot be read. The proc can: Boiling Point empowers Blood Boil, and C_SpellActivationOverlay.IsSpellOverlayed(50842) is a plain boolean that never touches aura data.",
            "Route 5 added, driven off that proc glow. Timing comes from our own clock and our own 15s constant, so the swipe and countdown work normally.",
            "This is the same combat-safe technique EllesmereUIAuraBuffReminders uses for beacons it cannot read either.",
            "Added /zs glowlog to find the glowing spell ID, /zs glow <id or name> to set it, /zs glowduration to tune it.",
            "The dump now reports which APIs actually exist, combat state, whether the spell is in the Cooldown Manager data set at all, and the override-spell state - so 'API missing' can never again look like 'aura not found'.",
        },
    },
    {
        version = "1.3.0",
        date = "2026-08-05",
        lines = {
            "The cooldown viewer route only searched the two buff viewers; it now searches all four, including Essential and Utility.",
            "Added a fourth route: icon match. If a secret aura keeps a readable icon, it can be identified by comparing it against our own spell's icon.",
            "Added /zs dump - dumps every cooldown viewer entry and every player buff, marking icon matches. Run it WHILE the buff is up; it is the command that shows what actually exists.",
            "/zs check now reports all four routes.",
        },
    },
    {
        version = "1.2.0",
        date = "2026-08-05",
        lines = {
            "Fixed: Boiling Point was never found. It is a secret rotational proc, and those are invisible to BOTH aura queries - by ID and by name alike.",
            "Added a third lookup route: Blizzard's own cooldown viewer buff frames. They still bind such procs, and expose a plain auraInstanceID that yields duration and stacks.",
            "The irony: the Cooldown Manager will not let you add this buff, but it knows exactly when it is up.",
            "Display now only re-renders when the shown aura actually changes, so the polling never restarts the cooldown swipe.",
            "/zs check now reports all three routes separately, and says whether timing is available or only presence.",
            "Added /zs scan - lists the buffs an addon is allowed to read and counts the secret ones.",
        },
    },
    {
        version = "1.1.0",
        date = "2026-08-05",
        lines = {
            "Fixed: the addon threw on every aura change. Patch 12.0 made aura fields 'secret values', and a secret may not be used as a table key - which is exactly how 1.0.0 matched spell IDs.",
            "Aura lookup reversed: the spell ID now goes INTO the query via GetPlayerAuraBySpellID, so nothing secret is ever read.",
            "Added a fallback lookup by spell name, for auras whose applied ID differs from the tooltip or talent ID.",
            "Cooldown swipe now armed from a DurationObject, the only carrier a cooldown frame accepts since 12.0.1.",
            "Remaining time and stack count are now rendered by the game engine, since an addon can no longer compute them.",
            "Removed the 'red timer in the last 3s' option - it required comparing a secret value.",
            "Added /zs check and /zs status, plus a Diagnose button, to tell a wrong spell ID apart from a broken display.",
        },
    },
    {
        version = "1.0.0",
        date = "2026-08-05",
        lines = {
            "Isolated aura display - shows a single buff the Cooldown Manager cannot track.",
            "Ships tracking Boiling Point (spell 1265968), the Blood Death Knight Blood Boil empowerment.",
            "Two display modes: icon with cooldown swipe, or icon plus shrinking bar.",
            "Optional 'always show' mode that greys the display out while the aura is down.",
            "Self-built proc glow, optional proc sound, optional warning colour in the last seconds.",
            "Movable and lockable display with a 15 second test preview for positioning.",
            "Additional spell IDs can be tracked; the list doubles as a priority order.",
            "Full slash command set under /zs.",
        },
    },
}
