---------------------------------------------------------------------------
-- Changelog data.
--
-- Kept in its own file: it only ever grows, and it is data, not layout.
-- Rendered by the Changelog page in Options.lua.
---------------------------------------------------------------------------
local _, ns = ...

ns.CHANGELOG = {
    {
        version = "4.7.0",
        date = "2026-08-07",
        lines = {
            "FIXED, and it is the one that was reported: switching pattern scattered the bar and never gave it back. Entering the puzzle wrote each cell's spread-out POSITION into the same two fields a nudge uses - and every other arrangement adds a nudge on top of the slot it worked out. So coming back to a grid displaced every cell by wherever the puzzle had put it, for ever, with nothing anywhere that would take it off again.",
            "The puzzle has two coordinate fields of its own now. Neither arrangement can see the other's, and the gain is not only that the grid comes back: you can move a bar into the puzzle, arrange it, go back to a grid and return - and find the puzzle exactly as you left it.",
            "FIXED: the Columns slider destroyed the arrangement. Every change compacted every spell to the front, so a deliberate hole in a row was gone after one drag with no way back. Cells keep their index now: 6 to 12 and back to 6 gives you exactly what was there.",
            "FIXED: the Columns slider DELETED spells. Shrinking a grid dropped whatever no longer had a cell. Anything that does not fit is parked now and comes back to its own slot the moment the bar is big enough again. A slider you drag to see what it looks like must not be able to lose your work.",
            "FIXED: moving into the puzzle flattened every arrangement that was not a grid - an arc arrived as a line. It is seeded from where the cells actually are now. And coming back no longer re-shapes the lattice: a 3x2 grid used to return as a row of six.",
            "FIXED: the Opacity slider moved half a bar. It reached the icons adopted from the Cooldown Manager and not the cells this addon draws itself, so a mixed bar faded unevenly.",
            "FIXED: a swapped spell arrived lit up, with the previous spell's sweep still running and a flash for a transition that belonged to a spell no longer on the bar. A cell is reused for whatever ends up at its index; the clock and the effect state now go with it.",
            "FIXED: effects were backwards on auras this addon draws. 'Ready' was read as 'the buff is NOT up', so the ready glow lit every proc that was down, and the ready flash fired when one ran out instead of when it landed.",
            "FIXED: the editor named a reason the renderer did not apply. In a kind of instance this addon has never heard of, the visibility panel said 'not in this kind of place' while the bar was - correctly - on screen.",
            "FIXED: turning one cell of an icon bar into a tracking bar hid the settings it needs. Width, height, the spell name and the fill were all on the other side of a test that asked about the BAR rather than about its cells.",
            "NEW: tracking bars this addon draws have a fill. They had none - a bar-shaped aura was a square icon and a hole beside it. It is a real status bar, it wears any LibSharedMedia texture including the twenty shipped here, and it drains on the clock this addon owns. Colour, opacity, texture and a fill-up direction. Buff bars adopted from Blizzard bring their own and ignore all of it, which the panel now says.",
            "NEW: /zs test. Forty-eight checks that can only be run inside the game, which is every check this addon has - arrangement geometry, the two coordinate systems, pattern round trips, the sliders, and the visibility rules against their own explanations. It runs on throwaway bars and never touches yours. Against the code as it stood this morning it reports eight failures, which is the entire point of it.",
            "NEW: Straighten, under Arrangement, and only offered when there is something to undo. Puts every cell back where the pattern wants it - and leaves the puzzle's own positions alone, because those belong to the other pattern.",
        },
    },
    {
        version = "4.6.0",
        date = "2026-08-07",
        lines = {
            "A bar is no longer a row of icons. It is an ARRANGEMENT, and there are five: Grid, Staggered, Arc, Diagonal and Puzzle. All five come out of one engine, and the preview in the window asks that same engine - so an arc curves in the editor too, and what you see there is what lands on screen.",
            "Arc puts the cells around a circle: set the span, where it starts and the radius, and a full 360 closes the ring. Leave the radius on auto and it works itself out from the cell size and how many there are, so four big icons and twelve small ones are both evenly spaced.",
            "Puzzle is the one to try. No lattice at all - every cell sits exactly where you dragged it. And it is not a separate mode bolted on: every arrangement adds each cell's own offset on top of whatever the lattice worked out, so nudging one icon out of a neat row and building a free-form layout are the same edit.",
            "With them: fill rows first or columns first, read left-to-right or right-to-left, top-to-bottom or bottom-to-top, and choose WHICH POINT of the bar stays put when it changes size. Pinned by the centre a bar spreads both ways when it gains a row; pin an edge and it grows away from that edge. That is the setting people mean by grow direction.",
            "NEW: per-cell overrides. Any single cell can carry its own scale, its own offset, its own kind and its own visibility. One icon in a row at 150%. A tracking bar in among the icons. A slot hidden while you decide. The settings travel with the SPELL - drag a cell somewhere else and they come along.",
            "NEW: BUILD MODE. /zs build, or the Build button on any bar card. The bar's panel shrinks out of the way and every cell gets a handle: drag it, scroll to scale it, Tab through the slots, arrows to nudge, Delete to empty, right click for kind, hide and reset. Dragging snaps to the bar's own raster; hold Alt for free hand.",
            "The spell palette opens beside it. Click a slot, click a spell, and the selection walks on to the next slot - so filling a bar is one click each instead of a trip through a window. Everything your Cooldown Manager knows is in there, greyed when it is not talented, so you can build a bar for the spec you are about to switch into.",
            "NEW: effects, all off until you ask. A FLASH when a cooldown lands, with a pulse count and a colour. An EDGE while the spell is up, optionally only in combat. A NAG: a spell that has been ready for six seconds in combat starts pulsing - for the defensive you keep forgetting. A last-seconds warning, a glow while a tracked aura is up, and greying out while a cooldown runs.",
            "What drives the effects is Blizzard's own answer to 'is this on a real cooldown', global cooldown excluded. Without that exclusion every spell in the game comes off cooldown every 1.5 seconds and the flash is a strobe.",
            "NEW: rules for when a bar is on screen at all. Combat, group size, target, rested area, and six kinds of place - world, dungeon, raid, scenario or delve, battleground, arena. Every rule has to agree, and every one of them starts on 'any', so a rule you have not set can never be the reason something is missing. Out of condition a bar is gone, or dimmed to whatever you choose - which is what you want while you are still arranging it.",
            "The window is denser and quieter. Every setting used to be a filled card with a gap around it, and forty of those is a brick wall. Rows are flat now, separated by a hairline, and only the row under the cursor gets a surface - the same page shows a third more of itself and reads as a list instead of a stack of boxes.",
            "New look to start from: Reactive. Clean, plus the things that move.",
        },
    },
    {
        version = "4.5.0",
        date = "2026-08-06",
        lines = {
            "Every icon on a bar now looks the way YOU want it, not four different ways. Blizzard's item frames are not one design - each of its four viewers decorates its own, with different masks, a shared overlay that lightens some and not others, a border here and a shadow there. All of that is stripped, and one set of settings is applied instead.",
            "NEW: fonts and textures from LibSharedMedia. That is not a design decision reversed - it is a registry, not a look. Every UI addon on your machine registers what it ships into it, so the fonts and bar textures you already have from ElvUI, WeakAuras or EllesmereUI turn up in our pickers under the names you already know. Ship our own instead and you would get a second, smaller, unfamiliar set with the one you wanted missing.",
            "The pickers show what they offer: a font renders its own name in itself, a texture draws a swatch behind it. A list of names would tell you nothing about either.",
            "Full styling per bar. Icon: crop and opacity. Border: thickness, colour, and a texture. Backdrop: on, colour, opacity, texture. Cooldown sweep: colour, opacity, leading edge. And each of the three text elements - countdown, stacks and charges, spell name - gets the same seven: on, font, size, colour, outline, one of nine positions, and a nudge in each direction.",
            "Same seven for all three on purpose. 'The countdown can be moved but the stack count cannot' is the kind of arbitrary limit that sends people looking for another addon.",
            "Four ready-made looks to start from - Clean, Blizzard, Heavy, Bare. Thirty-odd settings is what people ask for and nobody wants to build a look out of thirty-odd settings from nothing. They carry only what they are about: your grid, sizes and spacing are never touched.",
            "The whole styling block is folded away by default. The grid, the spells and the sizes are what you come back to; the knobs are set once and are one click from being out of the way.",
            "One font for everything, in Settings. Every piece of text on every bar follows it, and any single one of them can still be given its own - its font picker just offers 'Same as everywhere' at the top, which is what it starts on.",
            "Fonts and textures registered by a slower addon after login now reach your bars by themselves instead of waiting for a reload.",
            "Fixed, all found by looking at it running: the seven styling sections were laid out correctly and invisible, because a block placed by the grid gets a position and no width - notes set their own, which is why the note showed and the headings did not. The hovered menu entry was the one you could not read, because its highlight sat on a layer that draws above the text. And the window gave its width to the column with nothing to say: the rail is narrower, the settings column wider, so labels stop being clipped to 'T...'.",
            "Fixed: adopted icons came out at six sizes sitting at six offsets while the cells behind them were an even grid. Sizing the FRAME was never enough - each of Blizzard's four viewers anchors its own icon texture its own way, so the art has to be told to fill the frame too. Measured with /zs skin rather than guessed.",
        },
    },
    {
        version = "4.4.0",
        date = "2026-08-06",
        lines = {
            "The addon is called ZwoelfStuff now. DKstuff was never right - this is not about Death Knights, it is about cooldowns. It is named after the character it was written on: Zwoelf, EU Destromath. Your settings came with it.",
            "NEW: the bars actually render. A cell holds one of exactly two things, and they work in completely different ways.",
            "A Cooldown Manager cooldown is NOT drawn - Blizzard's own frame is adopted and moved onto your cell. That frame has the right icon, swipe, charges, stacks and timing, all computed inside the game where secret values are not a problem. Drawing our own would mean reading aura data, which this patch forbids outright.",
            "An aura proc has no frame to adopt - that is the whole reason the aura list exists - so its icon is drawn here and the clock is ours, started by the glow on the ability the aura empowers and running for the duration that was measured rather than assumed.",
            "Because an adopted icon stays Blizzard's child, it does not inherit our scale or our opacity. So a bar's Scale is a size multiplier rather than a frame scale, and its opacity is pushed into the icon itself. Anything else would have applied to half a bar and skipped the other half.",
            "It takes Blizzard's display over, and Settings says what that costs: Blizzard lays its row out without knowing an icon moved onto your bar, so it leaves a hole where that one used to be. There is no version of this where the original row still looks right, so cooldowns you did not place are hidden as well. Switch 'Take the display over' off to get that row back, holes included.",
            "NEW: Unlock Mode, built to work the way EllesmereUI's does - because that is what this addon is used next to, and a second set of rules for 'how do I move a thing' is a tax, not a feature.",
            "Every bar gets a panel with its live coordinates. Drag it, or select it and nudge with the arrow keys - Shift for 10. It snaps to the screen centre and to the other bars' centres and edges, with a guide line showing what it snapped to, and Alt switches snapping off while you drag.",
            "A cog on each panel: attach the bar to another one, centre it, open its options, switch it off. Shift + Right Click hides the overlay so you can see what is underneath - the panel stays, or that would be a one-way door. There is a grid, and Escape leaves.",
            "Bars can be ATTACHED to each other. Snapping puts a bar next to another one once; attaching keeps it there - move the one it hangs on and it comes along, resize it and the other stays flush. That is the difference between arranging a layout and rearranging it every time you change your mind. Dragging an attached bar adjusts its offset, and the same menu switches the side.",
            "NEW: the proc database is its own file, Core/KnownProcs.lua. It ships with the addon, so a fresh install already knows what a spec's procs are, and /zs auras export prints a block that pastes straight into it.",
            "/zs auras forget works on shipped entries too now. Deleting one the addon carries could only last until the file loaded again, so it is remembered as thrown away instead. /zs auras remember puts them all back.",
            "REMOVED: the Aura Display page and the single-buff window behind it. An aura is a cell on a bar now, so a second window showing one buff on its own was two answers to the same question. Every setting and command that only fed it is gone rather than left to rot.",
            "Fixed before it ever ran: EditMode reads the design system while it loads and was listed above the file that defines it - an instant crash at login. Also: dragging could stick to the cursor when you let go outside the panel, the aura catalogue was rebuilt once per cell instead of once per pass, and a hidden cell still answered the glow driving it.",
            "The minimap button shows the addon's own icon instead of whichever aura was being tracked. That changed under you and made the button hard to find again on a busy minimap.",
        },
    },
    {
        version = "4.3.0",
        date = "2026-08-06",
        lines = {
            "NEW: an Auras group in the spell list. What is shown is the aura's own icon; what drives it underneath is the action button that lights up when the aura is active. You see Boiling Point, the addon watches Blood Boil.",
            "It fills itself. Every proc this character raises is recorded, per class and spec, while you play - no learn mode, no button, no timing. A proc nobody knew about says so once in chat and is in the list from then on.",
            "The duration is MEASURED, and it knows when it is guessing. The time between the glow appearing and disappearing is the duration - but only when the glow ran out on its own. If you cast the ability just before it went out, the reading is a floor, not a fact: green means confirmed, orange with a > means at least that long.",
            "Which answers a question no amount of game knowledge would: a proc that never runs out by itself is a 'cast me' hint, not an aura. Nothing to look up, nothing to remember.",
            "A glow set belongs to a class and a spec, not to a player. /zs auras export prints this spec's set as a pasteable block, so one person playing one spec once is enough for everybody who plays it.",
            "Ready for 12.1: an entry carries three separate things - the ability that lights up (drives it today), the icon to show (a choice), and the aura's real ID (drives it on 12.1 through Blizzard_AuraContainer). The route switches by itself the moment that frame type exists. Set the aura ID with /zs auras bind <glowID> <auraID>.",
            "Tooltips on every spell, in the list and on the cells - the game's own tooltip, not a copy of it, so it stays current by itself. Under it goes only what the game cannot know: where that spell already sits on your bar, what actually drives an aura, and what a click would do.",
            "Three bugs the static check could not see, found by running it on a real character: every aura reported 'no route' so nothing could ever have displayed; the export read the raw recording instead of the merged view and would have shipped Blood Boil as Hemostasis, overwriting the one correct entry; and a measured duration overwrote the shipped one, dropping Boiling Point from 15s to 4s. Every measurement is a floor - casting the empowered ability ends the glow early - so the longest wins.",
            "Fixed: an error on every login. ADDON_LOADED called a seeding function the Auras module never had. Nothing was lost - it was the last line of the block - but it threw each time. There is no seeding step by design: the recorder registers itself, and the shipped set is merged when the list is read, so an update brings new data instead of being shadowed by an old copy in your saved variables.",
            "Fixed: /zs reset no longer erases recorded procs. Those are measurements that take hours of playing to collect and cannot be typed back in, so they are not settings. /zs auras forget <glowID> is how they go away.",
            "The one thing NOT done: a hardcoded table of aura-to-ability links. There is no API for that relationship, and writing one from memory is exactly what already produced two wrong spell IDs here. Everything shipped was observed and exported.",
            "Tried and rejected: reading the link out of talent descriptions. It works mechanically but answers the wrong question - the text names the ability a talent MODIFIES, not the one that lights up. On the only case that could be checked it returned Heart Strike where the truth is Blood Boil. The description scan is kept, demoted to suggesting a caption, where being wrong costs nothing.",
        },
    },
    {
        version = "4.2.0",
        date = "2026-08-06",
        lines = {
            "Two buttons at the bottom of the stack instead of one: Icon bar and Tracking bar. The two are a different thing to build, not a setting you change afterwards - they want different sizes, a different default grid and a different place on screen, so choosing up front means the first one is already right.",
            "The spell list is grouped: Cooldowns, Utility, Buffs, Buff bars, each under its own heading with a count, and filter buttons above to jump straight to one of them.",
            "Spells already on the bar you have selected are marked green, with a stripe down the left edge and the cell they sit in - so 'have I got that one already' is answered without reading a word.",
            "Spells your current talent build does not have are greyed out and sorted to the end of their group. They stay pickable, because a bar is often built for the build you are about to switch into.",
            "No more duplicates. The list is keyed by spell now, not by cooldown: several cooldown entries can point at one spell, and seeing Anti-Magic Shell three times was noise.",
            "One rule under every heading, across the whole window, at the same height in all three columns - including under ZwoelfStuff itself. Three separate lines with three sets of padding never quite agree, and the eye reads the disagreement as sloppiness.",
            "Modernised: a graphite palette with more space between the surface levels, empty cells recessed like wells rather than raised like buttons, the selected function marked with an accent bar instead of a block of tinted orange, and the add buttons quietened down so the bars are what you look at.",
        },
    },
    {
        version = "4.1.0",
        date = "2026-08-06",
        lines = {
            "The window is an app now, in three fixed columns: what you are working on (left), what you are working on it with (middle), and what you put into it (right).",
            "The middle shows EVERY bar you own, under each other, scrollable. Each one is a card that is the bar itself - the same grid, the same order - with Rows and Columns as two sliders right underneath it, and 'Add new bar' at the bottom of the stack where the next one appears.",
            "The left column no longer lists your bars. It lists what the addon does: Cooldowns, Aura Display, Settings, Diagnostics, About, Changelog. Listing bars there meant picking one before you could see any of them.",
            "The right column lists every cooldown your Cooldown Manager knows, all the time, with a search box. Click a cell, click a spell - and it moves on to the next empty cell by itself, so filling a bar is click, click, click.",
            "Press Options on a bar's header and that same right column becomes the settings for that bar: name, shape, sizes, spacing, scale, opacity, border. Done takes you back to the spells.",
            "NEW: a look can be reused. Copy it from another bar in one click, or save it as a named preset and apply it to any bar later. Only sizes, spacing and colours travel - the spells and the grid always stay with their own bar.",
            "Nothing in the window is see-through any more. Translucent panels over a moving 3D world are unreadable; the layering is done with distinct opaque surfaces instead, which is also what makes the depth actually read.",
            "Self-built throughout, as ever: the compact slider, the cards, the navigation marks and the scrollbar are all drawn from colour textures, so no art path and no Blizzard template can break them.",
            "Fixed: the command list offered commands that no longer exist, and the minimap tooltip advertised a panel that is parked until 12.1.",
            "Still nothing rendered on screen from bars - the operation comes first, on purpose.",
        },
    },
    {
        version = "4.0.0",
        date = "2026-08-06",
        lines = {
            "Different approach. Everything before this tried to track auras itself, which cannot work on patch 12.0: aura data is secret, and the sanctioned replacement (Blizzard_AuraContainer) does not exist until 12.1 - measured on this client, creating one fails outright.",
            "Blizzard's Cooldown Manager already does all of it. It knows the spells, binds the auras and has the timing. Every addon that does cooldowns on this patch works the same way: it takes Blizzard's item frames and restyles them. ZwoelfStuff does that now too.",
            "NEW: bars. A bar is a grid of cells; each cell holds one spell. Set rows and columns and the grid in the options changes with them - that grid IS the bar, same rows, same columns, same order.",
            "Click an empty cell to choose a spell (the list comes from your own Cooldown Manager), drag one cell onto another to swap, right click to clear. Changing rows or columns re-flows what is there instead of scrambling or dropping it.",
            "The whole aura-tracking stack is parked until 12.1 - Engine, Groups, Catalog, CoTanks, Probe. The code is correct, it simply cannot run on a 12.0 client. The reason is written into the TOC next to them.",
            "The proc-glow display for Boiling Point stays: that buff is not in the Cooldown Manager data set, so it remains the only way to see it.",
            "On screen nothing is rendered from bars yet - the editor comes first, on purpose.",
        },
    },
    {
        version = "3.4.0",
        date = "2026-08-05",
        lines = {
            "THE BIG ONE: the aura engine reported itself unavailable on every client, so every engine-backed feature was dead - the display's aura slot, the co-tank aura strips, and every tracking group. Only the proc-glow route ever worked.",
            "Cause: the availability check tried to LoadAddOn('Blizzard_AuraContainer') first and gave up when that failed. There is no such addon. The AuraContainer frame type is built into the client - every reference implementation just calls CreateFrame. The gate could never open.",
            "The check now builds a container and looks at it, which is the only honest test, and reports WHY when it says no instead of a bare 'not available'.",
            "NEW: /zs group status - per spell, one of: slot refused (a bug here, with the error), registered but never seen (the ID is wrong or the aura was never up), or bound. Turns 'only one icon shows' into an answer.",
            "Slots that the engine refuses now say so in chat instead of vanishing into a pcall, and they keep their place in the order rather than silently closing the gap.",
        },
    },
    {
        version = "3.3.0",
        date = "2026-08-05",
        lines = {
            "NEW: /zs probe <spellID> - does that ID actually bind? A hidden slot is bound to the ID and the engine shows it exactly while that aura is on you, so the answer comes from your own client instead of from a database or from memory.",
            "It reports every bind and unbind with a timestamp, which is what tells a CAST spell apart from the aura it applies - the trap that cost this project two rounds on Boiling Point and another on Death and Decay.",
            "Nothing is read from the aura or even from the button: the show and hide handlers are registered inside the initializer, the one window where touching an engine button is legal, and the engine does the telling.",
            "Also on the Diagnostics page: type an ID, press Enter, watch for 20 seconds.",
        },
    },
    {
        version = "3.2.0",
        date = "2026-08-05",
        lines = {
            "Fixed: nothing could be dragged into place. The aura containers lay over their own anchor frames and swallowed every click - engine containers come mouse-enabled, and only the buttons had been told otherwise. Unlocking looked like it did nothing at all.",
            "Fixed: an unlocked group with no active auras was an invisible rectangle. Unlocked groups now show a tinted drag surface and stay visible even when switched off, so they can be placed before they ever light up.",
            "The spell list is now a row of icons. Click + to add, drag an icon to move it, right click to remove it. What you see is the order the group renders in - no more arrow buttons on a list of text rows.",
            "The group picker now creates and deletes groups itself: pick a group, or use '+ New icon group' / '+ New bar group' at the bottom of the same menu, with a delete on every entry.",
            "The spell browser opens with the cursor already in the search box - type the name, click the hit.",
        },
    },
    {
        version = "3.1.0",
        date = "2026-08-05",
        lines = {
            "The settings window was rebuilt. It was a flat list of steppers and checkboxes; it is now a proper panel - a sidebar of modules, a titled content area, settings as two-column cards, and a footer that stays put.",
            "New controls, all self-built and all matching: on/off switches instead of checkboxes, real sliders with a numeric readout, dropdown menus instead of button rows, and colour swatches that open the game's colour picker.",
            "Blizzard's slider, dropdown and checkbox templates have been renamed repeatedly across expansions and cannot be styled to match a custom panel, so none of them are used. Nothing here can break on a template rename.",
            "Pages are built on first view instead of at login, so the panel costs only what you actually open.",
            "New Diagnostics page: the check, dump, scan and catalogue commands as buttons, plus whether the aura engine is available on this client.",
            "New General page: the minimap button toggles and a two-step reset-everything.",
            "Rows that do not apply to your current settings are dropped from the layout rather than left visible, so the page closes up instead of showing gaps.",
        },
    },
    {
        version = "3.0.1",
        date = "2026-08-05",
        lines = {
            "Fixed: tracking groups threw at login. ns.CreateBorder returns a table of four textures, not a frame, so it never had Hide/Show/SetShown - and the group anchor called Hide() on its outline.",
            "Fixed: that one error disabled every feature after it. The login handler ran the features in one straight line, so a broken group meant no co-tank panel and no minimap button either. Each feature now starts on its own and a failure is reported by name.",
            "In fixed mode the slot container is sized to its group anchor instead of staying 1x1, so nothing can clip the buttons.",
            "The spell browser now repopulates itself after a respec or spec switch.",
        },
    },
    {
        version = "3.0.0",
        date = "2026-08-05",
        lines = {
            "NEW: tracking groups. As many as you like, icons or bars, each with its own spells, position, size and colours.",
            "Arrange them any way: grows left or right, rows up or down, fill by rows or by columns, wrap after any number for a grid. All of it applies live, in combat included.",
            "Two ordering modes. 'My order' gives every spell one fixed place that never moves, so muscle memory holds and bars can show spell names. 'Auto' lets the game pick and sort, which stays compact but moves things around.",
            "NEW: spell browser. Your talents, your whole spellbook including the specs you are NOT playing, and Blizzard's Cooldown Manager set - all read out of the live client, so it follows every respec and every patch by itself. Nothing is hardcoded. Manual spell IDs still work.",
            "NEW: bars can now actually drain. button:SetDurationBar hands a StatusBar to the game engine, which drains it from the aura's own duration - so a bar works even for auras no addon may read.",
            "Fixed, and this is the big one: the engine slot never bound anything. It used AddAuraFilter/AddAuraFrame, which do not exist. The real API is AddAuraGroup/AddAuraSlot with an initializeFrame callback - verified against four working 12.1 addons on this machine rather than guessed.",
            "Fixed: the container was given its unit BEFORE its content. Unit assignment re-evaluates event registrations, and those are gated on the container already having groups, so UNIT_AURA stayed unregistered and the container silently never updated.",
        },
    },
    {
        version = "2.1.0",
        date = "2026-08-05",
        lines = {
            "Minimap button: left click opens the settings, right click toggles the co-tank panel, drag moves it around the minimap edge. Self-built, no LibDBIcon.",
            "The addon now has an icon in the AddOn list and the addon compartment.",
            "Toggle both from the options, or with /zs minimap.",
        },
    },
    {
        version = "2.0.0",
        date = "2026-08-05",
        lines = {
            "NEW: co-tank panel. One row per tank in the group - health bar, name, health percent, every debuff on them and every buff they carry.",
            "Auras on other players are secret exactly like your own, so an addon cannot read a co-tank's boss debuff stacks at all. The panel hands the widgets to the game engine, which binds and times them itself.",
            "NEW: engine aura slot for the tracked buff. Blizzard_AuraContainer can bind a secret aura by spell ID and render it - real icon, real duration, real stacks. This replaces the proc-glow proxy where it works.",
            "The proc glow stays as the fallback and still drives the proc flash. Switch with /zs source engine or /zs source glow.",
            "Fixed: the options window clipped its last section - the proc glow row was added without raising the window height.",
            "Fixed: reserved aura rows left a large empty gap; three rows instead of five.",
            "Fixed: the inactive greyed-out state dimmed the whole frame, which would have dimmed the engine's aura button too. Only the placeholder dims now.",
        },
    },
    {
        version = "1.4.0",
        date = "2026-08-05",
        lines = {
            "Measured in game: every single buff on the player came back secret (0 readable, 18 secret). No addon can identify an aura this way - not Boiling Point, not any other.",
            "The cooldown viewers do hand out plain data, but only for buffs the Cooldown Manager tracks, and Boiling Point is not one of them.",
            "So the buff itself cannot be read. The proc can: Boiling Point empowers Blood Boil, and C_SpellActivationOverlay.IsSpellOverlayed(50842) is a plain boolean that never touches aura data.",
            "Route 5 added, driven off that proc glow. Timing comes from our own clock and our own 15s constant, so the swipe and countdown work normally.",
            "This is the same combat-safe technique EllesmereUIAuraBuffReminders uses for beacons it cannot read either.",
            "Added /zs glowlog to find the glowing spell ID, /zs glow <id or name> to set it, /zs glowduration to tune it.",
            "The dump now reports which APIs actually exist, combat state, whether the spell is in the Cooldown Manager data set at all, and the override-spell state - so 'API missing' can never again look like 'aura not found'.",
        },
    },
    {
        version = "1.3.0",
        date = "2026-08-05",
        lines = {
            "The cooldown viewer route only searched the two buff viewers; it now searches all four, including Essential and Utility.",
            "Added a fourth route: icon match. If a secret aura keeps a readable icon, it can be identified by comparing it against our own spell's icon.",
            "Added /zs dump - dumps every cooldown viewer entry and every player buff, marking icon matches. Run it WHILE the buff is up; it is the command that shows what actually exists.",
            "/zs check now reports all four routes.",
        },
    },
    {
        version = "1.2.0",
        date = "2026-08-05",
        lines = {
            "Fixed: Boiling Point was never found. It is a secret rotational proc, and those are invisible to BOTH aura queries - by ID and by name alike.",
            "Added a third lookup route: Blizzard's own cooldown viewer buff frames. They still bind such procs, and expose a plain auraInstanceID that yields duration and stacks.",
            "The irony: the Cooldown Manager will not let you add this buff, but it knows exactly when it is up.",
            "Display now only re-renders when the shown aura actually changes, so the polling never restarts the cooldown swipe.",
            "/zs check now reports all three routes separately, and says whether timing is available or only presence.",
            "Added /zs scan - lists the buffs an addon is allowed to read and counts the secret ones.",
        },
    },
    {
        version = "1.1.0",
        date = "2026-08-05",
        lines = {
            "Fixed: the addon threw on every aura change. Patch 12.0 made aura fields 'secret values', and a secret may not be used as a table key - which is exactly how 1.0.0 matched spell IDs.",
            "Aura lookup reversed: the spell ID now goes INTO the query via GetPlayerAuraBySpellID, so nothing secret is ever read.",
            "Added a fallback lookup by spell name, for auras whose applied ID differs from the tooltip or talent ID.",
            "Cooldown swipe now armed from a DurationObject, the only carrier a cooldown frame accepts since 12.0.1.",
            "Remaining time and stack count are now rendered by the game engine, since an addon can no longer compute them.",
            "Removed the 'red timer in the last 3s' option - it required comparing a secret value.",
            "Added /zs check and /zs status, plus a Diagnose button, to tell a wrong spell ID apart from a broken display.",
        },
    },
    {
        version = "1.0.0",
        date = "2026-08-05",
        lines = {
            "Isolated aura display - shows a single buff the Cooldown Manager cannot track.",
            "Ships tracking Boiling Point (spell 1265968), the Blood Death Knight Blood Boil empowerment.",
            "Two display modes: icon with cooldown swipe, or icon plus shrinking bar.",
            "Optional 'always show' mode that greys the display out while the aura is down.",
            "Self-built proc glow, optional proc sound, optional warning colour in the last seconds.",
            "Movable and lockable display with a 15 second test preview for positioning.",
            "Additional spell IDs can be tracked; the list doubles as a priority order.",
            "Full slash command set under /zs.",
        },
    },
}
