---------------------------------------------------------------------------
-- Languages - every translation this addon ships.
--
-- ONE FILE, and it is a deliberate choice against the usual one-file-per-
-- language layout. Which language to use is read from the PROFILE, and the
-- profile is not open when these tables load - so a file that loads only when
-- it is the client's language could never honour somebody who chose a
-- different one, which is exactly the setting the owner asked for. Every
-- table is therefore resident, and one file is the honest way to say so.
--
-- WHAT THAT COSTS: measured with memcheck.lua, not guessed. See the handoff.
-- It is a table of strings; the whole file weighs less than one row of the
-- spell palette, and switching language then needs no second load.
--
-- enUS IS THE MASTER. Its keys are the list of strings this addon localises
-- at all. Every other table is held to it by the self test:
--   * a key that is not in enUS is a translation of something never asked for
--   * a key missing from a language shows as its English self, which is the
--     whole point of the key being the English sentence
--
-- SO AN UNFINISHED LANGUAGE IS NOT A BROKEN ONE. `/zs loca` prints how far
-- each has got, and `/zs loca deDE` prints exactly which lines are left.
--
-- HOW TO ADD A LINE: put the English sentence in the enUS table, wrap the
-- place it is drawn in L["..."], and the other ten tables are now one line
-- short - which the coverage number says out loud rather than hiding.
--
-- THE STATE OF THE NINE, honestly: German is complete. French, Spanish (both),
-- Italian, Portuguese and Russian carry the whole interface vocabulary and
-- the sentences. Korean and both Chinese carry the vocabulary - the short
-- labels that fill the window - and leave the longer sentences in English,
-- because a wrong sentence in a language nobody here reads cannot be spotted
-- and a missing one falls back to something correct.
---------------------------------------------------------------------------
local _, ns = ...

local Register = ns.Locale.Register

---------------------------------------------------------------------------
-- enUS - the master list
---------------------------------------------------------------------------
Register("enUS", {
    -- The rail
    ["Edit mode"] = true,
    ["Bars"] = true,
    ["M+ and raid stuff"] = true,
    ["System"] = true,
    ["Info"] = true,

    -- Page names. Also the module names, which is not a coincidence - a
    -- feature and its page are one thing with one name.
    ["Cooldowns"] = true,
    ["Tank Unitframes"] = true,
    ["Reminders"] = true,
    ["External CD request"] = true,
    ["External CD answer"] = true,
    ["Death-log"] = true,
    ["Raid Bar"] = true,
    ["Invites"] = true,
    ["Settings"] = true,
    ["Profiles"] = true,
    ["Diagnostics"] = true,
    ["About"] = true,
    ["Changelog"] = true,

    -- Words that appear on more than one page
    ["Close"] = true,
    ["Cancel"] = true,
    ["Done"] = true,
    ["Show"] = true,
    ["Hide"] = true,
    ["Colour"] = true,
    ["Texture"] = true,
    ["Thickness"] = true,
    ["Scale"] = true,
    ["Opacity"] = true,
    ["Spacing"] = true,
    ["Rows"] = true,
    ["Columns"] = true,
    ["Runs"] = true,
    ["Across"] = true,
    ["Down"] = true,
    ["Icon size"] = true,
    ["Look"] = true,
    ["Border"] = true,
    ["Backdrop"] = true,
    ["Set keys"] = true,
    ["Test mode"] = true,
    ["Test mode: on"] = true,
    ["Only in a group"] = true,
    ["Only in combat"] = true,
    ["Only in an instance"] = true,
    ["Nothing yet"] = true,
    ["Switch it on"] = true,
    ["Language"] = true,
    ["Same as the game"] = true,
    ["Missing lines are shown in English."] = true,
    ["%s is switched off"] = true,
    ["Right-click clears every marker."] = true,
    ["Right-click takes this one away."] = true,
    ["Right-click cancels it."] = true,

    -- Welcome
    ["Not now"] = true,
    ["Open settings"] = true,
    ["Show the welcome screen"] = true,
    ["NEW"] = true,
    ["BETA"] = true,
    ["HIDDEN"] = true,
    ["Not on screen"] = true,

    -- Settings
    ["Modules"] = true,
    ["Every bar"] = true,
    ["This window"] = true,
    ["Ways in"] = true,
    ["Minimap button"] = true,
    ["Lock its position"] = true,
    ["Game menu entry"] = true,
    ["Bar text"] = true,
    ["Panel font"] = true,
    ["Take the display over"] = true,
    ["Standard look"] = true,
    ["Everything this addon draws OUT ON THE SCREEN - the names, the counts "
        .. "and the timers on your bars, icons and panels. The standard is "
        .. "Expressway: narrow, so more name fits in the same bar, and "
        .. "outlined, because all of it is read over a moving scene. If your "
        .. "client has no Expressway the closest face it does have is used."]
        = true,
    ["Puts every background, every border and every typeface back to the "
        .. "standard: #1a1a1a behind and around everything, opaque, and "
        .. "Expressway outlined on top. It touches only those - your bars, "
        .. "your spells, your positions and your sizes stay exactly where "
        .. "they are."] = true,
    ["%d settings put back to the standard look."] = true,
    ["Everything was already on the standard look."] = true,

    -- Sounds. THE FOUR EVENT NAMES ARE LOOKED UP THROUGH A VARIABLE -
    -- L[event.text] - so the scanner that checks every literal L["..."] is
    -- in this list CANNOT see them. They are here by hand, and anything
    -- added to ns.Sounds.EVENTS has to be added here by hand too.
    ["Sounds"] = true,
    ["When you ask for a cooldown"] = true,
    ["When somebody asks you"] = true,
    ["When a cooldown comes back"] = true,
    ["When a reminder appears"] = true,
    ["The list is every sound your other addons have registered - pick one "
        .. "and you will hear it. |cffffd100None|r is a real answer and "
        .. "silences that moment completely."] = true,
    ["|cffffd100Your addons have not registered any sounds yet.|r They come "
        .. "from whatever else you have installed - BigWigs, Northern Sky "
        .. "and WeakAuras all bring their own. |cffffd100/zs sounds|r lists "
        .. "what is there."] = true,
    ["Where sounds come from"] = true,
    ["%d sounds"] = true,
    ["Switch a pack off and its sounds leave the four lists above. Nothing "
        .. "here changes what you have already chosen - a sound you picked "
        .. "goes on playing even if its pack is switched off."] = true,
    ["A sound belongs to the SPELL, not to the place it sits in - so a "
        .. "cooldown you gave a sound of its own keeps it on the reminder "
        .. "and on the request panel alike."] = true,

    ---------------------------------------------------------------------
    -- Raid Bar
    ---------------------------------------------------------------------
    ["Markers"] = true,
    ["World markers"] = true,
    ["Clear markers"] = true,
    ["Clear world markers"] = true,
    ["Ready check"] = true,
    ["Pull timer"] = true,
    ["Cancel the pull"] = true,
    ["Raid check"] = true,
    ["Countdown"] = true,
    ["Pull"] = true,
    ["Ready"] = true,
    ["Clear"] = true,
    ["Ping"] = true,
    ["Attack"] = true,
    ["Assist"] = true,
    ["On my way"] = true,
    ["Warning"] = true,
    ["Your raid bar"] = true,
    ["Every button"] = true,
    ["Click one to put it on your bar."] = true,
    ["The bar"] = true,
    ["Seconds"] = true,
    ["Right-click seconds"] = true,
    ["Only for the leader"] = true,
    ["Not while in combat"] = true,
    ["You need lead or assist for that."] = true,
    ["You are not in a group."] = true,
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] = true,

    ---------------------------------------------------------------------
    -- Raid check window
    ---------------------------------------------------------------------
    ["Name"] = true,
    ["Item level"] = true,
    ["Durability"] = true,
    ["Food"] = true,
    ["Flask"] = true,
    ["Rune"] = true,
    ["Stamina"] = true,
    ["Intellect"] = true,
    ["Attack power"] = true,
    ["Versatility"] = true,
    ["Mastery"] = true,
    ["Movement"] = true,
    ["Ask the group"] = true,
    ["No answer"] = true,
    ["Waiting for answers"] = true,
    ["Nobody has answered yet."] = true,
    ["Only players running this addon can answer."] = true,
    ["%d of %d answered"] = true,

    ---------------------------------------------------------------------
    -- Invites
    ---------------------------------------------------------------------
    ["Invite"] = true,
    ["Keywords"] = true,
    ["Invite on a whisper"] = true,
    ["Also on say and yell"] = true,
    ["Guild members only"] = true,
    ["Friends only"] = true,
    ["Make it a raid at five"] = true,
    ["Accept invites from friends"] = true,
    ["Promote"] = true,
    ["Disband"] = true,
    ["Invite everyone back"] = true,
    ["Invite the guild"] = true,
    ["Guild rank"] = true,
    ["Any rank"] = true,
    ["Difficulty"] = true,
    ["Normal"] = true,
    ["Heroic"] = true,
    ["Mythic"] = true,
    ["Nobody to invite back."] = true,
    ["Invited %s."] = true,
    ["The group is empty."] = true,
    ["One word per line."] = true,

    ---------------------------------------------------------------------
    -- Sentences. Longer, and the ones a half-finished language leaves in
    -- English rather than getting wrong.
    ---------------------------------------------------------------------
    ["%d features in one addon. Switch off what you do not want."] = true,
    ["Off, the panel never appears."] = true,
    ["Pick a language, then reload."] = true,
    ["The window is drawn when it opens, so a new language reaches it after a |cffffd100/reload|r."] = true,
    ["Rows times columns is how many places there are."] = true,
    ["The gap between two icons."] = true,
    ["How big each button is on your screen."] = true,
    ["On your own there is nobody to ask, so it stays away."] = true,

    -- The page notes. Long sentences, and until 4.81.0 they were the
    -- last English left on three pages whose labels had been translated
    -- for months - which reads as an addon that gave up half way rather
    -- than one that is honestly unfinished.
    ["Out in the world there is nothing to mark. Off, the bar is there whenever you are in a group."] = 
        true,
    ["The countdown is the game's own, so boss mods pick it up and everybody sees the numbers. Right-click the Pull button to cancel it. Not available in combat."] =
        true,
    ["Every icon on your bars, and how they look."] = true,
    ["Every piece of text on every bar, unless a bar has its own font."] = 
        true,
    ["The size of this window on your screen, not of anything on the bars. 100% is the size it was designed at; on a laptop 80% keeps all three columns in view. Takes effect as you change it."] = 
        true,
    ["Lets the scene behind the window through. It fades the whole window at once, on purpose: fading each layer separately makes the values multiply where they overlap and no surface keeps its colour. Judge it in a bright zone, not a dark one."] = 
        true,
    ["The window you are looking at - its labels, values and headings."] = 
        true,
    ["Left click opens this window, right click unlocks the panels for moving, and drag moves the button around the minimap edge."] =
        true,
    ["The button stays where you put it on the minimap edge, and dragging it does nothing until you unlock it again."] = 
        true,
    ["An entry in the game's own addon list."] = true,
    ["Everything on this page is |cffffd100off until you switch it on|r. Nothing here invites, promotes or accepts anything until the switch above it says so."] = 
        true,
    ["Somebody whispers one of the words above"] = true,
    ["For shouting at a summoning stone"] = true,
    ["Off, the whole message has to be the word"] = true,
    ["A Battle.net whisper names an account rather than a character, which cannot be invited - that one is answered with a line telling them to whisper the character instead."] = true,
    ["Anybody else is ignored, and you are told"] = true,
    ["Guild members count as friends here"] = true,
    ["Their invitation is accepted for you"] = true,
    ["The sixth invitation needs a raid"] = true,
    ["A line in your chat for every invitation"] = true,
    ["The names below become assistants"] = true,
    ["One name a line. They are made assistants when they join, and only while you are the leader of a raid."] = true,
    ["Everybody at that rank and above it"] = true,

    -- The Cooldowns page, and the conflict check on the welcome window
    ["Who is managing your cooldowns"] = true,
    ["Nothing else on this account is managing them."] = true,
    ["Also managing cooldowns on this account: %s."] = true,
    ["%d other addons"] = true,
    ["Blizzard's Cooldown Manager"] = true,
    ["What it holds"] = true,
    ["Only one addon can hold these frames. Leave Cooldowns off to keep the other addon's display, or switch that addon off and this one on."] =
        true,
    ["Switch off %s"] = true,
    ["Do it and reload?"] = true,
    ["Switches that addon off, switches Cooldowns on here, and reloads. Nothing is deleted - it is the same tick as in the game's own addon list, and putting it back there puts everything back with it."] =
        true,
    ["Careful: %s would stop loading as well, because it needs that addon."] = true,
    ["Read from what each addon says about itself in its own description, so an addon that manages cooldowns without ever saying so is not found. Addons switched off for this character are not counted."] =
        true,
    ["The data comes from Blizzard's Cooldown Manager. The reminders, the death log and the spell pickers read it whether this module is on or off."] =
        true,
    ["%s is already managing your cooldowns. Two addons cannot hold the same cooldown frames - one of them loses, and which one depends on the order they loaded. Cooldowns is switched off below; turn it on to use ours instead, and switch theirs off in your addon list."] =
        true,

    -- The cooldown bars: the list, the arrangement and the picker
    ["Your bars"] = true,
    ["This bar"] = true,
    ["No bars yet"] = true,
    ["Bar"] = true,
    ["this bar"] = true,
    ["New bar"] = true,
    ["Duplicate this one"] = true,
    ["Delete %s"] = true,
    ["Really delete it?"] = true,
    ["%d bars were following it and now sit where they are."] = true,
    ["No bars yet. Make one and the spells you pick land on it - everything Blizzard's Cooldown Manager already knows about is in the list on the right."] =
        true,
    ["Arrangement"] = true,
    ["Cells are"] = true,
    ["Icons"] = true,
    ["Pattern"] = true,
    ["Fills"] = true,
    ["Grows across"] = true,
    ["Grows down"] = true,
    ["Shift every other line"] = true,
    ["As a share of one cell, so it stays right when you change the icon size."] =
        true,
    ["Across times down is how many places the bar has. A spell already sitting past the last place keeps its cell - narrowing a bar never throws a pick away."] =
        true,
    ["Size and spacing"] = true,
    ["Bar width"] = true,
    ["Bar height"] = true,
    ["Gap across"] = true,
    ["Gap down"] = true,
    ["Spell icon"] = true,
    ["At the left"] = true,
    ["At the right"] = true,
    ["Not shown"] = true,
    ["Hide the ones you did not place"] = true,
    ["Cooldowns you have not put on a bar are not shown."] =
        true,
    ["Shown in the preview above"] = true,
    -- The bar editor: the look, the text, the effects and the fill
    ["Nothing to set up yet. Press + at the top of the list to make your first bar."] =
        true,
    ["Duplicate"] = true,
    ["Really?"] = true,
    ["Click to change it"] = true,
    ["Drag it to sort the bar"] = true,
    ["Hold Shift while dropping to swap the two"] = true,
    ["Right click to clear"] = true,
    ["Empty"] = true,
    ["Place %d"] = true,
    ["Click it, then pick a spell on the right"] = true,
    ["Every bar you have, drawn the way it really looks."] = true,
    ["Icon bar"] = true,
    ["Tracking bar"] = true,
    ["The sweep and the numbers need Blizzard's own frame, so they are not here - everything else is the bar as it is set right now."] =
        true,
    ["Places"] = true,
    ["Stacks and charges"] = true,
    ["Nought works the size out from the place it sits in, which is what keeps a 24 pixel bar and a 64 pixel icon looking like one design. Below %d pixels a number is there and cannot be read, so the rail goes straight from nought to %d."] =
        true,
    ["Show this place"] = true,
    ["Ready means you can press it. Working means the buff it put on you is still running - Anti-Magic Shell, Blood Shield. Recharging is neither."] =
        true,
    ["When"] = true,
    ["When to show it"] = true,
    ["Combat"] = true,
    ["Group"] = true,
    ["Target"] = true,
    ["Rested"] = true,
    ["Otherwise"] = true,
    ["gone"] = true,
    ["Rows and columns"] = true,
    ["Columns and Rows lay the places out, and either one sets how many places that comes to. Places is the total underneath and may be fewer than the rectangle holds - seven places in two rows of four leaves the last one empty."] =
        true,
    ["%d spells sit past the last place and are not drawn. Nothing was thrown away - make room and they come back where they were."] =
        true,
    ["Delete"] = true,
    ["No bars yet. Make one and the spells you pick land on it."] = true,
    ["Text"] = true,
    ["Effects"] = true,
    ["Fill"] = true,
    ["Blizzard"] = true,
    ["Spell name"] = true,
    ["A band starts at one stack. To switch one off, take it away - a band of nought would be crossed by an aura that is merely there."] =
        true,
    ["A band takes the fill's colour over once the stack count reaches its number. The highest one reached is the one you see."] =
        true,
    ["A bright line on the moving edge"] = true,
    ["A plate under the art. Spell art is opaque and fills its place, so you only see this where the art does not cover it - along a border, and behind a bar-shaped place."] =
        true,
    ["A pulse the moment the cooldown ends"] = true,
    ["A spell that has been ready this long IN COMBAT starts pulsing. For the defensive you keep forgetting."] =
        true,
    ["These reach the ICON. The fill and the plate each have their own opacity setting. 'While inactive' only has something to dim on a tracked buff bar."] =
        true,
    ["Add a band"] = true,
    ["An icon place is square and uses the first of these; a bar place is the other two. Which one a bar's places are is up under Arrangement."] =
        true,
    ["Behind the icon"] = true,
    ["Belongs to the staggered pattern and is ignored by the others. As a share of one cell, so it stays right when you change the icon size."] =
        true,
    ["The global cooldown never sets any of this off."] =
        true,
    ["Blizzard's icon art has a border baked into the file. Cropping cuts it off; at 0 you see the whole thing, frame and all. Above a fifth it starts eating the picture instead."] =
        true,
    ["Bottom"] = true,
    ["Bottom left"] = true,
    ["Bottom right"] = true,
    ["Centre"] = true,
    ["Charge marks"] = true,
    ["Charge marks and the spark"] = true,
    ["Charge marks only appear on a spell that HAS more than one charge, so the switch can stay on for a whole bar without marking everything on it."] =
        true,
    ["Changing"] = true,
    ["Charges"] = true,
    ["Click a place in the picture to change just that one, or the card itself to change the whole bar. What a place carries of its own wins over the bar, which is why a colour set on the bar can leave one place looking untouched."] =
        true,
    ["Close up"] = true,
    ["Close up in the row"] = true,
    ["Crop"] = true,
    ["Follow the bar again"] = true,
    ["Edge colour"] = true,
    ["Edge style"] = true,
    ["Edge thickness"] = true,
    ["Everything that pulses"] = true,
    ["Flash"] = true,
    ["Flash colour"] = true,
    ["Flat colour"] = true,
    ["Font"] = true,
    ["From"] = true,
    ["Glow in the window"] = true,
    ["Glow while it is up"] = true,
    ["Gradient"] = true,
    ["Grey out while it is down"] = true,
    ["Grey out while it runs"] = true,
    ["Greying and hiding"] = true,
    ["How grey"] = true,
    ["How many"] = true,
    ["How many squares"] = true,
    ["Its colour"] = true,
    ["Keep an edge"] = true,
    ["Keeps the edge dark while you are short of the resource. Range and target are ignored - a defensive with nothing targeted is not the same as one you cannot pay for."] =
        true,
    ["Leading edge"] = true,
    ["Leave it empty"] = true,
    ["Leaving it empty keeps everything where you learned it. Closing up in the ROW keeps a grid's shape, so the second row stays the second row."] =
        true,
    ["Left"] = true,
    ["Mark colour"] = true,
    ["Not drawn in this version. What you set here is kept."] =
        true,
    ["None is a crisp one-pixel line drawn from colour textures, and it stays sharper than any edge file at small sizes. The rest come from whatever your other addons registered."] =
        true,
    ["Nothing"] = true,
    ["Nudge across"] = true,
    ["Nudge up"] = true,
    ["One line per charge boundary"] = true,
    ["One speed for the flash, the nag and the squares"] = true,
    ["Only closes up what the row above takes off screen"] = true,
    ["Only the one-pixel line - an edge file takes one colour"] = true,
    ["Only when you can pay for it"] = true,
    ["Outline"] = true,
    ["Over time"] = true,
    ["Position"] = true,
    ["Ready is always on screen. Press a defensive and it stays while its own buff is still running - Anti-Magic Shell, Blood Shield - and goes for the rest of the cooldown. Anything the client will not answer for stays where it is."] =
        true,
    ["Remind me after"] = true,
    ["Reminder colour"] = true,
    ["Right"] = true,
    ["Running squares"] = true,
    ["Background"] = true,
    ["Background colour"] = true,
    ["Background opacity"] = true,
    ["Behind the fill, where the bar is not full yet"] = true,
    ["Same as behind the icon"] = true,
    ["Same as everywhere"] = true,
    ["Second colour"] = true,
    ["Size"] = true,
    ["Soft edge"] = true,
    ["Some places on this bar carry a look of their own and keep it. What you change here reaches every other place."] =
        true,
    ["Spark"] = true,
    ["The whole bar"] = true,
    ["This place also carries settings from an older version, filed under its position rather than its spell. Those are left exactly as they are."] =
        true,
    ["Speed"] = true,
    ["Stack colours"] = true,
    ["Stack count"] = true,
    ["Take off screen"] = true,
    ["Take this band away"] = true,
    ["That is as many bands as one bar carries (%d). Take one away to add another."] =
        true,
    ["The bar's fill"] = true,
    ["The bright line the sweep drags behind it"] = true,
    ["The cooldown sweep"] = true,
    ["The edge while it is ready"] = true,
    ["The empty place"] = true,
    ["The icon"] = true,
    ["The nag"] = true,
    ["The refresh window"] = true,
    ["The tail of an aura where recasting wastes nothing. Lights only for auras with pandemic alerts switched on in the game's settings."] =
        true,
    ["These reach a place Blizzard draws as a tracked buff BAR. An icon has no fill of its own, whichever shape this bar's places are set to."] =
        true,
    ["Top"] = true,
    ["Top left"] = true,
    ["Top right"] = true,
    ["Whether the bar fills or empties while the cooldown runs. The clock belongs to Blizzard's own template and it re-drives the bar on every update, so this is the one setting here whose undo is its owner putting it back."] =
        true,
    ["While inactive"] = true,
    ["While recharging"] = true,
    ["While the buff is up"] = true,
    ["Window colour"] = true,
    ["auto"] = true,
    ["off"] = true,
    ["Every spell"] = true,
    ["Click one to put it on the bar."] = true,
    ["Click to fill place %d of %s"] = true,
    ["Click to add it to %s"] = true,
})

---------------------------------------------------------------------------
-- deDE
---------------------------------------------------------------------------
Register("deDE", {
    ["Edit mode"] = "Bearbeiten",
    ["Bars"] = "Leisten",
    ["M+ and raid stuff"] = "M+ und Schlachtzug",
    ["System"] = "System",
    ["Info"] = "Info",

    ["Cooldowns"] = "Abklingzeiten",
    ["Tank Unitframes"] = "Tank-Unitframes",
    ["Reminders"] = "Erinnerungen",
    ["External CD request"] = "Externen CD anfragen",
    ["External CD answer"] = "Externen CD geben",
    ["Death-log"] = "Todesprotokoll",
    ["Raid Bar"] = "Schlachtzugsleiste",
    ["Invites"] = "Einladungen",
    ["Settings"] = "Einstellungen",
    ["Profiles"] = "Profile",
    ["Diagnostics"] = "Diagnose",
    ["About"] = "Über",
    ["Changelog"] = "Änderungen",

    ["Close"] = "Schließen",
    ["Cancel"] = "Abbrechen",
    ["Done"] = "Fertig",
    ["Show"] = "Anzeigen",
    ["Hide"] = "Ausblenden",
    ["Colour"] = "Farbe",
    ["Texture"] = "Textur",
    ["Thickness"] = "Stärke",
    ["Scale"] = "Skalierung",
    ["Opacity"] = "Deckkraft",
    ["Spacing"] = "Abstand",
    ["Rows"] = "Zeilen",
    ["Columns"] = "Spalten",
    ["Runs"] = "Verlauf",
    ["Across"] = "Waagerecht",
    ["Down"] = "Senkrecht",
    ["Icon size"] = "Symbolgröße",
    ["Look"] = "Aussehen",
    ["Border"] = "Rahmen",
    ["Backdrop"] = "Hintergrund",
    ["Set keys"] = "Tasten belegen",
    ["Test mode"] = "Testmodus",
    ["Test mode: on"] = "Testmodus: an",
    ["Only in a group"] = "Nur in einer Gruppe",
    ["Only in combat"] = "Nur im Kampf",
    ["Only in an instance"] = "Nur in einer Instanz",
    ["Nothing yet"] = "Noch nichts",
    ["Switch it on"] = "Einschalten",
    ["Language"] = "Sprache",
    ["Same as the game"] = "Wie das Spiel",
    ["Missing lines are shown in English."] = "Fehlende Zeilen erscheinen auf Englisch.",
    ["%s is switched off"] = "%s ist ausgeschaltet",
    ["Right-click clears every marker."] = "Rechtsklick entfernt alle Zeichen.",
    ["Right-click takes this one away."] = "Rechtsklick nimmt diese wieder weg.",
    ["Right-click cancels it."] = "Rechtsklick bricht ab.",

    ["Not now"] = "Später",
    ["Open settings"] = "Einstellungen",
    ["Show the welcome screen"] = "Willkommensfenster zeigen",
    ["NEW"] = "NEU",
    ["BETA"] = "BETA",
    ["HIDDEN"] = "VERSTECKT",
    ["Not on screen"] = "Nicht auf dem Bildschirm",

    ["Modules"] = "Module",
    ["Every bar"] = "Alle Leisten",
    ["This window"] = "Dieses Fenster",
    ["Ways in"] = "Zugänge",
    ["Minimap button"] = "Minikarten-Knopf",
    ["Lock its position"] = "Position sperren",
    ["Game menu entry"] = "Eintrag im Spielmenü",
    ["Bar text"] = "Leistentext",
    ["Panel font"] = "Schrift der Fenster",
    ["Take the display over"] = "Anzeige übernehmen",
    ["Standard look"] = "Standard-Aussehen",
    ["Everything this addon draws OUT ON THE SCREEN - the names, the counts "
        .. "and the timers on your bars, icons and panels. The standard is "
        .. "Expressway: narrow, so more name fits in the same bar, and "
        .. "outlined, because all of it is read over a moving scene. If your "
        .. "client has no Expressway the closest face it does have is used."]
        = "Alles, was dieses Addon AUF DEM BILDSCHIRM zeichnet - die Namen, "
        .. "die Zahlen und die Restzeiten auf deinen Leisten, Symbolen und "
        .. "Panels. Standard ist Expressway: schmal, damit mehr Name in "
        .. "dieselbe Leiste passt, und mit Kontur, weil das alles über einer "
        .. "bewegten Szene gelesen wird. Hat dein Client kein Expressway, "
        .. "wird die nächstbeste vorhandene Schrift genommen.",
    ["Puts every background, every border and every typeface back to the "
        .. "standard: #1a1a1a behind and around everything, opaque, and "
        .. "Expressway outlined on top. It touches only those - your bars, "
        .. "your spells, your positions and your sizes stay exactly where "
        .. "they are."]
        = "Setzt jeden Hintergrund, jeden Rahmen und jede Schrift auf den "
        .. "Standard zurück: #1a1a1a hinter und um alles herum, deckend, "
        .. "und Expressway mit Kontur darauf. Mehr nicht - deine Leisten, "
        .. "deine Zauber, deine Positionen und deine Größen bleiben genau "
        .. "so, wie sie sind.",
    ["%d settings put back to the standard look."]
        = "%d Einstellungen auf das Standard-Aussehen zurückgesetzt.",
    ["Everything was already on the standard look."]
        = "Es war schon alles auf dem Standard-Aussehen.",

    ["Sounds"] = "Töne",
    ["When you ask for a cooldown"] = "Wenn du einen Cooldown anforderst",
    ["When somebody asks you"] = "Wenn dich jemand fragt",
    ["When a cooldown comes back"] = "Wenn ein Cooldown wieder da ist",
    ["When a reminder appears"] = "Wenn eine Erinnerung erscheint",
    ["The list is every sound your other addons have registered - pick one "
        .. "and you will hear it. |cffffd100None|r is a real answer and "
        .. "silences that moment completely."] =
        "Die Liste enthält jeden Ton, den deine anderen Addons angemeldet "
        .. "haben - wähle einen und du hörst ihn sofort. |cffffd100None|r "
        .. "ist eine echte Antwort und macht diesen Moment ganz stumm.",
    ["|cffffd100Your addons have not registered any sounds yet.|r They come "
        .. "from whatever else you have installed - BigWigs, Northern Sky "
        .. "and WeakAuras all bring their own. |cffffd100/zs sounds|r lists "
        .. "what is there."] =
        "|cffffd100Deine Addons haben noch keine Töne angemeldet.|r "
        .. "Sie kommen aus allem anderen, was du installiert hast - BigWigs, "
        .. "Northern Sky und WeakAuras bringen eigene mit. "
        .. "|cffffd100/zs sounds|r zeigt, was da ist.",
    ["Where sounds come from"] = "Woher die Töne kommen",
    ["%d sounds"] = "%d Töne",
    ["Switch a pack off and its sounds leave the four lists above. Nothing "
        .. "here changes what you have already chosen - a sound you picked "
        .. "goes on playing even if its pack is switched off."] =
        "Schalte ein Paket ab und seine Töne verschwinden aus den vier "
        .. "Listen oben. An deiner Auswahl ändert das nichts - ein bereits "
        .. "gewählter Ton spielt weiter, auch wenn sein Paket aus ist.",
    ["A sound belongs to the SPELL, not to the place it sits in - so a "
        .. "cooldown you gave a sound of its own keeps it on the reminder "
        .. "and on the request panel alike."] =
        "Ein Ton gehört zum ZAUBER, nicht zu seinem Platz - ein Cooldown "
        .. "mit eigenem Ton behält ihn also auf der Erinnerung wie "
        .. "im Anfrage-Fenster.",

    ["Markers"] = "Zeichen",
    ["World markers"] = "Weltmarkierungen",
    ["Clear markers"] = "Zeichen entfernen",
    ["Clear world markers"] = "Weltmarkierungen entfernen",
    ["Ready check"] = "Bereitschaftsprüfung",
    ["Pull timer"] = "Pull-Timer",
    ["Cancel the pull"] = "Pull abbrechen",
    ["Raid check"] = "Raid-Check",
    ["Countdown"] = "Countdown",
    ["Pull"] = "Pull",
    ["Ready"] = "Bereit",
    ["Clear"] = "Löschen",
    ["Ping"] = "Ping",
    ["Attack"] = "Angreifen",
    ["Assist"] = "Helfen",
    ["On my way"] = "Bin unterwegs",
    ["Warning"] = "Achtung",
    ["Your raid bar"] = "Deine Schlachtzugsleiste",
    ["Every button"] = "Alle Knöpfe",
    ["Click one to put it on your bar."] = "Klick einen an, um ihn auf die Leiste zu legen.",
    ["The bar"] = "Die Leiste",
    ["Seconds"] = "Sekunden",
    ["Right-click seconds"] = "Sekunden bei Rechtsklick",
    ["Only for the leader"] = "Nur für den Anführer",
    ["Not while in combat"] = "Nicht im Kampf",
    ["You need lead or assist for that."] = "Dafür brauchst du Anführer oder Assistent.",
    ["You are not in a group."] = "Du bist in keiner Gruppe.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "Die Leiste kann im Kampf nicht neu gebaut werden. Es passiert, sobald du ihn verlässt.",

    ["Name"] = "Name",
    ["Item level"] = "Gegenstandsstufe",
    ["Durability"] = "Haltbarkeit",
    ["Food"] = "Essen",
    ["Flask"] = "Fläschchen",
    ["Rune"] = "Rune",
    ["Stamina"] = "Ausdauer",
    ["Intellect"] = "Intelligenz",
    ["Attack power"] = "Angriffskraft",
    ["Versatility"] = "Vielseitigkeit",
    ["Mastery"] = "Meisterschaft",
    ["Movement"] = "Tempo",
    ["Ask the group"] = "Gruppe fragen",
    ["No answer"] = "Keine Antwort",
    ["Waiting for answers"] = "Warte auf Antworten",
    ["Nobody has answered yet."] = "Noch hat niemand geantwortet.",
    ["Only players running this addon can answer."] =
        "Antworten können nur Spieler, die dieses Addon benutzen.",
    ["%d of %d answered"] = "%d von %d haben geantwortet",

    ["Invite"] = "Einladen",
    ["Keywords"] = "Schlüsselwörter",
    ["Invite on a whisper"] = "Bei Flüstern einladen",
    ["Also on say and yell"] = "Auch bei Sagen und Rufen",
    ["Guild members only"] = "Nur Gildenmitglieder",
    ["Friends only"] = "Nur Freunde",
    ["Make it a raid at five"] = "Bei fünf in Schlachtzug umwandeln",
    ["Accept invites from friends"] = "Einladungen von Freunden annehmen",
    ["Promote"] = "Befördern",
    ["Disband"] = "Auflösen",
    ["Invite everyone back"] = "Alle zurückholen",
    ["Invite the guild"] = "Gilde einladen",
    ["Guild rank"] = "Gildenrang",
    ["Any rank"] = "Jeder Rang",
    ["Difficulty"] = "Schwierigkeit",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroisch",
    ["Mythic"] = "Mythisch",
    ["Nobody to invite back."] = "Niemanden zurückzuholen.",
    ["Invited %s."] = "%s eingeladen.",
    ["The group is empty."] = "Die Gruppe ist leer.",
    ["One word per line."] = "Ein Wort pro Zeile.",

    ["%d features in one addon. Switch off what you do not want."] =
        "%d Funktionen in einem Addon. Schalte ab, was du nicht willst.",
    ["Off, the panel never appears."] = "Aus erscheint das Fenster nie.",
    ["Pick a language, then reload."] = "Sprache wählen, dann neu laden.",
    ["The window is drawn when it opens, so a new language reaches it after a |cffffd100/reload|r."] =
        "Das Fenster wird beim Öffnen gezeichnet - eine neue Sprache kommt also erst nach einem |cffffd100/reload|r an.",
    ["Rows times columns is how many places there are."] =
        "Zeilen mal Spalten ergibt die Anzahl der Plätze.",
    ["The gap between two icons."] = "Der Abstand zwischen zwei Symbolen.",
    ["How big each button is on your screen."] =
        "Wie groß jeder Knopf auf deinem Bildschirm ist.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Allein gibt es niemanden zu fragen, also bleibt sie weg.",

    -- The page notes. Long sentences, and until 4.81.0 they were the
    -- last English left on three pages whose labels had been translated
    -- for months - which reads as an addon that gave up half way rather
    -- than one that is honestly unfinished.
    ["Out in the world there is nothing to mark. Off, the bar is there whenever you are in a group."] = 
        "Draußen in der Welt gibt es nichts zu markieren. Aus, ist die Leiste da, sobald du in einer Gruppe bist.",
    ["The countdown is the game's own, so boss mods pick it up and everybody sees the numbers. Right-click the Pull button to cancel it. Not available in combat."] =
        "Der Countdown ist der des Spiels - Boss-Mods greifen ihn auf, und jeder sieht die Zahlen. Rechtsklick auf den Pull-Knopf bricht ab. Im Kampf nicht verfügbar.",
    ["Every icon on your bars, and how they look."] = 
        "Jedes Symbol auf deinen Leisten und wie sie aussehen.",
    ["Every piece of text on every bar, unless a bar has its own font."] = 
        "Jeder Text auf jeder Leiste, außer eine Leiste hat ihre eigene Schrift.",
    ["The size of this window on your screen, not of anything on the bars. 100% is the size it was designed at; on a laptop 80% keeps all three columns in view. Takes effect as you change it."] = 
        "Die Größe dieses Fensters auf deinem Bildschirm, nicht die von etwas auf den Leisten. 100% ist die Größe, für die es gestaltet wurde; auf einem Laptop hält 80% alle drei Spalten im Blick. Wirkt sofort beim Ziehen.",
    ["Lets the scene behind the window through. It fades the whole window at once, on purpose: fading each layer separately makes the values multiply where they overlap and no surface keeps its colour. Judge it in a bright zone, not a dark one."] = 
        "Lässt die Szene hinter dem Fenster durch. Es blendet das ganze Fenster auf einmal ab, mit Absicht: blendet man jede Ebene einzeln, multiplizieren sich die Werte an den Überlappungen und keine Fläche behält ihre Farbe. Beurteile es in einer hellen Gegend, nicht in einer dunklen.",
    ["The window you are looking at - its labels, values and headings."] = 
        "Das Fenster, das du gerade ansiehst - seine Beschriftungen, Werte und Überschriften.",
    ["Left click opens this window, right click unlocks the panels for moving, and drag moves the button around the minimap edge."] =
        "Linksklick öffnet dieses Fenster, Rechtsklick gibt die Panels zum Verschieben frei, und Ziehen bewegt den Knopf am Rand der Minikarte.",
    ["The button stays where you put it on the minimap edge, and dragging it does nothing until you unlock it again."] = 
        "Der Knopf bleibt, wo du ihn am Rand der Minikarte abgelegt hast, und Ziehen tut nichts, bis du ihn wieder freigibst.",
    ["An entry in the game's own addon list."] = 
        "Ein Eintrag in der Addon-Liste des Spiels.",
    ["Everything on this page is |cffffd100off until you switch it on|r. Nothing here invites, promotes or accepts anything until the switch above it says so."] = 
        "Alles auf dieser Seite ist |cffffd100aus, bis du es einschaltest|r. Nichts hier lädt ein, befördert oder nimmt an, bevor der Schalter darüber es sagt.",
    ["Somebody whispers one of the words above"] =
        "Jemand flüstert eines der Wörter oben",
    ["For shouting at a summoning stone"] =
        "Fürs Rufen am Beschwörungsstein",
    ["Off, the whole message has to be the word"] =
        "Aus, muss die ganze Nachricht das Wort sein",
    ["A Battle.net whisper names an account rather than a character, which cannot be invited - that one is answered with a line telling them to whisper the character instead."] =
        "Ein Battle.net-Flüstern nennt ein Konto statt eines Charakters, und ein Konto kann man nicht einladen - darauf kommt eine Zeile zurück, die um ein Flüstern an den Charakter bittet.",
    ["Anybody else is ignored, and you are told"] =
        "Alle anderen werden ignoriert, und du erfährst es",
    ["Guild members count as friends here"] =
        "Gildenmitglieder zählen hier als Freunde",
    ["Their invitation is accepted for you"] =
        "Ihre Einladung wird für dich angenommen",
    ["The sixth invitation needs a raid"] =
        "Die sechste Einladung braucht einen Schlachtzug",
    ["A line in your chat for every invitation"] =
        "Eine Chatzeile für jede Einladung",
    ["The names below become assistants"] =
        "Die Namen unten werden Assistenten",
    ["One name a line. They are made assistants when they join, and only while you are the leader of a raid."] =
        "Ein Name pro Zeile. Sie werden beim Beitreten zu Assistenten ernannt, und nur solange du Anführer eines Schlachtzugs bist.",
    ["Everybody at that rank and above it"] =
        "Jeder in diesem Rang und darüber",

    -- Die Cooldowns-Seite und die Konfliktprüfung im Willkommensfenster
    ["Who is managing your cooldowns"] = "Wer deine Cooldowns verwaltet",
    ["Nothing else on this account is managing them."] =
        "Sonst verwaltet sie auf diesem Account niemand.",
    ["Also managing cooldowns on this account: %s."] =
        "Verwalten auf diesem Account ebenfalls Cooldowns: %s.",
    ["%d other addons"] = "%d andere Addons",
    ["Blizzard's Cooldown Manager"] = "Blizzards Cooldown-Manager",
    ["What it holds"] = "Was er hält",
    ["Only one addon can hold these frames. Leave Cooldowns off to keep the other addon's display, or switch that addon off and this one on."] =
        "Nur ein Addon kann diese Frames halten. Lass Cooldowns aus, um die Anzeige des anderen Addons zu behalten - oder schalte das andere ab und dieses an.",
    ["Switch off %s"] = "%s abschalten",
    ["Do it and reload?"] = "Wirklich, mit Neuladen?",
    ["Switches that addon off, switches Cooldowns on here, and reloads. Nothing is deleted - it is the same tick as in the game's own addon list, and putting it back there puts everything back with it."] =
        "Schaltet dieses Addon ab, schaltet Cooldowns hier an und lädt neu. Es wird nichts gelöscht - es ist dasselbe Häkchen wie in der Addon-Liste des Spiels, und wer es dort zurücksetzt, bekommt alles wieder.",
    ["Careful: %s would stop loading as well, because it needs that addon."] =
        "Achtung: %s würde ebenfalls nicht mehr laden, weil es dieses Addon braucht.",
    ["Read from what each addon says about itself in its own description, so an addon that manages cooldowns without ever saying so is not found. Addons switched off for this character are not counted."] =
        "Gelesen aus dem, was jedes Addon in seiner eigenen Beschreibung über sich sagt - ein Addon, das Cooldowns verwaltet, ohne das je zu erwähnen, wird also nicht gefunden. Für diesen Charakter abgeschaltete Addons zählen nicht mit.",
    ["The data comes from Blizzard's Cooldown Manager. The reminders, the death log and the spell pickers read it whether this module is on or off."] =
        "Die Daten kommen aus Blizzards Cooldown-Manager. Die Erinnerungen, das Todesprotokoll und die Zauberlisten lesen ihn, egal ob dieses Modul an oder aus ist.",
    ["%s is already managing your cooldowns. Two addons cannot hold the same cooldown frames - one of them loses, and which one depends on the order they loaded. Cooldowns is switched off below; turn it on to use ours instead, and switch theirs off in your addon list."] =
        "%s verwaltet deine Cooldowns bereits. Zwei Addons können dieselben Cooldown-Frames nicht gemeinsam halten - eines verliert, und welches, hängt an der Ladereihenfolge. Cooldowns ist unten ausgeschaltet; schalte es an, um stattdessen unseres zu nutzen, und deren Addon in deiner Addon-Liste ab.",

    -- Die Cooldown-Leisten: die Liste, die Anordnung und die Auswahl
    ["Your bars"] = "Deine Leisten",
    ["This bar"] = "Diese Leiste",
    ["No bars yet"] = "Noch keine Leisten",
    ["Bar"] = "Leiste",
    ["this bar"] = "diese Leiste",
    ["New bar"] = "Neue Leiste",
    ["Duplicate this one"] = "Diese verdoppeln",
    ["Delete %s"] = "%s löschen",
    ["Really delete it?"] = "Wirklich löschen?",
    ["%d bars were following it and now sit where they are."] =
        "%d Leisten sind ihr gefolgt und bleiben jetzt, wo sie sind.",
    ["No bars yet. Make one and the spells you pick land on it - everything Blizzard's Cooldown Manager already knows about is in the list on the right."] =
        "Noch keine Leisten. Leg eine an, dann landen die Zauber, die du wählst, darauf - alles, was Blizzards Cooldown-Manager kennt, steht rechts in der Liste.",
    ["Arrangement"] = "Anordnung",
    ["Cells are"] = "Zellen sind",
    ["Icons"] = "Symbole",
    ["Pattern"] = "Muster",
    ["Fills"] = "Füllt sich",
    ["Grows across"] = "Wächst waagerecht",
    ["Grows down"] = "Wächst senkrecht",
    ["Shift every other line"] = "Jede zweite Reihe versetzen",
    ["As a share of one cell, so it stays right when you change the icon size."] =
        "Als Anteil einer Zelle, damit es stimmt, wenn du die Symbolgröße änderst.",
    ["Across times down is how many places the bar has. A spell already sitting past the last place keeps its cell - narrowing a bar never throws a pick away."] =
        "Waagerecht mal senkrecht ist die Anzahl der Plätze. Ein Zauber, der hinter dem letzten Platz sitzt, behält seine Zelle - eine schmalere Leiste wirft nie eine Wahl weg.",
    ["Size and spacing"] = "Größe und Abstände",
    ["Bar width"] = "Leistenbreite",
    ["Bar height"] = "Leistenhöhe",
    ["Gap across"] = "Abstand waagerecht",
    ["Gap down"] = "Abstand senkrecht",
    ["Spell icon"] = "Zaubersymbol",
    ["At the left"] = "Links",
    ["At the right"] = "Rechts",
    ["Not shown"] = "Nicht gezeigt",
    ["Hide the ones you did not place"] =
        "Die verstecken, die du nicht platziert hast",
    ["Cooldowns you have not put on a bar are not shown."] =
        "Cooldowns, die du auf keine Leiste gelegt hast, werden nicht angezeigt.",
    ["Shown in the preview above"] = "Oben in der Vorschau",
    -- Der Leisten-Editor: Aussehen, Text, Effekte und Füllung
    ["Nothing to set up yet. Press + at the top of the list to make your first bar."] =
        "Noch nichts einzustellen. Druck oben in der Liste auf +, um deine erste Leiste anzulegen.",
    ["Duplicate"] = "Duplizieren",
    ["Really?"] = "Wirklich?",
    ["Click to change it"] = "Klicken zum Wechseln",
    ["Drag it to sort the bar"] = "Ziehen, um die Leiste zu sortieren",
    ["Hold Shift while dropping to swap the two"] =
        "Beim Loslassen Umschalt halten, um die beiden zu tauschen",
    ["Right click to clear"] = "Rechtsklick zum Leeren",
    ["Empty"] = "Leer",
    ["Place %d"] = "Platz %d",
    ["Click it, then pick a spell on the right"] =
        "Anklicken, dann rechts einen Zauber aussuchen",
    ["Every bar you have, drawn the way it really looks."] =
        "Jede Leiste, die du hast, so gezeichnet, wie sie wirklich aussieht.",
    ["Icon bar"] = "Symbolleiste",
    ["Tracking bar"] = "Verfolgungsleiste",
    ["The sweep and the numbers need Blizzard's own frame, so they are not here - everything else is the bar as it is set right now."] =
        "Der Ablauf und die Zahlen brauchen Blizzards eigenen Rahmen, deshalb stehen sie nicht hier - alles andere ist die Leiste, wie sie gerade eingestellt ist.",
    ["Places"] = "Plätze",
    ["Stacks and charges"] = "Stapel und Aufladungen",
    ["Nought works the size out from the place it sits in, which is what keeps a 24 pixel bar and a 64 pixel icon looking like one design. Below %d pixels a number is there and cannot be read, so the rail goes straight from nought to %d."] =
        "Null rechnet die Größe aus dem Platz aus, in dem sie sitzt - das hält eine 24-Pixel-Leiste und ein 64-Pixel-Symbol wie ein Design aussehend. Unter %d Pixeln ist eine Zahl da und nicht lesbar, deshalb springt der Regler von null direkt auf %d.",
    ["Show this place"] = "Diesen Platz zeigen",
    ["Ready means you can press it. Working means the buff it put on you is still running - Anti-Magic Shell, Blood Shield. Recharging is neither."] =
        "Bereit heißt, du kannst ihn drücken. Wirkt heißt, der Buff, den er dir gegeben hat, läuft noch - Antimagische Hülle, Blutschild. Lädt nach ist keins von beidem.",
    ["When"] = "Wann",
    ["When to show it"] = "Wann sie zu sehen ist",
    ["Combat"] = "Kampf",
    ["Group"] = "Gruppe",
    ["Target"] = "Ziel",
    ["Rested"] = "Ausgeruht",
    ["Otherwise"] = "Sonst",
    ["gone"] = "weg",
    ["Rows and columns"] = "Zeilen und Spalten",
    ["Columns and Rows lay the places out, and either one sets how many places that comes to. Places is the total underneath and may be fewer than the rectangle holds - seven places in two rows of four leaves the last one empty."] =
        "Spalten und Zeilen legen die Plätze aus, und jede von beiden setzt, wie viele Plätze das ergibt. Plätze ist die Gesamtzahl darunter und darf kleiner sein, als das Rechteck fasst - sieben Plätze in zwei Zeilen zu vier lassen den letzten frei.",
    ["%d spells sit past the last place and are not drawn. Nothing was thrown away - make room and they come back where they were."] =
        "%d Zauber sitzen hinter dem letzten Platz und werden nicht gezeichnet. Nichts wurde weggeworfen - schaff Platz, und sie kommen dorthin zurück, wo sie waren.",
    ["Delete"] = "Löschen",
    ["No bars yet. Make one and the spells you pick land on it."] =
        "Noch keine Leisten. Leg eine an, dann landen die Zauber, die du aussuchst, darauf.",
    ["Text"] = "Text",
    ["Effects"] = "Effekte",
    ["Fill"] = "Füllung",
    ["Blizzard"] = "Blizzard",
    ["Spell name"] = "Zaubername",
    ["A band starts at one stack. To switch one off, take it away - a band of nought would be crossed by an aura that is merely there."] =
        "Ein Band beginnt bei einem Stapel. Zum Abschalten nimm es weg - ein Band bei null würde von jeder bloß vorhandenen Aura überschritten.",
    ["A band takes the fill's colour over once the stack count reaches its number. The highest one reached is the one you see."] =
        "Ein Band übernimmt die Farbe der Füllung, sobald die Stapelzahl seine Zahl erreicht. Sichtbar ist das höchste erreichte.",
    ["A bright line on the moving edge"] =
        "Eine helle Linie auf der laufenden Kante",
    ["A plate under the art. Spell art is opaque and fills its place, so you only see this where the art does not cover it - along a border, and behind a bar-shaped place."] =
        "Eine Platte unter dem Bild. Zaubergrafik ist deckend und füllt ihren Platz, du siehst das hier also nur dort, wo sie ihn nicht bedeckt - am Rand entlang und hinter einem leistenförmigen Platz.",
    ["A pulse the moment the cooldown ends"] =
        "Ein Puls in dem Moment, in dem der Cooldown endet",
    ["A spell that has been ready this long IN COMBAT starts pulsing. For the defensive you keep forgetting."] =
        "Ein Zauber, der IM KAMPF so lange bereit war, beginnt zu pulsieren. Für den Defensiven, den du immer vergisst.",
    ["These reach the ICON. The fill and the plate each have their own opacity setting. 'While inactive' only has something to dim on a tracked buff bar."] =
        "Diese erreichen das SYMBOL. Füllung und Platte haben je eine eigene Deckkraft. 'Während inaktiv' hat nur bei einer verfolgten Buff-Leiste etwas zu dimmen.",
    ["Add a band"] = "Band hinzufügen",
    ["An icon place is square and uses the first of these; a bar place is the other two. Which one a bar's places are is up under Arrangement."] =
        "Ein Symbolplatz ist quadratisch und nutzt den ersten Wert; ein Leistenplatz die anderen beiden. Welche Art die Plätze einer Leiste sind, steht oben unter Anordnung.",
    ["Behind the icon"] = "Hinter dem Symbol",
    ["Belongs to the staggered pattern and is ignored by the others. As a share of one cell, so it stays right when you change the icon size."] =
        "Gehört zum versetzten Muster und wird von den anderen ignoriert. Als Anteil einer Zelle, damit es stimmt, wenn du die Symbolgröße änderst.",
    ["The global cooldown never sets any of this off."] =
        "Der globale Cooldown löst hier nichts aus.",
    ["Blizzard's icon art has a border baked into the file. Cropping cuts it off; at 0 you see the whole thing, frame and all. Above a fifth it starts eating the picture instead."] =
        "Blizzards Symbolgrafik hat einen Rand fest in der Datei. Der Zuschnitt schneidet ihn ab; bei 0 siehst du alles, Rahmen inklusive. Über einem Fünftel frisst er stattdessen das Bild an.",
    ["Bottom"] = "Unten",
    ["Bottom left"] = "Unten links",
    ["Bottom right"] = "Unten rechts",
    ["Centre"] = "Mitte",
    ["Charge marks"] = "Ladungsmarken",
    ["Charge marks and the spark"] = "Ladungsmarken und der Funke",
    ["Charge marks only appear on a spell that HAS more than one charge, so the switch can stay on for a whole bar without marking everything on it."] =
        "Ladungsmarken erscheinen nur bei einem Zauber, der mehr als eine Ladung HAT - der Schalter kann also für eine ganze Leiste an bleiben, ohne alles darauf zu markieren.",
    ["Changing"] = "Du änderst",
    ["Charges"] = "Ladungen",
    ["Click a place in the picture to change just that one, or the card itself to change the whole bar. What a place carries of its own wins over the bar, which is why a colour set on the bar can leave one place looking untouched."] =
        "Klick im Bild auf einen Platz, um nur diesen zu ändern, oder auf die Karte selbst für die ganze Leiste. Was ein Platz selbst mitbringt, gewinnt gegen die Leiste - deshalb kann eine auf der Leiste gesetzte Farbe einen Platz unberührt lassen.",
    ["Close up"] = "Aufrücken",
    ["Close up in the row"] = "In der Reihe aufrücken",
    ["Crop"] = "Zuschnitt",
    ["Follow the bar again"] = "Wieder der Leiste folgen",
    ["Edge colour"] = "Kantenfarbe",
    ["Edge style"] = "Kantenstil",
    ["Edge thickness"] = "Kantenstärke",
    ["Everything that pulses"] = "Alles, was pulsiert",
    ["Flash"] = "Blitz",
    ["Flash colour"] = "Blitzfarbe",
    ["Flat colour"] = "Einfarbig",
    ["Font"] = "Schrift",
    ["From"] = "Ab",
    ["Glow in the window"] = "Im Fenster leuchten",
    ["Glow while it is up"] = "Leuchten, solange er oben ist",
    ["Gradient"] = "Verlauf",
    ["Grey out while it is down"] = "Ausgrauen, solange sie aus ist",
    ["Grey out while it runs"] = "Ausgrauen, solange er läuft",
    ["Greying and hiding"] = "Ausgrauen und Ausblenden",
    ["How grey"] = "Wie grau",
    ["How many"] = "Wie viele",
    ["How many squares"] = "Wie viele Quadrate",
    ["Its colour"] = "Seine Farbe",
    ["Keep an edge"] = "Kante behalten",
    ["Keeps the edge dark while you are short of the resource. Range and target are ignored - a defensive with nothing targeted is not the same as one you cannot pay for."] =
        "Hält die Kante dunkel, solange dir die Ressource fehlt. Reichweite und Ziel bleiben außen vor - ein Defensiver ohne Ziel ist nicht dasselbe wie einer, den du nicht bezahlen kannst.",
    ["Leading edge"] = "Vordere Kante",
    ["Leave it empty"] = "Leer lassen",
    ["Leaving it empty keeps everything where you learned it. Closing up in the ROW keeps a grid's shape, so the second row stays the second row."] =
        "Leer lassen hält alles dort, wo du es gelernt hast. In der REIHE aufrücken behält die Form des Rasters, die zweite Reihe bleibt also die zweite Reihe.",
    ["Left"] = "Links",
    ["Mark colour"] = "Markenfarbe",
    ["Not drawn in this version. What you set here is kept."] =
        "Wird in dieser Version noch nicht gezeichnet. Was du einstellst, bleibt erhalten.",
    ["None is a crisp one-pixel line drawn from colour textures, and it stays sharper than any edge file at small sizes. The rest come from whatever your other addons registered."] =
        "Keine ist eine scharfe Ein-Pixel-Linie aus Farbtexturen und bleibt bei kleinen Größen schärfer als jede Kantendatei. Der Rest kommt aus dem, was deine anderen Addons registriert haben.",
    ["Nothing"] = "Nichts",
    ["Nudge across"] = "Waagerecht verschieben",
    ["Nudge up"] = "Senkrecht verschieben",
    ["One line per charge boundary"] = "Eine Linie pro Ladungsgrenze",
    ["One speed for the flash, the nag and the squares"] =
        "Eine Geschwindigkeit für den Blitz, das Nörgeln und die Quadrate",
    ["Only closes up what the row above takes off screen"] =
        "Rückt nur auf, was die Regel darüber vom Bildschirm nimmt",
    ["Only the one-pixel line - an edge file takes one colour"] =
        "Nur die Ein-Pixel-Linie - eine Kantendatei nimmt eine Farbe",
    ["Only when you can pay for it"] = "Nur, wenn du ihn bezahlen kannst",
    ["Outline"] = "Umrandung",
    ["Over time"] = "Mit der Zeit",
    ["Position"] = "Position",
    ["Ready is always on screen. Press a defensive and it stays while its own buff is still running - Anti-Magic Shell, Blood Shield - and goes for the rest of the cooldown. Anything the client will not answer for stays where it is."] =
        "Bereit ist immer auf dem Bildschirm. Drück einen Defensiven und er bleibt, solange sein eigener Buff läuft - Antimagische Hülle, Blutschild - und geht für den Rest des Cooldowns. Was der Client nicht beantwortet, bleibt, wo es ist.",
    ["Remind me after"] = "Erinnern nach",
    ["Reminder colour"] = "Erinnerungsfarbe",
    ["Right"] = "Rechts",
    ["Running squares"] = "Laufende Quadrate",
    ["Background"] = "Hintergrund",
    ["Background colour"] = "Hintergrundfarbe",
    ["Background opacity"] = "Hintergrund-Deckkraft",
    ["Behind the fill, where the bar is not full yet"] =
        "Hinter der Füllung, wo die Leiste noch nicht voll ist",
    ["Same as behind the icon"] = "Wie hinter dem Symbol",
    ["Same as everywhere"] = "Wie überall",
    ["Second colour"] = "Zweite Farbe",
    ["Size"] = "Größe",
    ["Soft edge"] = "Weiche Kante",
    ["Some places on this bar carry a look of their own and keep it. What you change here reaches every other place."] =
        "Manche Plätze dieser Leiste haben ein eigenes Aussehen und behalten es. Was du hier änderst, erreicht jeden anderen Platz.",
    ["Spark"] = "Funke",
    ["The whole bar"] = "Die ganze Leiste",
    ["This place also carries settings from an older version, filed under its position rather than its spell. Those are left exactly as they are."] =
        "Dieser Platz trägt außerdem Einstellungen einer älteren Version, abgelegt unter seiner Position statt unter seinem Zauber. Die bleiben unangetastet.",
    ["Speed"] = "Geschwindigkeit",
    ["Stack colours"] = "Stapelfarben",
    ["Stack count"] = "Stapelzahl",
    ["Take off screen"] = "Vom Bildschirm nehmen",
    ["Take this band away"] = "Dieses Band entfernen",
    ["That is as many bands as one bar carries (%d). Take one away to add another."] =
        "Mehr Bänder trägt eine Leiste nicht (%d). Nimm eines weg, um ein anderes hinzuzufügen.",
    ["The bar's fill"] = "Die Füllung der Leiste",
    ["The bright line the sweep drags behind it"] =
        "Die helle Linie, die der Zeiger hinter sich herzieht",
    ["The cooldown sweep"] = "Der Cooldown-Zeiger",
    ["The edge while it is ready"] = "Die Kante, solange er bereit ist",
    ["The empty place"] = "Der leere Platz",
    ["The icon"] = "Das Symbol",
    ["The nag"] = "Das Nörgeln",
    ["The refresh window"] = "Das Auffrischfenster",
    ["The tail of an aura where recasting wastes nothing. Lights only for auras with pandemic alerts switched on in the game's settings."] =
        "Das Ende einer Aura, in dem ein Neuwirken nichts verschenkt. Leuchtet nur für Auren, für die Pandemie-Hinweise in den Einstellungen des Spiels an sind.",
    ["These reach a place Blizzard draws as a tracked buff BAR. An icon has no fill of its own, whichever shape this bar's places are set to."] =
        "Diese erreichen einen Platz, den Blizzard als verfolgte Buff-LEISTE zeichnet. Ein Symbol hat keine eigene Füllung, egal welche Form für die Plätze dieser Leiste eingestellt ist.",
    ["Top"] = "Oben",
    ["Top left"] = "Oben links",
    ["Top right"] = "Oben rechts",
    ["Whether the bar fills or empties while the cooldown runs. The clock belongs to Blizzard's own template and it re-drives the bar on every update, so this is the one setting here whose undo is its owner putting it back."] =
        "Ob sich die Leiste füllt oder leert, während der Cooldown läuft. Die Uhr gehört Blizzards eigener Vorlage und treibt die Leiste bei jeder Aktualisierung neu an - das ist also die eine Einstellung hier, deren Rücknahme ihr Eigentümer selbst vornimmt.",
    ["While inactive"] = "Während inaktiv",
    ["While recharging"] = "Während des Aufladens",
    ["While the buff is up"] = "Solange der Buff oben ist",
    ["Window colour"] = "Fensterfarbe",
    ["auto"] = "auto",
    ["off"] = "aus",
    ["Every spell"] = "Jeder Zauber",
    ["Click one to put it on the bar."] =
        "Klick einen an, um ihn auf die Leiste zu legen.",
    ["Click to fill place %d of %s"] = "Klicken füllt Platz %d von %s",
    ["Click to add it to %s"] = "Klicken legt ihn auf %s",
})

---------------------------------------------------------------------------
-- frFR
---------------------------------------------------------------------------
Register("frFR", {
    ["Edit mode"] = "Mode édition",
    ["Bars"] = "Barres",
    ["M+ and raid stuff"] = "M+ et raid",
    ["System"] = "Système",
    ["Info"] = "Infos",

    ["Cooldowns"] = "Temps de recharge",
    ["Tank Unitframes"] = "Unitframes des tanks",
    ["Reminders"] = "Rappels",
    ["External CD request"] = "Demander un externe",
    ["External CD answer"] = "Donner un externe",
    ["Death-log"] = "Journal des morts",
    ["Raid Bar"] = "Barre de raid",
    ["Invites"] = "Invitations",
    ["Settings"] = "Réglages",
    ["Profiles"] = "Profils",
    ["Diagnostics"] = "Diagnostic",
    ["About"] = "À propos",
    ["Changelog"] = "Nouveautés",

    ["Close"] = "Fermer",
    ["Cancel"] = "Annuler",
    ["Done"] = "Terminé",
    ["Show"] = "Afficher",
    ["Hide"] = "Masquer",
    ["Colour"] = "Couleur",
    ["Texture"] = "Texture",
    ["Thickness"] = "Épaisseur",
    ["Scale"] = "Échelle",
    ["Opacity"] = "Opacité",
    ["Spacing"] = "Espacement",
    ["Rows"] = "Lignes",
    ["Columns"] = "Colonnes",
    ["Runs"] = "Sens",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Taille des icônes",
    ["Look"] = "Apparence",
    ["Border"] = "Bordure",
    ["Backdrop"] = "Fond",
    ["Set keys"] = "Assigner les touches",
    ["Test mode"] = "Mode test",
    ["Test mode: on"] = "Mode test : actif",
    ["Only in a group"] = "Seulement en groupe",
    ["Only in combat"] = "Seulement en combat",
    ["Only in an instance"] = "Seulement en instance",
    ["Nothing yet"] = "Rien pour l'instant",
    ["Switch it on"] = "Activer",
    ["Language"] = "Langue",
    ["Same as the game"] = "Comme le jeu",
    ["Missing lines are shown in English."] = "Les lignes manquantes restent en anglais.",
    ["%s is switched off"] = "%s est désactivé",
    ["Right-click clears every marker."] = "Le clic droit efface tous les symboles.",
    ["Right-click takes this one away."] = "Le clic droit retire celle-ci.",
    ["Right-click cancels it."] = "Le clic droit annule.",

    ["Not now"] = "Plus tard",
    ["Open settings"] = "Réglages",
    ["Show the welcome screen"] = "Afficher l'accueil",
    ["NEW"] = "NOUVEAU",
    ["BETA"] = "BÊTA",
    ["HIDDEN"] = "MASQUÉ",
    ["Not on screen"] = "Pas à l'écran",

    ["Modules"] = "Modules",
    ["Every bar"] = "Toutes les barres",
    ["This window"] = "Cette fenêtre",
    ["Ways in"] = "Accès",
    ["Minimap button"] = "Bouton de minicarte",
    ["Lock its position"] = "Verrouiller sa position",
    ["Game menu entry"] = "Entrée dans le menu du jeu",
    ["Bar text"] = "Texte des barres",
    ["Panel font"] = "Police des fenêtres",
    ["Take the display over"] = "Reprendre l'affichage",

    ["Markers"] = "Symboles",
    ["World markers"] = "Balises de zone",
    ["Clear markers"] = "Effacer les symboles",
    ["Clear world markers"] = "Effacer les balises",
    ["Ready check"] = "Vérification",
    ["Pull timer"] = "Compte à rebours",
    ["Cancel the pull"] = "Annuler le pull",
    ["Raid check"] = "Contrôle du raid",
    ["Countdown"] = "Compte à rebours",
    ["Pull"] = "Pull",
    ["Ready"] = "Prêt",
    ["Clear"] = "Effacer",
    ["Ping"] = "Ping",
    ["Attack"] = "Attaquer",
    ["Assist"] = "Aider",
    ["On my way"] = "J'arrive",
    ["Warning"] = "Attention",
    ["Your raid bar"] = "Votre barre de raid",
    ["Every button"] = "Tous les boutons",
    ["Click one to put it on your bar."] = "Cliquez pour l'ajouter à votre barre.",
    ["The bar"] = "La barre",
    ["Seconds"] = "Secondes",
    ["Right-click seconds"] = "Secondes au clic droit",
    ["Only for the leader"] = "Seulement pour le chef",
    ["Not while in combat"] = "Pas en combat",
    ["You need lead or assist for that."] = "Il faut être chef ou assistant.",
    ["You are not in a group."] = "Vous n'êtes pas en groupe.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "La barre ne peut pas être reconstruite en combat. Ce sera fait dès que vous en sortirez.",

    ["Name"] = "Nom",
    ["Item level"] = "Niveau d'objet",
    ["Durability"] = "Durabilité",
    ["Food"] = "Nourriture",
    ["Flask"] = "Flacon",
    ["Rune"] = "Rune",
    ["Stamina"] = "Endurance",
    ["Intellect"] = "Intelligence",
    ["Attack power"] = "Puissance d'attaque",
    ["Versatility"] = "Polyvalence",
    ["Mastery"] = "Maîtrise",
    ["Movement"] = "Déplacement",
    ["Ask the group"] = "Demander au groupe",
    ["No answer"] = "Pas de réponse",
    ["Waiting for answers"] = "En attente de réponses",
    ["Nobody has answered yet."] = "Personne n'a encore répondu.",
    ["Only players running this addon can answer."] =
        "Seuls les joueurs qui utilisent cet addon peuvent répondre.",
    ["%d of %d answered"] = "%d sur %d ont répondu",

    ["Invite"] = "Inviter",
    ["Keywords"] = "Mots-clés",
    ["Invite on a whisper"] = "Inviter sur chuchotement",
    ["Also on say and yell"] = "Aussi sur dire et crier",
    ["Guild members only"] = "Guilde seulement",
    ["Friends only"] = "Amis seulement",
    ["Make it a raid at five"] = "Passer en raid à cinq",
    ["Accept invites from friends"] = "Accepter les invitations des amis",
    ["Promote"] = "Promouvoir",
    ["Disband"] = "Dissoudre",
    ["Invite everyone back"] = "Réinviter tout le monde",
    ["Invite the guild"] = "Inviter la guilde",
    ["Guild rank"] = "Rang de guilde",
    ["Any rank"] = "Tous les rangs",
    ["Difficulty"] = "Difficulté",
    ["Normal"] = "Normal",
    ["Heroic"] = "Héroïque",
    ["Mythic"] = "Mythique",
    ["Nobody to invite back."] = "Personne à réinviter.",
    ["Invited %s."] = "%s invité.",
    ["The group is empty."] = "Le groupe est vide.",
    ["One word per line."] = "Un mot par ligne.",

    ["%d features in one addon. Switch off what you do not want."] =
        "%d fonctions dans un addon. Désactivez ce que vous ne voulez pas.",
    ["Off, the panel never appears."] = "Désactivé, la fenêtre n'apparaît jamais.",
    ["Pick a language, then reload."] = "Choisissez une langue, puis rechargez.",
    ["Rows times columns is how many places there are."] =
        "Lignes fois colonnes donne le nombre de places.",
    ["The gap between two icons."] = "L'écart entre deux icônes.",
    ["How big each button is on your screen."] =
        "La taille de chaque bouton à l'écran.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Seul, il n'y a personne à qui demander : elle reste cachée.",
})

---------------------------------------------------------------------------
-- esES
---------------------------------------------------------------------------
Register("esES", {
    ["Edit mode"] = "Modo edición",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ y banda",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Reutilizaciones",
    ["Tank Unitframes"] = "Unitframes de tanques",
    ["Reminders"] = "Recordatorios",
    ["External CD request"] = "Pedir un externo",
    ["External CD answer"] = "Dar un externo",
    ["Death-log"] = "Registro de muertes",
    ["Raid Bar"] = "Barra de banda",
    ["Invites"] = "Invitaciones",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfiles",
    ["Diagnostics"] = "Diagnóstico",
    ["About"] = "Acerca de",
    ["Changelog"] = "Novedades",

    ["Close"] = "Cerrar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Hecho",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Color",
    ["Texture"] = "Textura",
    ["Thickness"] = "Grosor",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidad",
    ["Spacing"] = "Espaciado",
    ["Rows"] = "Filas",
    ["Columns"] = "Columnas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Tamaño de icono",
    ["Look"] = "Aspecto",
    ["Border"] = "Borde",
    ["Backdrop"] = "Fondo",
    ["Set keys"] = "Asignar teclas",
    ["Test mode"] = "Modo prueba",
    ["Test mode: on"] = "Modo prueba: activo",
    ["Only in a group"] = "Solo en grupo",
    ["Only in combat"] = "Solo en combate",
    ["Only in an instance"] = "Solo en una instancia",
    ["Nothing yet"] = "Nada todavía",
    ["Switch it on"] = "Activar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Como el juego",
    ["Missing lines are shown in English."] = "Las líneas que faltan salen en inglés.",
    ["%s is switched off"] = "%s está desactivado",
    ["Right-click clears every marker."] = "El clic derecho quita todas las marcas.",
    ["Right-click takes this one away."] = "El clic derecho quita esta.",
    ["Right-click cancels it."] = "El clic derecho lo cancela.",

    ["Not now"] = "Ahora no",
    ["Open settings"] = "Ajustes",
    ["Show the welcome screen"] = "Mostrar la bienvenida",
    ["NEW"] = "NUEVO",
    ["BETA"] = "BETA",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "No está en pantalla",

    ["Modules"] = "Módulos",
    ["Every bar"] = "Todas las barras",
    ["This window"] = "Esta ventana",
    ["Ways in"] = "Accesos",
    ["Minimap button"] = "Botón del minimapa",
    ["Lock its position"] = "Bloquear su posición",
    ["Game menu entry"] = "Entrada en el menú del juego",
    ["Bar text"] = "Texto de las barras",
    ["Panel font"] = "Fuente de las ventanas",
    ["Take the display over"] = "Tomar el control de la pantalla",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de zona",
    ["Clear markers"] = "Quitar marcas",
    ["Clear world markers"] = "Quitar marcas de zona",
    ["Ready check"] = "Comprobar preparación",
    ["Pull timer"] = "Cuenta atrás",
    ["Cancel the pull"] = "Cancelar el pull",
    ["Raid check"] = "Revisión de banda",
    ["Countdown"] = "Cuenta atrás",
    ["Pull"] = "Pull",
    ["Ready"] = "Listo",
    ["Clear"] = "Limpiar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ayudar",
    ["On my way"] = "Voy de camino",
    ["Warning"] = "Cuidado",
    ["Your raid bar"] = "Tu barra de banda",
    ["Every button"] = "Todos los botones",
    ["Click one to put it on your bar."] = "Haz clic para ponerlo en la barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos con clic derecho",
    ["Only for the leader"] = "Solo para el líder",
    ["Not while in combat"] = "No en combate",
    ["You need lead or assist for that."] = "Necesitas ser líder o asistente.",
    ["You are not in a group."] = "No estás en un grupo.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "La barra no puede rehacerse en combate. Se hará en cuanto salgas de él.",

    ["Name"] = "Nombre",
    ["Item level"] = "Nivel de objeto",
    ["Durability"] = "Durabilidad",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Aguante",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidad",
    ["Mastery"] = "Maestría",
    ["Movement"] = "Movimiento",
    ["Ask the group"] = "Preguntar al grupo",
    ["No answer"] = "Sin respuesta",
    ["Waiting for answers"] = "Esperando respuestas",
    ["Nobody has answered yet."] = "Nadie ha respondido todavía.",
    ["Only players running this addon can answer."] =
        "Solo pueden responder los jugadores con este addon.",
    ["%d of %d answered"] = "%d de %d han respondido",

    ["Invite"] = "Invitar",
    ["Keywords"] = "Palabras clave",
    ["Invite on a whisper"] = "Invitar al susurrar",
    ["Also on say and yell"] = "También al decir y gritar",
    ["Guild members only"] = "Solo la hermandad",
    ["Friends only"] = "Solo amigos",
    ["Make it a raid at five"] = "Convertir en banda con cinco",
    ["Accept invites from friends"] = "Aceptar invitaciones de amigos",
    ["Promote"] = "Ascender",
    ["Disband"] = "Disolver",
    ["Invite everyone back"] = "Volver a invitar a todos",
    ["Invite the guild"] = "Invitar a la hermandad",
    ["Guild rank"] = "Rango de hermandad",
    ["Any rank"] = "Cualquier rango",
    ["Difficulty"] = "Dificultad",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "Mítico",
    ["Nobody to invite back."] = "No hay a quién volver a invitar.",
    ["Invited %s."] = "%s invitado.",
    ["The group is empty."] = "El grupo está vacío.",
    ["One word per line."] = "Una palabra por línea.",

    ["%d features in one addon. Switch off what you do not want."] =
        "%d funciones en un addon. Desactiva lo que no quieras.",
    ["Off, the panel never appears."] = "Desactivado, la ventana no aparece nunca.",
    ["Pick a language, then reload."] = "Elige un idioma y recarga.",
    ["Rows times columns is how many places there are."] =
        "Filas por columnas son los sitios que hay.",
    ["The gap between two icons."] = "El hueco entre dos iconos.",
    ["How big each button is on your screen."] =
        "El tamaño de cada botón en tu pantalla.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Solo no hay a quién pedir nada, así que no aparece.",
})

---------------------------------------------------------------------------
-- esMX - the same language, and the differences are real ones. Everything
-- not listed here falls through to... nothing: there is no inheritance
-- between tables on purpose (a chain is a second rule to get wrong), so the
-- untranslated lines fall back to English like everywhere else.
---------------------------------------------------------------------------
Register("esMX", {
    ["Edit mode"] = "Modo edición",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ y banda",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Reutilizaciones",
    ["Tank Unitframes"] = "Unitframes de tanques",
    ["Reminders"] = "Recordatorios",
    ["External CD request"] = "Pedir un externo",
    ["External CD answer"] = "Dar un externo",
    ["Death-log"] = "Registro de muertes",
    ["Raid Bar"] = "Barra de banda",
    ["Invites"] = "Invitaciones",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfiles",
    ["Diagnostics"] = "Diagnóstico",
    ["About"] = "Acerca de",
    ["Changelog"] = "Novedades",

    ["Close"] = "Cerrar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Listo",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Color",
    ["Texture"] = "Textura",
    ["Thickness"] = "Grosor",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidad",
    ["Spacing"] = "Espaciado",
    ["Rows"] = "Filas",
    ["Columns"] = "Columnas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Tamaño de icono",
    ["Look"] = "Aspecto",
    ["Border"] = "Borde",
    ["Backdrop"] = "Fondo",
    ["Set keys"] = "Asignar teclas",
    ["Test mode"] = "Modo prueba",
    ["Test mode: on"] = "Modo prueba: activo",
    ["Only in a group"] = "Solo en grupo",
    ["Only in combat"] = "Solo en combate",
    ["Only in an instance"] = "Solo en una instancia",
    ["Nothing yet"] = "Nada todavía",
    ["Switch it on"] = "Activar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Como el juego",
    ["Missing lines are shown in English."] = "Las líneas que faltan salen en inglés.",
    ["%s is switched off"] = "%s está desactivado",
    ["Right-click clears every marker."] = "El clic derecho quita todas las marcas.",
    ["Right-click takes this one away."] = "El clic derecho quita esta.",
    ["Right-click cancels it."] = "El clic derecho lo cancela.",

    ["Not now"] = "Ahora no",
    ["Open settings"] = "Ajustes",
    ["Show the welcome screen"] = "Mostrar la bienvenida",
    ["NEW"] = "NUEVO",
    ["BETA"] = "BETA",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "No está en pantalla",

    ["Modules"] = "Módulos",
    ["Every bar"] = "Todas las barras",
    ["This window"] = "Esta ventana",
    ["Ways in"] = "Accesos",
    ["Minimap button"] = "Botón del minimapa",
    ["Lock its position"] = "Bloquear su posición",
    ["Game menu entry"] = "Entrada en el menú del juego",
    ["Bar text"] = "Texto de las barras",
    ["Panel font"] = "Fuente de las ventanas",
    ["Take the display over"] = "Tomar el control de la pantalla",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de zona",
    ["Clear markers"] = "Quitar marcas",
    ["Clear world markers"] = "Quitar marcas de zona",
    ["Ready check"] = "Comprobar preparación",
    ["Pull timer"] = "Cuenta regresiva",
    ["Cancel the pull"] = "Cancelar el pull",
    ["Raid check"] = "Revisión de banda",
    ["Countdown"] = "Cuenta regresiva",
    ["Pull"] = "Pull",
    ["Ready"] = "Listo",
    ["Clear"] = "Limpiar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ayudar",
    ["On my way"] = "Voy en camino",
    ["Warning"] = "Cuidado",
    ["Your raid bar"] = "Tu barra de banda",
    ["Every button"] = "Todos los botones",
    ["Click one to put it on your bar."] = "Haz clic para ponerlo en la barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos con clic derecho",
    ["Only for the leader"] = "Solo para el líder",
    ["Not while in combat"] = "No en combate",
    ["You need lead or assist for that."] = "Necesitas ser líder o asistente.",
    ["You are not in a group."] = "No estás en un grupo.",

    ["Name"] = "Nombre",
    ["Item level"] = "Nivel de objeto",
    ["Durability"] = "Durabilidad",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Aguante",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidad",
    ["Mastery"] = "Maestría",
    ["Movement"] = "Movimiento",
    ["Ask the group"] = "Preguntar al grupo",
    ["No answer"] = "Sin respuesta",
    ["Waiting for answers"] = "Esperando respuestas",
    ["Nobody has answered yet."] = "Nadie ha respondido todavía.",
    ["%d of %d answered"] = "%d de %d respondieron",

    ["Invite"] = "Invitar",
    ["Keywords"] = "Palabras clave",
    ["Invite on a whisper"] = "Invitar al susurrar",
    ["Also on say and yell"] = "También al decir y gritar",
    ["Guild members only"] = "Solo la hermandad",
    ["Friends only"] = "Solo amigos",
    ["Make it a raid at five"] = "Convertir en banda con cinco",
    ["Accept invites from friends"] = "Aceptar invitaciones de amigos",
    ["Promote"] = "Ascender",
    ["Disband"] = "Disolver",
    ["Invite everyone back"] = "Volver a invitar a todos",
    ["Invite the guild"] = "Invitar a la hermandad",
    ["Guild rank"] = "Rango de hermandad",
    ["Any rank"] = "Cualquier rango",
    ["Difficulty"] = "Dificultad",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "Mítico",
    ["The group is empty."] = "El grupo está vacío.",
    ["One word per line."] = "Una palabra por línea.",
})

---------------------------------------------------------------------------
-- itIT
---------------------------------------------------------------------------
Register("itIT", {
    ["Edit mode"] = "Modifica",
    ["Bars"] = "Barre",
    ["M+ and raid stuff"] = "M+ e incursione",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Recuperi",
    ["Tank Unitframes"] = "Unitframes dei tank",
    ["Reminders"] = "Promemoria",
    ["External CD request"] = "Chiedi un esterno",
    ["External CD answer"] = "Dai un esterno",
    ["Death-log"] = "Registro morti",
    ["Raid Bar"] = "Barra incursione",
    ["Invites"] = "Inviti",
    ["Settings"] = "Impostazioni",
    ["Profiles"] = "Profili",
    ["Diagnostics"] = "Diagnostica",
    ["About"] = "Informazioni",
    ["Changelog"] = "Novità",

    ["Close"] = "Chiudi",
    ["Cancel"] = "Annulla",
    ["Done"] = "Fatto",
    ["Show"] = "Mostra",
    ["Hide"] = "Nascondi",
    ["Colour"] = "Colore",
    ["Texture"] = "Trama",
    ["Thickness"] = "Spessore",
    ["Scale"] = "Scala",
    ["Opacity"] = "Opacità",
    ["Spacing"] = "Spaziatura",
    ["Rows"] = "Righe",
    ["Columns"] = "Colonne",
    ["Runs"] = "Direzione",
    ["Across"] = "Orizzontale",
    ["Down"] = "Verticale",
    ["Icon size"] = "Dimensione icone",
    ["Look"] = "Aspetto",
    ["Border"] = "Bordo",
    ["Backdrop"] = "Sfondo",
    ["Set keys"] = "Assegna i tasti",
    ["Test mode"] = "Modalità prova",
    ["Test mode: on"] = "Modalità prova: attiva",
    ["Only in a group"] = "Solo in gruppo",
    ["Only in combat"] = "Solo in combattimento",
    ["Only in an instance"] = "Solo in un'istanza",
    ["Nothing yet"] = "Ancora niente",
    ["Switch it on"] = "Attiva",
    ["Language"] = "Lingua",
    ["Same as the game"] = "Come il gioco",
    ["Missing lines are shown in English."] = "Le righe mancanti restano in inglese.",
    ["%s is switched off"] = "%s è disattivato",
    ["Right-click clears every marker."] = "Il tasto destro toglie tutti i simboli.",
    ["Right-click takes this one away."] = "Il tasto destro toglie questo.",
    ["Right-click cancels it."] = "Il tasto destro annulla.",

    ["Not now"] = "Non ora",
    ["Open settings"] = "Impostazioni",
    ["Show the welcome screen"] = "Mostra il benvenuto",
    ["NEW"] = "NUOVO",
    ["BETA"] = "BETA",
    ["HIDDEN"] = "NASCOSTO",
    ["Not on screen"] = "Non è sullo schermo",

    ["Modules"] = "Moduli",
    ["Every bar"] = "Tutte le barre",
    ["This window"] = "Questa finestra",
    ["Ways in"] = "Accessi",
    ["Minimap button"] = "Pulsante minimappa",
    ["Lock its position"] = "Blocca la posizione",
    ["Game menu entry"] = "Voce nel menu di gioco",
    ["Bar text"] = "Testo delle barre",
    ["Panel font"] = "Carattere delle finestre",
    ["Take the display over"] = "Prendi il controllo",

    ["Markers"] = "Simboli",
    ["World markers"] = "Segnalini",
    ["Clear markers"] = "Togli i simboli",
    ["Clear world markers"] = "Togli i segnalini",
    ["Ready check"] = "Controllo pronti",
    ["Pull timer"] = "Conto alla rovescia",
    ["Cancel the pull"] = "Annulla il pull",
    ["Raid check"] = "Controllo incursione",
    ["Countdown"] = "Conto alla rovescia",
    ["Pull"] = "Pull",
    ["Ready"] = "Pronto",
    ["Clear"] = "Pulisci",
    ["Ping"] = "Ping",
    ["Attack"] = "Attacca",
    ["Assist"] = "Aiuta",
    ["On my way"] = "Sto arrivando",
    ["Warning"] = "Attenzione",
    ["Your raid bar"] = "La tua barra",
    ["Every button"] = "Tutti i pulsanti",
    ["Click one to put it on your bar."] = "Clicca per metterlo sulla barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Secondi",
    ["Right-click seconds"] = "Secondi col tasto destro",
    ["Only for the leader"] = "Solo per il capo",
    ["Not while in combat"] = "Non in combattimento",
    ["You need lead or assist for that."] = "Serve essere capo o assistente.",
    ["You are not in a group."] = "Non sei in un gruppo.",

    ["Name"] = "Nome",
    ["Item level"] = "Livello oggetti",
    ["Durability"] = "Integrità",
    ["Food"] = "Cibo",
    ["Flask"] = "Fiala",
    ["Rune"] = "Runa",
    ["Stamina"] = "Tempra",
    ["Intellect"] = "Intelletto",
    ["Attack power"] = "Potere d'attacco",
    ["Versatility"] = "Versatilità",
    ["Mastery"] = "Maestria",
    ["Movement"] = "Movimento",
    ["Ask the group"] = "Chiedi al gruppo",
    ["No answer"] = "Nessuna risposta",
    ["Waiting for answers"] = "In attesa di risposte",
    ["Nobody has answered yet."] = "Non ha ancora risposto nessuno.",
    ["%d of %d answered"] = "%d su %d hanno risposto",

    ["Invite"] = "Invita",
    ["Keywords"] = "Parole chiave",
    ["Invite on a whisper"] = "Invita su sussurro",
    ["Also on say and yell"] = "Anche su dire e urlare",
    ["Guild members only"] = "Solo la gilda",
    ["Friends only"] = "Solo amici",
    ["Make it a raid at five"] = "Converti in incursione a cinque",
    ["Accept invites from friends"] = "Accetta gli inviti degli amici",
    ["Promote"] = "Promuovi",
    ["Disband"] = "Sciogli",
    ["Invite everyone back"] = "Reinvita tutti",
    ["Invite the guild"] = "Invita la gilda",
    ["Guild rank"] = "Grado di gilda",
    ["Any rank"] = "Qualsiasi grado",
    ["Difficulty"] = "Difficoltà",
    ["Normal"] = "Normale",
    ["Heroic"] = "Eroica",
    ["Mythic"] = "Mitica",
    ["The group is empty."] = "Il gruppo è vuoto.",
    ["One word per line."] = "Una parola per riga.",
})

---------------------------------------------------------------------------
-- ptBR
---------------------------------------------------------------------------
Register("ptBR", {
    ["Edit mode"] = "Modo de edição",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ e raide",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Recargas",
    ["Tank Unitframes"] = "Unitframes dos tanques",
    ["Reminders"] = "Lembretes",
    ["External CD request"] = "Pedir um externo",
    ["External CD answer"] = "Dar um externo",
    ["Death-log"] = "Registro de mortes",
    ["Raid Bar"] = "Barra de raide",
    ["Invites"] = "Convites",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfis",
    ["Diagnostics"] = "Diagnóstico",
    ["About"] = "Sobre",
    ["Changelog"] = "Novidades",

    ["Close"] = "Fechar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Pronto",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Cor",
    ["Texture"] = "Textura",
    ["Thickness"] = "Espessura",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidade",
    ["Spacing"] = "Espaçamento",
    ["Rows"] = "Linhas",
    ["Columns"] = "Colunas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Tamanho do ícone",
    ["Look"] = "Aparência",
    ["Border"] = "Borda",
    ["Backdrop"] = "Fundo",
    ["Set keys"] = "Definir teclas",
    ["Test mode"] = "Modo de teste",
    ["Test mode: on"] = "Modo de teste: ativo",
    ["Only in a group"] = "Só em grupo",
    ["Only in combat"] = "Só em combate",
    ["Only in an instance"] = "Só em uma masmorra",
    ["Nothing yet"] = "Nada ainda",
    ["Switch it on"] = "Ativar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Igual ao jogo",
    ["Missing lines are shown in English."] = "As linhas que faltam aparecem em inglês.",
    ["%s is switched off"] = "%s está desligado",
    ["Right-click clears every marker."] = "O clique direito limpa todas as marcas.",
    ["Right-click takes this one away."] = "O clique direito tira esta.",
    ["Right-click cancels it."] = "O clique direito cancela.",

    ["Not now"] = "Agora não",
    ["Open settings"] = "Ajustes",
    ["Show the welcome screen"] = "Mostrar as boas-vindas",
    ["NEW"] = "NOVO",
    ["BETA"] = "BETA",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "Não está na tela",

    ["Modules"] = "Módulos",
    ["Every bar"] = "Todas as barras",
    ["This window"] = "Esta janela",
    ["Ways in"] = "Acessos",
    ["Minimap button"] = "Botão do minimapa",
    ["Lock its position"] = "Travar a posição",
    ["Game menu entry"] = "Entrada no menu do jogo",
    ["Bar text"] = "Texto das barras",
    ["Panel font"] = "Fonte das janelas",
    ["Take the display over"] = "Assumir o visor",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de área",
    ["Clear markers"] = "Limpar marcas",
    ["Clear world markers"] = "Limpar marcas de área",
    ["Ready check"] = "Verificar prontidão",
    ["Pull timer"] = "Contagem regressiva",
    ["Cancel the pull"] = "Cancelar o pull",
    ["Raid check"] = "Checagem do raide",
    ["Countdown"] = "Contagem regressiva",
    ["Pull"] = "Pull",
    ["Ready"] = "Pronto",
    ["Clear"] = "Limpar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ajudar",
    ["On my way"] = "Estou indo",
    ["Warning"] = "Atenção",
    ["Your raid bar"] = "Sua barra de raide",
    ["Every button"] = "Todos os botões",
    ["Click one to put it on your bar."] = "Clique para colocar na barra.",
    ["The bar"] = "A barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos no botão direito",
    ["Only for the leader"] = "Só para o líder",
    ["Not while in combat"] = "Não em combate",
    ["You need lead or assist for that."] = "Você precisa ser líder ou assistente.",
    ["You are not in a group."] = "Você não está em um grupo.",

    ["Name"] = "Nome",
    ["Item level"] = "Nível de item",
    ["Durability"] = "Durabilidade",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Vigor",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidade",
    ["Mastery"] = "Maestria",
    ["Movement"] = "Movimento",
    ["Ask the group"] = "Perguntar ao grupo",
    ["No answer"] = "Sem resposta",
    ["Waiting for answers"] = "Aguardando respostas",
    ["Nobody has answered yet."] = "Ninguém respondeu ainda.",
    ["%d of %d answered"] = "%d de %d responderam",

    ["Invite"] = "Convidar",
    ["Keywords"] = "Palavras-chave",
    ["Invite on a whisper"] = "Convidar ao sussurrar",
    ["Also on say and yell"] = "Também ao falar e gritar",
    ["Guild members only"] = "Só a guilda",
    ["Friends only"] = "Só amigos",
    ["Make it a raid at five"] = "Virar raide com cinco",
    ["Accept invites from friends"] = "Aceitar convites de amigos",
    ["Promote"] = "Promover",
    ["Disband"] = "Desfazer o grupo",
    ["Invite everyone back"] = "Convidar todos de volta",
    ["Invite the guild"] = "Convidar a guilda",
    ["Guild rank"] = "Cargo na guilda",
    ["Any rank"] = "Qualquer cargo",
    ["Difficulty"] = "Dificuldade",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "Mítico",
    ["The group is empty."] = "O grupo está vazio.",
    ["One word per line."] = "Uma palavra por linha.",
})

---------------------------------------------------------------------------
-- ruRU
---------------------------------------------------------------------------
Register("ruRU", {
    ["Edit mode"] = "Режим правки",
    ["Bars"] = "Панели",
    ["M+ and raid stuff"] = "М+ и рейд",
    ["Info"] = "Инфо",

    ["Tank Unitframes"] = "Фреймы танков",
    ["Reminders"] = "Напоминания",
    ["External CD answer"] = "Дать внешний КД",
    ["Raid Bar"] = "Рейдовая панель",
    ["Invites"] = "Приглашения",
    ["Profiles"] = "Профили",
    ["About"] = "О дополнении",
    ["Changelog"] = "Изменения",

    ["Close"] = "Закрыть",
    ["Cancel"] = "Отмена",
    ["Done"] = "Готово",
    ["Show"] = "Показать",
    ["Hide"] = "Скрыть",
    ["Colour"] = "Цвет",
    ["Thickness"] = "Толщина",
    ["Rows"] = "Строки",
    ["Columns"] = "Столбцы",
    ["Runs"] = "Направление",
    ["Across"] = "По горизонтали",
    ["Down"] = "По вертикали",
    ["Icon size"] = "Размер значка",
    ["Look"] = "Вид",
    ["Border"] = "Рамка",
    ["Backdrop"] = "Подложка",
    ["Set keys"] = "Назначить клавиши",
    ["Only in a group"] = "Только в группе",
    ["Only in combat"] = "Только в бою",
    ["Only in an instance"] = "Только в подземелье",
    ["Switch it on"] = "Включить",
    ["Language"] = "Язык",
    ["Same as the game"] = "Как в игре",
    ["%s is switched off"] = "%s выключен",
    ["Right-click takes this one away."] = "Правая кнопка убирает эту метку.",
    ["Right-click cancels it."] = "Правая кнопка отменяет.",

    ["Open settings"] = "Настройки",
    ["NEW"] = "НОВОЕ",
    ["BETA"] = "БЕТА",
    ["HIDDEN"] = "СКРЫТО",
    ["Not on screen"] = "Нет на экране",

    ["Modules"] = "Модули",
    ["This window"] = "Это окно",
    ["Minimap button"] = "Кнопка у миникарты",
    ["Lock its position"] = "Закрепить положение",
    ["Game menu entry"] = "Пункт в игровом меню",
    ["Panel font"] = "Шрифт окон",

    ["Markers"] = "Метки",
    ["World markers"] = "Метки на земле",
    ["Clear markers"] = "Убрать метки",
    ["Clear world markers"] = "Убрать метки на земле",
    ["Cancel the pull"] = "Отменить пул",
    ["Raid check"] = "Проверка рейда",
    ["Pull"] = "Пул",
    ["Ready"] = "Готов",
    ["Ping"] = "Пинг",
    ["Attack"] = "Атака",
    ["Assist"] = "Помощь",
    ["On my way"] = "Иду",
    ["Warning"] = "Внимание",
    ["Your raid bar"] = "Ваша рейдовая панель",
    ["Click one to put it on your bar."] = "Нажмите, чтобы добавить на панель.",
    ["The bar"] = "Панель",
    ["Seconds"] = "Секунды",
    ["Right-click seconds"] = "Секунды по правой кнопке",
    ["Only for the leader"] = "Только для лидера",
    ["Not while in combat"] = "Не в бою",
    ["You need lead or assist for that."] = "Нужны права лидера или помощника.",
    ["You are not in a group."] = "Вы не в группе.",

    ["Name"] = "Имя",
    ["Item level"] = "Уровень предметов",
    ["Food"] = "Еда",
    ["Rune"] = "Руна",
    ["Intellect"] = "Интеллект",
    ["Attack power"] = "Сила атаки",
    ["No answer"] = "Нет ответа",
    ["Waiting for answers"] = "Ожидание ответов",
    ["Nobody has answered yet."] = "Пока никто не ответил.",
    ["%d of %d answered"] = "Ответили %d из %d",

    ["Invite on a whisper"] = "Приглашать по шёпоту",
    ["Guild members only"] = "Только гильдия",
    ["Friends only"] = "Только друзья",
    ["Make it a raid at five"] = "Собрать рейд при пяти",
    ["Accept invites from friends"] = "Принимать приглашения друзей",
    ["Guild rank"] = "Ранг в гильдии",
    ["Any rank"] = "Любой ранг",
    ["Normal"] = "Обычный",
    ["Mythic"] = "Эпохальный",
})

---------------------------------------------------------------------------
-- koKR - the vocabulary. See the header: the short labels are here, the
-- sentences are left in English on purpose rather than guessed at.
---------------------------------------------------------------------------
Register("koKR", {
    ["Edit mode"] = "편집 모드",
    ["Bars"] = "바",
    ["System"] = "시스템",
    ["Info"] = "정보",

    ["Cooldowns"] = "재사용 대기시간",
    ["Reminders"] = "알림",
    ["Death-log"] = "죽음 기록",
    ["Raid Bar"] = "공격대 바",
    ["Invites"] = "초대",
    ["Settings"] = "설정",
    ["Profiles"] = "프로필",
    ["Diagnostics"] = "진단",
    ["About"] = "정보",
    ["Changelog"] = "변경 내역",

    ["Close"] = "닫기",
    ["Cancel"] = "취소",
    ["Done"] = "완료",
    ["Show"] = "표시",
    ["Hide"] = "숨기기",
    ["Texture"] = "텍스처",
    ["Thickness"] = "두께",
    ["Opacity"] = "불투명도",
    ["Spacing"] = "간격",
    ["Rows"] = "행",
    ["Columns"] = "열",
    ["Look"] = "모양",
    ["Border"] = "테두리",
    ["Backdrop"] = "배경",
    ["Language"] = "언어",
    ["Switch it on"] = "켜기",
    ["Modules"] = "모듈",
    ["Not now"] = "나중에",

    ["World markers"] = "지역 표시",
    ["Ready check"] = "준비 확인",
    ["Pull timer"] = "풀 타이머",
    ["Raid check"] = "공격대 점검",
    ["Ready"] = "준비",
    ["Clear"] = "지우기",
    ["Ping"] = "핑",
    ["Attack"] = "공격",
    ["Assist"] = "지원",
    ["Warning"] = "경고",
    ["Seconds"] = "초",

    ["Name"] = "이름",
    ["Item level"] = "아이템 레벨",
    ["Durability"] = "내구도",
    ["Food"] = "음식",
    ["Rune"] = "룬",
    ["Stamina"] = "체력",
    ["Intellect"] = "지능",
    ["Attack power"] = "공격력",
    ["Versatility"] = "특화",
    ["Mastery"] = "특화",
    ["Movement"] = "이동 속도",
    ["No answer"] = "응답 없음",

    ["Invite"] = "초대",
    ["Keywords"] = "키워드",
    ["Promote"] = "승급",
    ["Disband"] = "해산",
    ["Difficulty"] = "난이도",
    ["Normal"] = "일반",
    ["Mythic"] = "신화",
})

---------------------------------------------------------------------------
-- zhCN
---------------------------------------------------------------------------
Register("zhCN", {
    ["Edit mode"] = "编辑模式",
    ["Bars"] = "条",
    ["System"] = "系统",

    ["Cooldowns"] = "冷却",
    ["Reminders"] = "提醒",
    ["Death-log"] = "死亡记录",
    ["Raid Bar"] = "团队栏",
    ["Invites"] = "邀请",
    ["Settings"] = "设置",
    ["Profiles"] = "配置",
    ["Diagnostics"] = "诊断",
    ["About"] = "关于",
    ["Changelog"] = "更新日志",

    ["Close"] = "关闭",
    ["Cancel"] = "取消",
    ["Done"] = "完成",
    ["Show"] = "显示",
    ["Hide"] = "隐藏",
    ["Colour"] = "颜色",
    ["Texture"] = "材质",
    ["Thickness"] = "粗细",
    ["Scale"] = "缩放",
    ["Opacity"] = "不透明度",
    ["Spacing"] = "间距",
    ["Rows"] = "行",
    ["Columns"] = "列",
    ["Icon size"] = "图标大小",
    ["Look"] = "外观",
    ["Border"] = "边框",
    ["Backdrop"] = "背景",
    ["Language"] = "语言",
    ["Switch it on"] = "开启",
    ["Modules"] = "模块",
    ["Not now"] = "暂不",

    ["Markers"] = "标记",
    ["World markers"] = "场景标记",
    ["Ready check"] = "准备确认",
    ["Pull timer"] = "开怪倒计时",
    ["Raid check"] = "团队检查",
    ["Ready"] = "准备",
    ["Clear"] = "清除",
    ["Ping"] = "标点",
    ["Attack"] = "攻击",
    ["Assist"] = "协助",
    ["Warning"] = "警告",
    ["Seconds"] = "秒",

    ["Name"] = "名字",
    ["Item level"] = "装等",
    ["Durability"] = "耐久度",
    ["Food"] = "食物",
    ["Flask"] = "合剂",
    ["Rune"] = "符文",
    ["Stamina"] = "耐力",
    ["Intellect"] = "智力",
    ["Attack power"] = "攻击强度",
    ["Versatility"] = "全能",
    ["Mastery"] = "精通",
    ["Movement"] = "移动速度",
    ["No answer"] = "无回应",

    ["Invite"] = "邀请",
    ["Keywords"] = "关键词",
    ["Promote"] = "提升",
    ["Disband"] = "解散",
    ["Difficulty"] = "难度",
    ["Normal"] = "普通",
    ["Heroic"] = "英雄",
    ["Mythic"] = "史诗",
})

---------------------------------------------------------------------------
-- zhTW
---------------------------------------------------------------------------
Register("zhTW", {
    ["Edit mode"] = "編輯模式",
    ["Bars"] = "列",
    ["System"] = "系統",
    ["Info"] = "資訊",

    ["Cooldowns"] = "冷卻",
    ["Reminders"] = "提醒",
    ["Death-log"] = "死亡記錄",
    ["Raid Bar"] = "團隊列",
    ["Invites"] = "邀請",
    ["Settings"] = "設定",
    ["Profiles"] = "設定檔",
    ["Diagnostics"] = "診斷",
    ["About"] = "關於",
    ["Changelog"] = "更新記錄",

    ["Close"] = "關閉",
    ["Cancel"] = "取消",
    ["Done"] = "完成",
    ["Show"] = "顯示",
    ["Hide"] = "隱藏",
    ["Colour"] = "顏色",
    ["Texture"] = "材質",
    ["Thickness"] = "粗細",
    ["Scale"] = "縮放",
    ["Opacity"] = "不透明度",
    ["Spacing"] = "間距",
    ["Rows"] = "列數",
    ["Columns"] = "行數",
    ["Icon size"] = "圖示大小",
    ["Look"] = "外觀",
    ["Border"] = "邊框",
    ["Backdrop"] = "背景",
    ["Language"] = "語言",
    ["Switch it on"] = "開啟",
    ["Modules"] = "模組",
    ["Not now"] = "稍後",

    ["Markers"] = "標記",
    ["World markers"] = "場景標記",
    ["Ready check"] = "準備確認",
    ["Pull timer"] = "開怪倒數",
    ["Raid check"] = "團隊檢查",
    ["Ready"] = "準備",
    ["Clear"] = "清除",
    ["Ping"] = "標點",
    ["Attack"] = "攻擊",
    ["Assist"] = "協助",
    ["Warning"] = "警告",
    ["Seconds"] = "秒",

    ["Name"] = "名字",
    ["Item level"] = "裝等",
    ["Durability"] = "耐久度",
    ["Food"] = "食物",
    ["Flask"] = "合劑",
    ["Rune"] = "符文",
    ["Stamina"] = "耐力",
    ["Intellect"] = "智力",
    ["Attack power"] = "攻擊強度",
    ["Versatility"] = "臨機應變",
    ["Mastery"] = "精通",
    ["Movement"] = "移動速度",
    ["No answer"] = "無回應",

    ["Invite"] = "邀請",
    ["Keywords"] = "關鍵字",
    ["Promote"] = "晉升",
    ["Disband"] = "解散",
    ["Difficulty"] = "難度",
    ["Normal"] = "普通",
    ["Heroic"] = "英雄",
    ["Mythic"] = "史詩",
})
