---------------------------------------------------------------------------
-- Languages - every translation this addon ships.
--
-- ONE FILE, and it is a deliberate choice against the usual one-file-per-
-- language layout. Which language to use is read from the PROFILE, and the
-- profile is not open when these tables load - so a file that loads only when
-- it is the client's language could never honour somebody who chose a
-- different one, which is exactly the setting the owner asked for. Every
-- table is therefore resident, and one file is the honest way to say so.
--
-- WHAT THAT COSTS: measured with memcheck.lua, not guessed. See the handoff.
-- It is a table of strings; the whole file weighs less than one row of the
-- spell palette, and switching language then needs no second load.
--
-- enUS IS THE MASTER. Its keys are the list of strings this addon localises
-- at all. Every other table is held to it by the self test:
--   * a key that is not in enUS is a translation of something never asked for
--   * a key missing from a language shows as its English self, which is the
--     whole point of the key being the English sentence
--
-- SO AN UNFINISHED LANGUAGE IS NOT A BROKEN ONE. `/zs loca` prints how far
-- each has got, and `/zs loca deDE` prints exactly which lines are left.
--
-- HOW TO ADD A LINE: put the English sentence in the enUS table, wrap the
-- place it is drawn in L["..."], and the other ten tables are now one line
-- short - which the coverage number says out loud rather than hiding.
--
-- THE STATE OF THE NINE, honestly: German is complete. French, Spanish (both),
-- Italian, Portuguese and Russian carry the whole interface vocabulary and
-- the sentences. Korean and both Chinese carry the vocabulary - the short
-- labels that fill the window - and leave the longer sentences in English,
-- because a wrong sentence in a language nobody here reads cannot be spotted
-- and a missing one falls back to something correct.
---------------------------------------------------------------------------
local _, ns = ...

local Register = ns.Locale.Register

---------------------------------------------------------------------------
-- enUS - the master list
---------------------------------------------------------------------------
Register("enUS", {
    -- The rail
    ["Edit mode"] = true,
    ["Bars"] = true,
    ["M+ and raid stuff"] = true,
    ["System"] = true,
    ["Info"] = true,

    -- Page names. Also the module names, which is not a coincidence - a
    -- feature and its page are one thing with one name.
    ["Cooldowns"] = true,
    ["Co-Tanks"] = true,
    ["Reminders"] = true,
    ["External CD request"] = true,
    ["External CD answer"] = true,
    ["Death-log"] = true,
    ["Raid Bar"] = true,
    ["Invites"] = true,
    ["Settings"] = true,
    ["Profiles"] = true,
    ["Diagnostics"] = true,
    ["About"] = true,
    ["Changelog"] = true,

    -- Words that appear on more than one page
    ["Close"] = true,
    ["Cancel"] = true,
    ["Done"] = true,
    ["Show"] = true,
    ["Hide"] = true,
    ["Colour"] = true,
    ["Texture"] = true,
    ["Thickness"] = true,
    ["Scale"] = true,
    ["Opacity"] = true,
    ["Spacing"] = true,
    ["Rows"] = true,
    ["Columns"] = true,
    ["Runs"] = true,
    ["Across"] = true,
    ["Down"] = true,
    ["Icon size"] = true,
    ["Look"] = true,
    ["Border"] = true,
    ["Backdrop"] = true,
    ["Keys"] = true,
    ["Set keys"] = true,
    ["Test mode"] = true,
    ["Test mode: on"] = true,
    ["Only in a group"] = true,
    ["Only in combat"] = true,
    ["Only in an instance"] = true,
    ["Nothing yet"] = true,
    ["Switch it on"] = true,
    ["Language"] = true,
    ["Same as the game"] = true,
    ["Missing lines are shown in English."] = true,
    ["%s is switched off"] = true,
    ["Right-click clears every marker."] = true,
    ["Right-click takes this one away."] = true,
    ["Right-click cancels it."] = true,

    -- Welcome
    ["Not now"] = true,
    ["Let's go"] = true,
    ["Show the welcome screen"] = true,
    ["NEW"] = true,
    ["HIDDEN"] = true,
    ["Not on screen"] = true,

    -- Settings
    ["Modules"] = true,
    ["Every bar"] = true,
    ["This window"] = true,
    ["Ways in"] = true,
    ["Minimap button"] = true,
    ["Lock its position"] = true,
    ["Game menu entry"] = true,
    ["Bar text"] = true,
    ["Panel font"] = true,
    ["Take the display over"] = true,

    ---------------------------------------------------------------------
    -- Raid Bar
    ---------------------------------------------------------------------
    ["Markers"] = true,
    ["World markers"] = true,
    ["Clear markers"] = true,
    ["Clear world markers"] = true,
    ["Ready check"] = true,
    ["Pull timer"] = true,
    ["Cancel the pull"] = true,
    ["Raid check"] = true,
    ["Countdown"] = true,
    ["Pull"] = true,
    ["Ready"] = true,
    ["Clear"] = true,
    ["Ping"] = true,
    ["Attack"] = true,
    ["Assist"] = true,
    ["On my way"] = true,
    ["Warning"] = true,
    ["Your raid bar"] = true,
    ["Every button"] = true,
    ["Click one to put it on your bar."] = true,
    ["The bar"] = true,
    ["Seconds"] = true,
    ["Right-click seconds"] = true,
    ["Only for the leader"] = true,
    ["Not while in combat"] = true,
    ["You need lead or assist for that."] = true,
    ["You are not in a group."] = true,
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] = true,

    ---------------------------------------------------------------------
    -- Raid check window
    ---------------------------------------------------------------------
    ["Name"] = true,
    ["Item level"] = true,
    ["Durability"] = true,
    ["Food"] = true,
    ["Flask"] = true,
    ["Rune"] = true,
    ["Stamina"] = true,
    ["Intellect"] = true,
    ["Attack power"] = true,
    ["Versatility"] = true,
    ["Mastery"] = true,
    ["Movement"] = true,
    ["Ask the group"] = true,
    ["No answer"] = true,
    ["Waiting for answers"] = true,
    ["Nobody has answered yet."] = true,
    ["Only players running this addon can answer."] = true,
    ["%d of %d answered"] = true,

    ---------------------------------------------------------------------
    -- Invites
    ---------------------------------------------------------------------
    ["Invite"] = true,
    ["Keywords"] = true,
    ["Invite on a whisper"] = true,
    ["Also on say and yell"] = true,
    ["Guild members only"] = true,
    ["Friends only"] = true,
    ["Make it a raid at five"] = true,
    ["Accept invites from friends"] = true,
    ["Promote"] = true,
    ["Disband"] = true,
    ["Invite everyone back"] = true,
    ["Invite the guild"] = true,
    ["Guild rank"] = true,
    ["Any rank"] = true,
    ["Difficulty"] = true,
    ["Normal"] = true,
    ["Heroic"] = true,
    ["Mythic"] = true,
    ["Nobody to invite back."] = true,
    ["Invited %s."] = true,
    ["The group is empty."] = true,
    ["One word per line."] = true,

    ---------------------------------------------------------------------
    -- Sentences. Longer, and the ones a half-finished language leaves in
    -- English rather than getting wrong.
    ---------------------------------------------------------------------
    ["%d features in one addon. Pick the ones you want running."] = true,
    ["%d features in one addon. Switch off what you do not want."] = true,
    ["Off, the panel never appears."] = true,
    ["Pick a language, then reload."] = true,
    ["The window is drawn when it opens, so a new language reaches it after a |cffffd100/reload|r."] = true,
    ["Rows times columns is how many places there are."] = true,
    ["The gap between two icons."] = true,
    ["How big each button is on your screen."] = true,
    ["On your own there is nobody to ask, so it stays away."] = true,
})

---------------------------------------------------------------------------
-- deDE
---------------------------------------------------------------------------
Register("deDE", {
    ["Edit mode"] = "Bearbeiten",
    ["Bars"] = "Leisten",
    ["M+ and raid stuff"] = "M+ und Schlachtzug",
    ["System"] = "System",
    ["Info"] = "Info",

    ["Cooldowns"] = "Abklingzeiten",
    ["Co-Tanks"] = "Mit-Tanks",
    ["Reminders"] = "Erinnerungen",
    ["External CD request"] = "Externen CD anfragen",
    ["External CD answer"] = "Externen CD geben",
    ["Death-log"] = "Todesprotokoll",
    ["Raid Bar"] = "Schlachtzugsleiste",
    ["Invites"] = "Einladungen",
    ["Settings"] = "Einstellungen",
    ["Profiles"] = "Profile",
    ["Diagnostics"] = "Diagnose",
    ["About"] = "Über",
    ["Changelog"] = "Änderungen",

    ["Close"] = "Schließen",
    ["Cancel"] = "Abbrechen",
    ["Done"] = "Fertig",
    ["Show"] = "Anzeigen",
    ["Hide"] = "Ausblenden",
    ["Colour"] = "Farbe",
    ["Texture"] = "Textur",
    ["Thickness"] = "Stärke",
    ["Scale"] = "Skalierung",
    ["Opacity"] = "Deckkraft",
    ["Spacing"] = "Abstand",
    ["Rows"] = "Zeilen",
    ["Columns"] = "Spalten",
    ["Runs"] = "Verlauf",
    ["Across"] = "Waagerecht",
    ["Down"] = "Senkrecht",
    ["Icon size"] = "Symbolgröße",
    ["Look"] = "Aussehen",
    ["Border"] = "Rahmen",
    ["Backdrop"] = "Hintergrund",
    ["Keys"] = "Tasten",
    ["Set keys"] = "Tasten belegen",
    ["Test mode"] = "Testmodus",
    ["Test mode: on"] = "Testmodus: an",
    ["Only in a group"] = "Nur in einer Gruppe",
    ["Only in combat"] = "Nur im Kampf",
    ["Only in an instance"] = "Nur in einer Instanz",
    ["Nothing yet"] = "Noch nichts",
    ["Switch it on"] = "Einschalten",
    ["Language"] = "Sprache",
    ["Same as the game"] = "Wie das Spiel",
    ["Missing lines are shown in English."] = "Fehlende Zeilen erscheinen auf Englisch.",
    ["%s is switched off"] = "%s ist ausgeschaltet",
    ["Right-click clears every marker."] = "Rechtsklick entfernt alle Zeichen.",
    ["Right-click takes this one away."] = "Rechtsklick nimmt diese wieder weg.",
    ["Right-click cancels it."] = "Rechtsklick bricht ab.",

    ["Not now"] = "Später",
    ["Let's go"] = "Los geht's",
    ["Show the welcome screen"] = "Willkommensfenster zeigen",
    ["NEW"] = "NEU",
    ["HIDDEN"] = "VERSTECKT",
    ["Not on screen"] = "Nicht auf dem Bildschirm",

    ["Modules"] = "Module",
    ["Every bar"] = "Alle Leisten",
    ["This window"] = "Dieses Fenster",
    ["Ways in"] = "Zugänge",
    ["Minimap button"] = "Minikarten-Knopf",
    ["Lock its position"] = "Position sperren",
    ["Game menu entry"] = "Eintrag im Spielmenü",
    ["Bar text"] = "Leistentext",
    ["Panel font"] = "Schrift der Fenster",
    ["Take the display over"] = "Anzeige übernehmen",

    ["Markers"] = "Zeichen",
    ["World markers"] = "Weltmarkierungen",
    ["Clear markers"] = "Zeichen entfernen",
    ["Clear world markers"] = "Weltmarkierungen entfernen",
    ["Ready check"] = "Bereitschaftsprüfung",
    ["Pull timer"] = "Pull-Timer",
    ["Cancel the pull"] = "Pull abbrechen",
    ["Raid check"] = "Raid-Check",
    ["Countdown"] = "Countdown",
    ["Pull"] = "Pull",
    ["Ready"] = "Bereit",
    ["Clear"] = "Löschen",
    ["Ping"] = "Ping",
    ["Attack"] = "Angreifen",
    ["Assist"] = "Helfen",
    ["On my way"] = "Bin unterwegs",
    ["Warning"] = "Achtung",
    ["Your raid bar"] = "Deine Schlachtzugsleiste",
    ["Every button"] = "Alle Knöpfe",
    ["Click one to put it on your bar."] = "Klick einen an, um ihn auf die Leiste zu legen.",
    ["The bar"] = "Die Leiste",
    ["Seconds"] = "Sekunden",
    ["Right-click seconds"] = "Sekunden bei Rechtsklick",
    ["Only for the leader"] = "Nur für den Anführer",
    ["Not while in combat"] = "Nicht im Kampf",
    ["You need lead or assist for that."] = "Dafür brauchst du Anführer oder Assistent.",
    ["You are not in a group."] = "Du bist in keiner Gruppe.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "Die Leiste kann im Kampf nicht neu gebaut werden. Es passiert, sobald du ihn verlässt.",

    ["Name"] = "Name",
    ["Item level"] = "Gegenstandsstufe",
    ["Durability"] = "Haltbarkeit",
    ["Food"] = "Essen",
    ["Flask"] = "Fläschchen",
    ["Rune"] = "Rune",
    ["Stamina"] = "Ausdauer",
    ["Intellect"] = "Intelligenz",
    ["Attack power"] = "Angriffskraft",
    ["Versatility"] = "Vielseitigkeit",
    ["Mastery"] = "Meisterschaft",
    ["Movement"] = "Tempo",
    ["Ask the group"] = "Gruppe fragen",
    ["No answer"] = "Keine Antwort",
    ["Waiting for answers"] = "Warte auf Antworten",
    ["Nobody has answered yet."] = "Noch hat niemand geantwortet.",
    ["Only players running this addon can answer."] =
        "Antworten können nur Spieler, die dieses Addon benutzen.",
    ["%d of %d answered"] = "%d von %d haben geantwortet",

    ["Invite"] = "Einladen",
    ["Keywords"] = "Schlüsselwörter",
    ["Invite on a whisper"] = "Bei Flüstern einladen",
    ["Also on say and yell"] = "Auch bei Sagen und Rufen",
    ["Guild members only"] = "Nur Gildenmitglieder",
    ["Friends only"] = "Nur Freunde",
    ["Make it a raid at five"] = "Bei fünf in Schlachtzug umwandeln",
    ["Accept invites from friends"] = "Einladungen von Freunden annehmen",
    ["Promote"] = "Befördern",
    ["Disband"] = "Auflösen",
    ["Invite everyone back"] = "Alle zurückholen",
    ["Invite the guild"] = "Gilde einladen",
    ["Guild rank"] = "Gildenrang",
    ["Any rank"] = "Jeder Rang",
    ["Difficulty"] = "Schwierigkeit",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroisch",
    ["Mythic"] = "Mythisch",
    ["Nobody to invite back."] = "Niemanden zurückzuholen.",
    ["Invited %s."] = "%s eingeladen.",
    ["The group is empty."] = "Die Gruppe ist leer.",
    ["One word per line."] = "Ein Wort pro Zeile.",

    ["%d features in one addon. Pick the ones you want running."] =
        "%d Funktionen in einem Addon. Wähle die, die laufen sollen.",
    ["%d features in one addon. Switch off what you do not want."] =
        "%d Funktionen in einem Addon. Schalte ab, was du nicht willst.",
    ["Off, the panel never appears."] = "Aus erscheint das Fenster nie.",
    ["Pick a language, then reload."] = "Sprache wählen, dann neu laden.",
    ["The window is drawn when it opens, so a new language reaches it after a |cffffd100/reload|r."] =
        "Das Fenster wird beim Öffnen gezeichnet - eine neue Sprache kommt also erst nach einem |cffffd100/reload|r an.",
    ["Rows times columns is how many places there are."] =
        "Zeilen mal Spalten ergibt die Anzahl der Plätze.",
    ["The gap between two icons."] = "Der Abstand zwischen zwei Symbolen.",
    ["How big each button is on your screen."] =
        "Wie groß jeder Knopf auf deinem Bildschirm ist.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Allein gibt es niemanden zu fragen, also bleibt sie weg.",
})

---------------------------------------------------------------------------
-- frFR
---------------------------------------------------------------------------
Register("frFR", {
    ["Edit mode"] = "Mode édition",
    ["Bars"] = "Barres",
    ["M+ and raid stuff"] = "M+ et raid",
    ["System"] = "Système",
    ["Info"] = "Infos",

    ["Cooldowns"] = "Temps de recharge",
    ["Co-Tanks"] = "Autres tanks",
    ["Reminders"] = "Rappels",
    ["External CD request"] = "Demander un externe",
    ["External CD answer"] = "Donner un externe",
    ["Death-log"] = "Journal des morts",
    ["Raid Bar"] = "Barre de raid",
    ["Invites"] = "Invitations",
    ["Settings"] = "Réglages",
    ["Profiles"] = "Profils",
    ["Diagnostics"] = "Diagnostic",
    ["About"] = "À propos",
    ["Changelog"] = "Nouveautés",

    ["Close"] = "Fermer",
    ["Cancel"] = "Annuler",
    ["Done"] = "Terminé",
    ["Show"] = "Afficher",
    ["Hide"] = "Masquer",
    ["Colour"] = "Couleur",
    ["Texture"] = "Texture",
    ["Thickness"] = "Épaisseur",
    ["Scale"] = "Échelle",
    ["Opacity"] = "Opacité",
    ["Spacing"] = "Espacement",
    ["Rows"] = "Lignes",
    ["Columns"] = "Colonnes",
    ["Runs"] = "Sens",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Taille des icônes",
    ["Look"] = "Apparence",
    ["Border"] = "Bordure",
    ["Backdrop"] = "Fond",
    ["Keys"] = "Touches",
    ["Set keys"] = "Assigner les touches",
    ["Test mode"] = "Mode test",
    ["Test mode: on"] = "Mode test : actif",
    ["Only in a group"] = "Seulement en groupe",
    ["Only in combat"] = "Seulement en combat",
    ["Only in an instance"] = "Seulement en instance",
    ["Nothing yet"] = "Rien pour l'instant",
    ["Switch it on"] = "Activer",
    ["Language"] = "Langue",
    ["Same as the game"] = "Comme le jeu",
    ["Missing lines are shown in English."] = "Les lignes manquantes restent en anglais.",
    ["%s is switched off"] = "%s est désactivé",
    ["Right-click clears every marker."] = "Le clic droit efface tous les symboles.",
    ["Right-click takes this one away."] = "Le clic droit retire celle-ci.",
    ["Right-click cancels it."] = "Le clic droit annule.",

    ["Not now"] = "Plus tard",
    ["Let's go"] = "C'est parti",
    ["Show the welcome screen"] = "Afficher l'accueil",
    ["NEW"] = "NOUVEAU",
    ["HIDDEN"] = "MASQUÉ",
    ["Not on screen"] = "Pas à l'écran",

    ["Modules"] = "Modules",
    ["Every bar"] = "Toutes les barres",
    ["This window"] = "Cette fenêtre",
    ["Ways in"] = "Accès",
    ["Minimap button"] = "Bouton de minicarte",
    ["Lock its position"] = "Verrouiller sa position",
    ["Game menu entry"] = "Entrée dans le menu du jeu",
    ["Bar text"] = "Texte des barres",
    ["Panel font"] = "Police des fenêtres",
    ["Take the display over"] = "Reprendre l'affichage",

    ["Markers"] = "Symboles",
    ["World markers"] = "Balises de zone",
    ["Clear markers"] = "Effacer les symboles",
    ["Clear world markers"] = "Effacer les balises",
    ["Ready check"] = "Vérification",
    ["Pull timer"] = "Compte à rebours",
    ["Cancel the pull"] = "Annuler le pull",
    ["Raid check"] = "Contrôle du raid",
    ["Countdown"] = "Compte à rebours",
    ["Pull"] = "Pull",
    ["Ready"] = "Prêt",
    ["Clear"] = "Effacer",
    ["Ping"] = "Ping",
    ["Attack"] = "Attaquer",
    ["Assist"] = "Aider",
    ["On my way"] = "J'arrive",
    ["Warning"] = "Attention",
    ["Your raid bar"] = "Votre barre de raid",
    ["Every button"] = "Tous les boutons",
    ["Click one to put it on your bar."] = "Cliquez pour l'ajouter à votre barre.",
    ["The bar"] = "La barre",
    ["Seconds"] = "Secondes",
    ["Right-click seconds"] = "Secondes au clic droit",
    ["Only for the leader"] = "Seulement pour le chef",
    ["Not while in combat"] = "Pas en combat",
    ["You need lead or assist for that."] = "Il faut être chef ou assistant.",
    ["You are not in a group."] = "Vous n'êtes pas en groupe.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "La barre ne peut pas être reconstruite en combat. Ce sera fait dès que vous en sortirez.",

    ["Name"] = "Nom",
    ["Item level"] = "Niveau d'objet",
    ["Durability"] = "Durabilité",
    ["Food"] = "Nourriture",
    ["Flask"] = "Flacon",
    ["Rune"] = "Rune",
    ["Stamina"] = "Endurance",
    ["Intellect"] = "Intelligence",
    ["Attack power"] = "Puissance d'attaque",
    ["Versatility"] = "Polyvalence",
    ["Mastery"] = "Maîtrise",
    ["Movement"] = "Déplacement",
    ["Ask the group"] = "Demander au groupe",
    ["No answer"] = "Pas de réponse",
    ["Waiting for answers"] = "En attente de réponses",
    ["Nobody has answered yet."] = "Personne n'a encore répondu.",
    ["Only players running this addon can answer."] =
        "Seuls les joueurs qui utilisent cet addon peuvent répondre.",
    ["%d of %d answered"] = "%d sur %d ont répondu",

    ["Invite"] = "Inviter",
    ["Keywords"] = "Mots-clés",
    ["Invite on a whisper"] = "Inviter sur chuchotement",
    ["Also on say and yell"] = "Aussi sur dire et crier",
    ["Guild members only"] = "Guilde seulement",
    ["Friends only"] = "Amis seulement",
    ["Make it a raid at five"] = "Passer en raid à cinq",
    ["Accept invites from friends"] = "Accepter les invitations des amis",
    ["Promote"] = "Promouvoir",
    ["Disband"] = "Dissoudre",
    ["Invite everyone back"] = "Réinviter tout le monde",
    ["Invite the guild"] = "Inviter la guilde",
    ["Guild rank"] = "Rang de guilde",
    ["Any rank"] = "Tous les rangs",
    ["Difficulty"] = "Difficulté",
    ["Normal"] = "Normal",
    ["Heroic"] = "Héroïque",
    ["Mythic"] = "Mythique",
    ["Nobody to invite back."] = "Personne à réinviter.",
    ["Invited %s."] = "%s invité.",
    ["The group is empty."] = "Le groupe est vide.",
    ["One word per line."] = "Un mot par ligne.",

    ["%d features in one addon. Pick the ones you want running."] =
        "%d fonctions dans un addon. Choisissez celles que vous voulez.",
    ["%d features in one addon. Switch off what you do not want."] =
        "%d fonctions dans un addon. Désactivez ce que vous ne voulez pas.",
    ["Off, the panel never appears."] = "Désactivé, la fenêtre n'apparaît jamais.",
    ["Pick a language, then reload."] = "Choisissez une langue, puis rechargez.",
    ["Rows times columns is how many places there are."] =
        "Lignes fois colonnes donne le nombre de places.",
    ["The gap between two icons."] = "L'écart entre deux icônes.",
    ["How big each button is on your screen."] =
        "La taille de chaque bouton à l'écran.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Seul, il n'y a personne à qui demander : elle reste cachée.",
})

---------------------------------------------------------------------------
-- esES
---------------------------------------------------------------------------
Register("esES", {
    ["Edit mode"] = "Modo edición",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ y banda",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Reutilizaciones",
    ["Co-Tanks"] = "Otros tanques",
    ["Reminders"] = "Recordatorios",
    ["External CD request"] = "Pedir un externo",
    ["External CD answer"] = "Dar un externo",
    ["Death-log"] = "Registro de muertes",
    ["Raid Bar"] = "Barra de banda",
    ["Invites"] = "Invitaciones",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfiles",
    ["Diagnostics"] = "Diagnóstico",
    ["About"] = "Acerca de",
    ["Changelog"] = "Novedades",

    ["Close"] = "Cerrar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Hecho",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Color",
    ["Texture"] = "Textura",
    ["Thickness"] = "Grosor",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidad",
    ["Spacing"] = "Espaciado",
    ["Rows"] = "Filas",
    ["Columns"] = "Columnas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Tamaño de icono",
    ["Look"] = "Aspecto",
    ["Border"] = "Borde",
    ["Backdrop"] = "Fondo",
    ["Keys"] = "Teclas",
    ["Set keys"] = "Asignar teclas",
    ["Test mode"] = "Modo prueba",
    ["Test mode: on"] = "Modo prueba: activo",
    ["Only in a group"] = "Solo en grupo",
    ["Only in combat"] = "Solo en combate",
    ["Only in an instance"] = "Solo en una instancia",
    ["Nothing yet"] = "Nada todavía",
    ["Switch it on"] = "Activar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Como el juego",
    ["Missing lines are shown in English."] = "Las líneas que faltan salen en inglés.",
    ["%s is switched off"] = "%s está desactivado",
    ["Right-click clears every marker."] = "El clic derecho quita todas las marcas.",
    ["Right-click takes this one away."] = "El clic derecho quita esta.",
    ["Right-click cancels it."] = "El clic derecho lo cancela.",

    ["Not now"] = "Ahora no",
    ["Let's go"] = "Adelante",
    ["Show the welcome screen"] = "Mostrar la bienvenida",
    ["NEW"] = "NUEVO",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "No está en pantalla",

    ["Modules"] = "Módulos",
    ["Every bar"] = "Todas las barras",
    ["This window"] = "Esta ventana",
    ["Ways in"] = "Accesos",
    ["Minimap button"] = "Botón del minimapa",
    ["Lock its position"] = "Bloquear su posición",
    ["Game menu entry"] = "Entrada en el menú del juego",
    ["Bar text"] = "Texto de las barras",
    ["Panel font"] = "Fuente de las ventanas",
    ["Take the display over"] = "Tomar el control de la pantalla",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de zona",
    ["Clear markers"] = "Quitar marcas",
    ["Clear world markers"] = "Quitar marcas de zona",
    ["Ready check"] = "Comprobar preparación",
    ["Pull timer"] = "Cuenta atrás",
    ["Cancel the pull"] = "Cancelar el pull",
    ["Raid check"] = "Revisión de banda",
    ["Countdown"] = "Cuenta atrás",
    ["Pull"] = "Pull",
    ["Ready"] = "Listo",
    ["Clear"] = "Limpiar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ayudar",
    ["On my way"] = "Voy de camino",
    ["Warning"] = "Cuidado",
    ["Your raid bar"] = "Tu barra de banda",
    ["Every button"] = "Todos los botones",
    ["Click one to put it on your bar."] = "Haz clic para ponerlo en la barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos con clic derecho",
    ["Only for the leader"] = "Solo para el líder",
    ["Not while in combat"] = "No en combate",
    ["You need lead or assist for that."] = "Necesitas ser líder o asistente.",
    ["You are not in a group."] = "No estás en un grupo.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "La barra no puede rehacerse en combate. Se hará en cuanto salgas de él.",

    ["Name"] = "Nombre",
    ["Item level"] = "Nivel de objeto",
    ["Durability"] = "Durabilidad",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Aguante",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidad",
    ["Mastery"] = "Maestría",
    ["Movement"] = "Movimiento",
    ["Ask the group"] = "Preguntar al grupo",
    ["No answer"] = "Sin respuesta",
    ["Waiting for answers"] = "Esperando respuestas",
    ["Nobody has answered yet."] = "Nadie ha respondido todavía.",
    ["Only players running this addon can answer."] =
        "Solo pueden responder los jugadores con este addon.",
    ["%d of %d answered"] = "%d de %d han respondido",

    ["Invite"] = "Invitar",
    ["Keywords"] = "Palabras clave",
    ["Invite on a whisper"] = "Invitar al susurrar",
    ["Also on say and yell"] = "También al decir y gritar",
    ["Guild members only"] = "Solo la hermandad",
    ["Friends only"] = "Solo amigos",
    ["Make it a raid at five"] = "Convertir en banda con cinco",
    ["Accept invites from friends"] = "Aceptar invitaciones de amigos",
    ["Promote"] = "Ascender",
    ["Disband"] = "Disolver",
    ["Invite everyone back"] = "Volver a invitar a todos",
    ["Invite the guild"] = "Invitar a la hermandad",
    ["Guild rank"] = "Rango de hermandad",
    ["Any rank"] = "Cualquier rango",
    ["Difficulty"] = "Dificultad",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "Mítico",
    ["Nobody to invite back."] = "No hay a quién volver a invitar.",
    ["Invited %s."] = "%s invitado.",
    ["The group is empty."] = "El grupo está vacío.",
    ["One word per line."] = "Una palabra por línea.",

    ["%d features in one addon. Pick the ones you want running."] =
        "%d funciones en un addon. Elige las que quieras usar.",
    ["%d features in one addon. Switch off what you do not want."] =
        "%d funciones en un addon. Desactiva lo que no quieras.",
    ["Off, the panel never appears."] = "Desactivado, la ventana no aparece nunca.",
    ["Pick a language, then reload."] = "Elige un idioma y recarga.",
    ["Rows times columns is how many places there are."] =
        "Filas por columnas son los sitios que hay.",
    ["The gap between two icons."] = "El hueco entre dos iconos.",
    ["How big each button is on your screen."] =
        "El tamaño de cada botón en tu pantalla.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Solo no hay a quién pedir nada, así que no aparece.",
})

---------------------------------------------------------------------------
-- esMX - the same language, and the differences are real ones. Everything
-- not listed here falls through to... nothing: there is no inheritance
-- between tables on purpose (a chain is a second rule to get wrong), so the
-- untranslated lines fall back to English like everywhere else.
---------------------------------------------------------------------------
Register("esMX", {
    ["Edit mode"] = "Modo edición",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ y banda",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Reutilizaciones",
    ["Co-Tanks"] = "Otros tanques",
    ["Reminders"] = "Recordatorios",
    ["External CD request"] = "Pedir un externo",
    ["External CD answer"] = "Dar un externo",
    ["Death-log"] = "Registro de muertes",
    ["Raid Bar"] = "Barra de banda",
    ["Invites"] = "Invitaciones",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfiles",
    ["Diagnostics"] = "Diagnóstico",
    ["About"] = "Acerca de",
    ["Changelog"] = "Novedades",

    ["Close"] = "Cerrar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Listo",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Color",
    ["Texture"] = "Textura",
    ["Thickness"] = "Grosor",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidad",
    ["Spacing"] = "Espaciado",
    ["Rows"] = "Filas",
    ["Columns"] = "Columnas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Tamaño de icono",
    ["Look"] = "Aspecto",
    ["Border"] = "Borde",
    ["Backdrop"] = "Fondo",
    ["Keys"] = "Teclas",
    ["Set keys"] = "Asignar teclas",
    ["Test mode"] = "Modo prueba",
    ["Test mode: on"] = "Modo prueba: activo",
    ["Only in a group"] = "Solo en grupo",
    ["Only in combat"] = "Solo en combate",
    ["Only in an instance"] = "Solo en una instancia",
    ["Nothing yet"] = "Nada todavía",
    ["Switch it on"] = "Activar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Como el juego",
    ["Missing lines are shown in English."] = "Las líneas que faltan salen en inglés.",
    ["%s is switched off"] = "%s está desactivado",
    ["Right-click clears every marker."] = "El clic derecho quita todas las marcas.",
    ["Right-click takes this one away."] = "El clic derecho quita esta.",
    ["Right-click cancels it."] = "El clic derecho lo cancela.",

    ["Not now"] = "Ahora no",
    ["Let's go"] = "Vamos",
    ["Show the welcome screen"] = "Mostrar la bienvenida",
    ["NEW"] = "NUEVO",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "No está en pantalla",

    ["Modules"] = "Módulos",
    ["Every bar"] = "Todas las barras",
    ["This window"] = "Esta ventana",
    ["Ways in"] = "Accesos",
    ["Minimap button"] = "Botón del minimapa",
    ["Lock its position"] = "Bloquear su posición",
    ["Game menu entry"] = "Entrada en el menú del juego",
    ["Bar text"] = "Texto de las barras",
    ["Panel font"] = "Fuente de las ventanas",
    ["Take the display over"] = "Tomar el control de la pantalla",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de zona",
    ["Clear markers"] = "Quitar marcas",
    ["Clear world markers"] = "Quitar marcas de zona",
    ["Ready check"] = "Comprobar preparación",
    ["Pull timer"] = "Cuenta regresiva",
    ["Cancel the pull"] = "Cancelar el pull",
    ["Raid check"] = "Revisión de banda",
    ["Countdown"] = "Cuenta regresiva",
    ["Pull"] = "Pull",
    ["Ready"] = "Listo",
    ["Clear"] = "Limpiar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ayudar",
    ["On my way"] = "Voy en camino",
    ["Warning"] = "Cuidado",
    ["Your raid bar"] = "Tu barra de banda",
    ["Every button"] = "Todos los botones",
    ["Click one to put it on your bar."] = "Haz clic para ponerlo en la barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos con clic derecho",
    ["Only for the leader"] = "Solo para el líder",
    ["Not while in combat"] = "No en combate",
    ["You need lead or assist for that."] = "Necesitas ser líder o asistente.",
    ["You are not in a group."] = "No estás en un grupo.",

    ["Name"] = "Nombre",
    ["Item level"] = "Nivel de objeto",
    ["Durability"] = "Durabilidad",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Aguante",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidad",
    ["Mastery"] = "Maestría",
    ["Movement"] = "Movimiento",
    ["Ask the group"] = "Preguntar al grupo",
    ["No answer"] = "Sin respuesta",
    ["Waiting for answers"] = "Esperando respuestas",
    ["Nobody has answered yet."] = "Nadie ha respondido todavía.",
    ["%d of %d answered"] = "%d de %d respondieron",

    ["Invite"] = "Invitar",
    ["Keywords"] = "Palabras clave",
    ["Invite on a whisper"] = "Invitar al susurrar",
    ["Also on say and yell"] = "También al decir y gritar",
    ["Guild members only"] = "Solo la hermandad",
    ["Friends only"] = "Solo amigos",
    ["Make it a raid at five"] = "Convertir en banda con cinco",
    ["Accept invites from friends"] = "Aceptar invitaciones de amigos",
    ["Promote"] = "Ascender",
    ["Disband"] = "Disolver",
    ["Invite everyone back"] = "Volver a invitar a todos",
    ["Invite the guild"] = "Invitar a la hermandad",
    ["Guild rank"] = "Rango de hermandad",
    ["Any rank"] = "Cualquier rango",
    ["Difficulty"] = "Dificultad",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "Mítico",
    ["The group is empty."] = "El grupo está vacío.",
    ["One word per line."] = "Una palabra por línea.",
})

---------------------------------------------------------------------------
-- itIT
---------------------------------------------------------------------------
Register("itIT", {
    ["Edit mode"] = "Modifica",
    ["Bars"] = "Barre",
    ["M+ and raid stuff"] = "M+ e incursione",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Recuperi",
    ["Co-Tanks"] = "Altri tank",
    ["Reminders"] = "Promemoria",
    ["External CD request"] = "Chiedi un esterno",
    ["External CD answer"] = "Dai un esterno",
    ["Death-log"] = "Registro morti",
    ["Raid Bar"] = "Barra incursione",
    ["Invites"] = "Inviti",
    ["Settings"] = "Impostazioni",
    ["Profiles"] = "Profili",
    ["Diagnostics"] = "Diagnostica",
    ["About"] = "Informazioni",
    ["Changelog"] = "Novità",

    ["Close"] = "Chiudi",
    ["Cancel"] = "Annulla",
    ["Done"] = "Fatto",
    ["Show"] = "Mostra",
    ["Hide"] = "Nascondi",
    ["Colour"] = "Colore",
    ["Texture"] = "Trama",
    ["Thickness"] = "Spessore",
    ["Scale"] = "Scala",
    ["Opacity"] = "Opacità",
    ["Spacing"] = "Spaziatura",
    ["Rows"] = "Righe",
    ["Columns"] = "Colonne",
    ["Runs"] = "Direzione",
    ["Across"] = "Orizzontale",
    ["Down"] = "Verticale",
    ["Icon size"] = "Dimensione icone",
    ["Look"] = "Aspetto",
    ["Border"] = "Bordo",
    ["Backdrop"] = "Sfondo",
    ["Keys"] = "Tasti",
    ["Set keys"] = "Assegna i tasti",
    ["Test mode"] = "Modalità prova",
    ["Test mode: on"] = "Modalità prova: attiva",
    ["Only in a group"] = "Solo in gruppo",
    ["Only in combat"] = "Solo in combattimento",
    ["Only in an instance"] = "Solo in un'istanza",
    ["Nothing yet"] = "Ancora niente",
    ["Switch it on"] = "Attiva",
    ["Language"] = "Lingua",
    ["Same as the game"] = "Come il gioco",
    ["Missing lines are shown in English."] = "Le righe mancanti restano in inglese.",
    ["%s is switched off"] = "%s è disattivato",
    ["Right-click clears every marker."] = "Il tasto destro toglie tutti i simboli.",
    ["Right-click takes this one away."] = "Il tasto destro toglie questo.",
    ["Right-click cancels it."] = "Il tasto destro annulla.",

    ["Not now"] = "Non ora",
    ["Let's go"] = "Andiamo",
    ["Show the welcome screen"] = "Mostra il benvenuto",
    ["NEW"] = "NUOVO",
    ["HIDDEN"] = "NASCOSTO",
    ["Not on screen"] = "Non è sullo schermo",

    ["Modules"] = "Moduli",
    ["Every bar"] = "Tutte le barre",
    ["This window"] = "Questa finestra",
    ["Ways in"] = "Accessi",
    ["Minimap button"] = "Pulsante minimappa",
    ["Lock its position"] = "Blocca la posizione",
    ["Game menu entry"] = "Voce nel menu di gioco",
    ["Bar text"] = "Testo delle barre",
    ["Panel font"] = "Carattere delle finestre",
    ["Take the display over"] = "Prendi il controllo",

    ["Markers"] = "Simboli",
    ["World markers"] = "Segnalini",
    ["Clear markers"] = "Togli i simboli",
    ["Clear world markers"] = "Togli i segnalini",
    ["Ready check"] = "Controllo pronti",
    ["Pull timer"] = "Conto alla rovescia",
    ["Cancel the pull"] = "Annulla il pull",
    ["Raid check"] = "Controllo incursione",
    ["Countdown"] = "Conto alla rovescia",
    ["Pull"] = "Pull",
    ["Ready"] = "Pronto",
    ["Clear"] = "Pulisci",
    ["Ping"] = "Ping",
    ["Attack"] = "Attacca",
    ["Assist"] = "Aiuta",
    ["On my way"] = "Sto arrivando",
    ["Warning"] = "Attenzione",
    ["Your raid bar"] = "La tua barra",
    ["Every button"] = "Tutti i pulsanti",
    ["Click one to put it on your bar."] = "Clicca per metterlo sulla barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Secondi",
    ["Right-click seconds"] = "Secondi col tasto destro",
    ["Only for the leader"] = "Solo per il capo",
    ["Not while in combat"] = "Non in combattimento",
    ["You need lead or assist for that."] = "Serve essere capo o assistente.",
    ["You are not in a group."] = "Non sei in un gruppo.",

    ["Name"] = "Nome",
    ["Item level"] = "Livello oggetti",
    ["Durability"] = "Integrità",
    ["Food"] = "Cibo",
    ["Flask"] = "Fiala",
    ["Rune"] = "Runa",
    ["Stamina"] = "Tempra",
    ["Intellect"] = "Intelletto",
    ["Attack power"] = "Potere d'attacco",
    ["Versatility"] = "Versatilità",
    ["Mastery"] = "Maestria",
    ["Movement"] = "Movimento",
    ["Ask the group"] = "Chiedi al gruppo",
    ["No answer"] = "Nessuna risposta",
    ["Waiting for answers"] = "In attesa di risposte",
    ["Nobody has answered yet."] = "Non ha ancora risposto nessuno.",
    ["%d of %d answered"] = "%d su %d hanno risposto",

    ["Invite"] = "Invita",
    ["Keywords"] = "Parole chiave",
    ["Invite on a whisper"] = "Invita su sussurro",
    ["Also on say and yell"] = "Anche su dire e urlare",
    ["Guild members only"] = "Solo la gilda",
    ["Friends only"] = "Solo amici",
    ["Make it a raid at five"] = "Converti in incursione a cinque",
    ["Accept invites from friends"] = "Accetta gli inviti degli amici",
    ["Promote"] = "Promuovi",
    ["Disband"] = "Sciogli",
    ["Invite everyone back"] = "Reinvita tutti",
    ["Invite the guild"] = "Invita la gilda",
    ["Guild rank"] = "Grado di gilda",
    ["Any rank"] = "Qualsiasi grado",
    ["Difficulty"] = "Difficoltà",
    ["Normal"] = "Normale",
    ["Heroic"] = "Eroica",
    ["Mythic"] = "Mitica",
    ["The group is empty."] = "Il gruppo è vuoto.",
    ["One word per line."] = "Una parola per riga.",
})

---------------------------------------------------------------------------
-- ptBR
---------------------------------------------------------------------------
Register("ptBR", {
    ["Edit mode"] = "Modo de edição",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ e raide",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Recargas",
    ["Co-Tanks"] = "Outros tanques",
    ["Reminders"] = "Lembretes",
    ["External CD request"] = "Pedir um externo",
    ["External CD answer"] = "Dar um externo",
    ["Death-log"] = "Registro de mortes",
    ["Raid Bar"] = "Barra de raide",
    ["Invites"] = "Convites",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfis",
    ["Diagnostics"] = "Diagnóstico",
    ["About"] = "Sobre",
    ["Changelog"] = "Novidades",

    ["Close"] = "Fechar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Pronto",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Cor",
    ["Texture"] = "Textura",
    ["Thickness"] = "Espessura",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidade",
    ["Spacing"] = "Espaçamento",
    ["Rows"] = "Linhas",
    ["Columns"] = "Colunas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Tamanho do ícone",
    ["Look"] = "Aparência",
    ["Border"] = "Borda",
    ["Backdrop"] = "Fundo",
    ["Keys"] = "Teclas",
    ["Set keys"] = "Definir teclas",
    ["Test mode"] = "Modo de teste",
    ["Test mode: on"] = "Modo de teste: ativo",
    ["Only in a group"] = "Só em grupo",
    ["Only in combat"] = "Só em combate",
    ["Only in an instance"] = "Só em uma masmorra",
    ["Nothing yet"] = "Nada ainda",
    ["Switch it on"] = "Ativar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Igual ao jogo",
    ["Missing lines are shown in English."] = "As linhas que faltam aparecem em inglês.",
    ["%s is switched off"] = "%s está desligado",
    ["Right-click clears every marker."] = "O clique direito limpa todas as marcas.",
    ["Right-click takes this one away."] = "O clique direito tira esta.",
    ["Right-click cancels it."] = "O clique direito cancela.",

    ["Not now"] = "Agora não",
    ["Let's go"] = "Vamos",
    ["Show the welcome screen"] = "Mostrar as boas-vindas",
    ["NEW"] = "NOVO",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "Não está na tela",

    ["Modules"] = "Módulos",
    ["Every bar"] = "Todas as barras",
    ["This window"] = "Esta janela",
    ["Ways in"] = "Acessos",
    ["Minimap button"] = "Botão do minimapa",
    ["Lock its position"] = "Travar a posição",
    ["Game menu entry"] = "Entrada no menu do jogo",
    ["Bar text"] = "Texto das barras",
    ["Panel font"] = "Fonte das janelas",
    ["Take the display over"] = "Assumir o visor",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de área",
    ["Clear markers"] = "Limpar marcas",
    ["Clear world markers"] = "Limpar marcas de área",
    ["Ready check"] = "Verificar prontidão",
    ["Pull timer"] = "Contagem regressiva",
    ["Cancel the pull"] = "Cancelar o pull",
    ["Raid check"] = "Checagem do raide",
    ["Countdown"] = "Contagem regressiva",
    ["Pull"] = "Pull",
    ["Ready"] = "Pronto",
    ["Clear"] = "Limpar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ajudar",
    ["On my way"] = "Estou indo",
    ["Warning"] = "Atenção",
    ["Your raid bar"] = "Sua barra de raide",
    ["Every button"] = "Todos os botões",
    ["Click one to put it on your bar."] = "Clique para colocar na barra.",
    ["The bar"] = "A barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos no botão direito",
    ["Only for the leader"] = "Só para o líder",
    ["Not while in combat"] = "Não em combate",
    ["You need lead or assist for that."] = "Você precisa ser líder ou assistente.",
    ["You are not in a group."] = "Você não está em um grupo.",

    ["Name"] = "Nome",
    ["Item level"] = "Nível de item",
    ["Durability"] = "Durabilidade",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Vigor",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidade",
    ["Mastery"] = "Maestria",
    ["Movement"] = "Movimento",
    ["Ask the group"] = "Perguntar ao grupo",
    ["No answer"] = "Sem resposta",
    ["Waiting for answers"] = "Aguardando respostas",
    ["Nobody has answered yet."] = "Ninguém respondeu ainda.",
    ["%d of %d answered"] = "%d de %d responderam",

    ["Invite"] = "Convidar",
    ["Keywords"] = "Palavras-chave",
    ["Invite on a whisper"] = "Convidar ao sussurrar",
    ["Also on say and yell"] = "Também ao falar e gritar",
    ["Guild members only"] = "Só a guilda",
    ["Friends only"] = "Só amigos",
    ["Make it a raid at five"] = "Virar raide com cinco",
    ["Accept invites from friends"] = "Aceitar convites de amigos",
    ["Promote"] = "Promover",
    ["Disband"] = "Desfazer o grupo",
    ["Invite everyone back"] = "Convidar todos de volta",
    ["Invite the guild"] = "Convidar a guilda",
    ["Guild rank"] = "Cargo na guilda",
    ["Any rank"] = "Qualquer cargo",
    ["Difficulty"] = "Dificuldade",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "Mítico",
    ["The group is empty."] = "O grupo está vazio.",
    ["One word per line."] = "Uma palavra por linha.",
})

---------------------------------------------------------------------------
-- ruRU
---------------------------------------------------------------------------
Register("ruRU", {
    ["Edit mode"] = "Режим правки",
    ["Bars"] = "Панели",
    ["M+ and raid stuff"] = "М+ и рейд",
    ["System"] = "Система",
    ["Info"] = "Инфо",

    ["Cooldowns"] = "Восстановление",
    ["Co-Tanks"] = "Другие танки",
    ["Reminders"] = "Напоминания",
    ["External CD request"] = "Просить внешний КД",
    ["External CD answer"] = "Дать внешний КД",
    ["Death-log"] = "Журнал смертей",
    ["Raid Bar"] = "Рейдовая панель",
    ["Invites"] = "Приглашения",
    ["Settings"] = "Настройки",
    ["Profiles"] = "Профили",
    ["Diagnostics"] = "Диагностика",
    ["About"] = "О дополнении",
    ["Changelog"] = "Изменения",

    ["Close"] = "Закрыть",
    ["Cancel"] = "Отмена",
    ["Done"] = "Готово",
    ["Show"] = "Показать",
    ["Hide"] = "Скрыть",
    ["Colour"] = "Цвет",
    ["Texture"] = "Текстура",
    ["Thickness"] = "Толщина",
    ["Scale"] = "Масштаб",
    ["Opacity"] = "Непрозрачность",
    ["Spacing"] = "Отступ",
    ["Rows"] = "Строки",
    ["Columns"] = "Столбцы",
    ["Runs"] = "Направление",
    ["Across"] = "По горизонтали",
    ["Down"] = "По вертикали",
    ["Icon size"] = "Размер значка",
    ["Look"] = "Вид",
    ["Border"] = "Рамка",
    ["Backdrop"] = "Подложка",
    ["Keys"] = "Клавиши",
    ["Set keys"] = "Назначить клавиши",
    ["Test mode"] = "Тестовый режим",
    ["Test mode: on"] = "Тестовый режим: вкл",
    ["Only in a group"] = "Только в группе",
    ["Only in combat"] = "Только в бою",
    ["Only in an instance"] = "Только в подземелье",
    ["Nothing yet"] = "Пока пусто",
    ["Switch it on"] = "Включить",
    ["Language"] = "Язык",
    ["Same as the game"] = "Как в игре",
    ["Missing lines are shown in English."] = "Непереведённые строки показаны на английском.",
    ["%s is switched off"] = "%s выключен",
    ["Right-click clears every marker."] = "Правая кнопка убирает все метки.",
    ["Right-click takes this one away."] = "Правая кнопка убирает эту метку.",
    ["Right-click cancels it."] = "Правая кнопка отменяет.",

    ["Not now"] = "Не сейчас",
    ["Let's go"] = "Поехали",
    ["Show the welcome screen"] = "Показать приветствие",
    ["NEW"] = "НОВОЕ",
    ["HIDDEN"] = "СКРЫТО",
    ["Not on screen"] = "Нет на экране",

    ["Modules"] = "Модули",
    ["Every bar"] = "Все панели",
    ["This window"] = "Это окно",
    ["Ways in"] = "Способы открыть",
    ["Minimap button"] = "Кнопка у миникарты",
    ["Lock its position"] = "Закрепить положение",
    ["Game menu entry"] = "Пункт в игровом меню",
    ["Bar text"] = "Текст на панелях",
    ["Panel font"] = "Шрифт окон",
    ["Take the display over"] = "Взять отображение на себя",

    ["Markers"] = "Метки",
    ["World markers"] = "Метки на земле",
    ["Clear markers"] = "Убрать метки",
    ["Clear world markers"] = "Убрать метки на земле",
    ["Ready check"] = "Проверка готовности",
    ["Pull timer"] = "Отсчёт до пула",
    ["Cancel the pull"] = "Отменить пул",
    ["Raid check"] = "Проверка рейда",
    ["Countdown"] = "Отсчёт",
    ["Pull"] = "Пул",
    ["Ready"] = "Готов",
    ["Clear"] = "Очистить",
    ["Ping"] = "Пинг",
    ["Attack"] = "Атака",
    ["Assist"] = "Помощь",
    ["On my way"] = "Иду",
    ["Warning"] = "Внимание",
    ["Your raid bar"] = "Ваша рейдовая панель",
    ["Every button"] = "Все кнопки",
    ["Click one to put it on your bar."] = "Нажмите, чтобы добавить на панель.",
    ["The bar"] = "Панель",
    ["Seconds"] = "Секунды",
    ["Right-click seconds"] = "Секунды по правой кнопке",
    ["Only for the leader"] = "Только для лидера",
    ["Not while in combat"] = "Не в бою",
    ["You need lead or assist for that."] = "Нужны права лидера или помощника.",
    ["You are not in a group."] = "Вы не в группе.",

    ["Name"] = "Имя",
    ["Item level"] = "Уровень предметов",
    ["Durability"] = "Прочность",
    ["Food"] = "Еда",
    ["Flask"] = "Настой",
    ["Rune"] = "Руна",
    ["Stamina"] = "Выносливость",
    ["Intellect"] = "Интеллект",
    ["Attack power"] = "Сила атаки",
    ["Versatility"] = "Универсальность",
    ["Mastery"] = "Искусность",
    ["Movement"] = "Скорость",
    ["Ask the group"] = "Спросить группу",
    ["No answer"] = "Нет ответа",
    ["Waiting for answers"] = "Ожидание ответов",
    ["Nobody has answered yet."] = "Пока никто не ответил.",
    ["%d of %d answered"] = "Ответили %d из %d",

    ["Invite"] = "Пригласить",
    ["Keywords"] = "Ключевые слова",
    ["Invite on a whisper"] = "Приглашать по шёпоту",
    ["Also on say and yell"] = "Также по «сказать» и «крикнуть»",
    ["Guild members only"] = "Только гильдия",
    ["Friends only"] = "Только друзья",
    ["Make it a raid at five"] = "Собрать рейд при пяти",
    ["Accept invites from friends"] = "Принимать приглашения друзей",
    ["Promote"] = "Повысить",
    ["Disband"] = "Распустить",
    ["Invite everyone back"] = "Пригласить всех обратно",
    ["Invite the guild"] = "Пригласить гильдию",
    ["Guild rank"] = "Ранг в гильдии",
    ["Any rank"] = "Любой ранг",
    ["Difficulty"] = "Сложность",
    ["Normal"] = "Обычный",
    ["Heroic"] = "Героический",
    ["Mythic"] = "Эпохальный",
    ["The group is empty."] = "Группа пуста.",
    ["One word per line."] = "По одному слову в строке.",
})

---------------------------------------------------------------------------
-- koKR - the vocabulary. See the header: the short labels are here, the
-- sentences are left in English on purpose rather than guessed at.
---------------------------------------------------------------------------
Register("koKR", {
    ["Edit mode"] = "편집 모드",
    ["Bars"] = "바",
    ["System"] = "시스템",
    ["Info"] = "정보",

    ["Cooldowns"] = "재사용 대기시간",
    ["Reminders"] = "알림",
    ["Death-log"] = "죽음 기록",
    ["Raid Bar"] = "공격대 바",
    ["Invites"] = "초대",
    ["Settings"] = "설정",
    ["Profiles"] = "프로필",
    ["Diagnostics"] = "진단",
    ["About"] = "정보",
    ["Changelog"] = "변경 내역",

    ["Close"] = "닫기",
    ["Cancel"] = "취소",
    ["Done"] = "완료",
    ["Show"] = "표시",
    ["Hide"] = "숨기기",
    ["Colour"] = "색상",
    ["Texture"] = "텍스처",
    ["Thickness"] = "두께",
    ["Scale"] = "크기",
    ["Opacity"] = "불투명도",
    ["Spacing"] = "간격",
    ["Rows"] = "행",
    ["Columns"] = "열",
    ["Icon size"] = "아이콘 크기",
    ["Look"] = "모양",
    ["Border"] = "테두리",
    ["Backdrop"] = "배경",
    ["Keys"] = "단축키",
    ["Language"] = "언어",
    ["Switch it on"] = "켜기",
    ["Modules"] = "모듈",
    ["Not now"] = "나중에",

    ["Markers"] = "표적 지정",
    ["World markers"] = "지역 표시",
    ["Ready check"] = "준비 확인",
    ["Pull timer"] = "풀 타이머",
    ["Raid check"] = "공격대 점검",
    ["Ready"] = "준비",
    ["Clear"] = "지우기",
    ["Ping"] = "핑",
    ["Attack"] = "공격",
    ["Assist"] = "지원",
    ["Warning"] = "경고",
    ["Seconds"] = "초",

    ["Name"] = "이름",
    ["Item level"] = "아이템 레벨",
    ["Durability"] = "내구도",
    ["Food"] = "음식",
    ["Flask"] = "영약",
    ["Rune"] = "룬",
    ["Stamina"] = "체력",
    ["Intellect"] = "지능",
    ["Attack power"] = "공격력",
    ["Versatility"] = "특화",
    ["Mastery"] = "특화",
    ["Movement"] = "이동 속도",
    ["No answer"] = "응답 없음",

    ["Invite"] = "초대",
    ["Keywords"] = "키워드",
    ["Promote"] = "승급",
    ["Disband"] = "해산",
    ["Difficulty"] = "난이도",
    ["Normal"] = "일반",
    ["Heroic"] = "영웅",
    ["Mythic"] = "신화",
})

---------------------------------------------------------------------------
-- zhCN
---------------------------------------------------------------------------
Register("zhCN", {
    ["Edit mode"] = "编辑模式",
    ["Bars"] = "条",
    ["System"] = "系统",
    ["Info"] = "信息",

    ["Cooldowns"] = "冷却",
    ["Reminders"] = "提醒",
    ["Death-log"] = "死亡记录",
    ["Raid Bar"] = "团队栏",
    ["Invites"] = "邀请",
    ["Settings"] = "设置",
    ["Profiles"] = "配置",
    ["Diagnostics"] = "诊断",
    ["About"] = "关于",
    ["Changelog"] = "更新日志",

    ["Close"] = "关闭",
    ["Cancel"] = "取消",
    ["Done"] = "完成",
    ["Show"] = "显示",
    ["Hide"] = "隐藏",
    ["Colour"] = "颜色",
    ["Texture"] = "材质",
    ["Thickness"] = "粗细",
    ["Scale"] = "缩放",
    ["Opacity"] = "不透明度",
    ["Spacing"] = "间距",
    ["Rows"] = "行",
    ["Columns"] = "列",
    ["Icon size"] = "图标大小",
    ["Look"] = "外观",
    ["Border"] = "边框",
    ["Backdrop"] = "背景",
    ["Keys"] = "按键",
    ["Language"] = "语言",
    ["Switch it on"] = "开启",
    ["Modules"] = "模块",
    ["Not now"] = "暂不",

    ["Markers"] = "标记",
    ["World markers"] = "场景标记",
    ["Ready check"] = "准备确认",
    ["Pull timer"] = "开怪倒计时",
    ["Raid check"] = "团队检查",
    ["Ready"] = "准备",
    ["Clear"] = "清除",
    ["Ping"] = "标点",
    ["Attack"] = "攻击",
    ["Assist"] = "协助",
    ["Warning"] = "警告",
    ["Seconds"] = "秒",

    ["Name"] = "名字",
    ["Item level"] = "装等",
    ["Durability"] = "耐久度",
    ["Food"] = "食物",
    ["Flask"] = "合剂",
    ["Rune"] = "符文",
    ["Stamina"] = "耐力",
    ["Intellect"] = "智力",
    ["Attack power"] = "攻击强度",
    ["Versatility"] = "全能",
    ["Mastery"] = "精通",
    ["Movement"] = "移动速度",
    ["No answer"] = "无回应",

    ["Invite"] = "邀请",
    ["Keywords"] = "关键词",
    ["Promote"] = "提升",
    ["Disband"] = "解散",
    ["Difficulty"] = "难度",
    ["Normal"] = "普通",
    ["Heroic"] = "英雄",
    ["Mythic"] = "史诗",
})

---------------------------------------------------------------------------
-- zhTW
---------------------------------------------------------------------------
Register("zhTW", {
    ["Edit mode"] = "編輯模式",
    ["Bars"] = "列",
    ["System"] = "系統",
    ["Info"] = "資訊",

    ["Cooldowns"] = "冷卻",
    ["Reminders"] = "提醒",
    ["Death-log"] = "死亡記錄",
    ["Raid Bar"] = "團隊列",
    ["Invites"] = "邀請",
    ["Settings"] = "設定",
    ["Profiles"] = "設定檔",
    ["Diagnostics"] = "診斷",
    ["About"] = "關於",
    ["Changelog"] = "更新記錄",

    ["Close"] = "關閉",
    ["Cancel"] = "取消",
    ["Done"] = "完成",
    ["Show"] = "顯示",
    ["Hide"] = "隱藏",
    ["Colour"] = "顏色",
    ["Texture"] = "材質",
    ["Thickness"] = "粗細",
    ["Scale"] = "縮放",
    ["Opacity"] = "不透明度",
    ["Spacing"] = "間距",
    ["Rows"] = "列數",
    ["Columns"] = "行數",
    ["Icon size"] = "圖示大小",
    ["Look"] = "外觀",
    ["Border"] = "邊框",
    ["Backdrop"] = "背景",
    ["Keys"] = "按鍵",
    ["Language"] = "語言",
    ["Switch it on"] = "開啟",
    ["Modules"] = "模組",
    ["Not now"] = "稍後",

    ["Markers"] = "標記",
    ["World markers"] = "場景標記",
    ["Ready check"] = "準備確認",
    ["Pull timer"] = "開怪倒數",
    ["Raid check"] = "團隊檢查",
    ["Ready"] = "準備",
    ["Clear"] = "清除",
    ["Ping"] = "標點",
    ["Attack"] = "攻擊",
    ["Assist"] = "協助",
    ["Warning"] = "警告",
    ["Seconds"] = "秒",

    ["Name"] = "名字",
    ["Item level"] = "裝等",
    ["Durability"] = "耐久度",
    ["Food"] = "食物",
    ["Flask"] = "合劑",
    ["Rune"] = "符文",
    ["Stamina"] = "耐力",
    ["Intellect"] = "智力",
    ["Attack power"] = "攻擊強度",
    ["Versatility"] = "臨機應變",
    ["Mastery"] = "精通",
    ["Movement"] = "移動速度",
    ["No answer"] = "無回應",

    ["Invite"] = "邀請",
    ["Keywords"] = "關鍵字",
    ["Promote"] = "晉升",
    ["Disband"] = "解散",
    ["Difficulty"] = "難度",
    ["Normal"] = "普通",
    ["Heroic"] = "英雄",
    ["Mythic"] = "史詩",
})
