---------------------------------------------------------------------------
-- Languages - every translation this addon ships.
--
-- ONE FILE, and it is a deliberate choice against the usual one-file-per-
-- language layout. Which language to use is read from the PROFILE, and the
-- profile is not open when these tables load - so a file that loads only when
-- it is the client's language could never honour somebody who chose a
-- different one, which is exactly the setting the owner asked for. Every
-- table is therefore resident, and one file is the honest way to say so.
--
-- WHAT THAT COSTS: measured with memcheck.lua, not guessed. See the handoff.
-- It is a table of strings; the whole file weighs less than one row of the
-- spell palette, and switching language then needs no second load.
--
-- enUS IS THE MASTER. Its keys are the list of strings this addon localises
-- at all. Every other table is held to it by the self test:
--   * a key that is not in enUS is a translation of something never asked for
--   * a key missing from a language shows as its English self, which is the
--     whole point of the key being the English sentence
--
-- SO AN UNFINISHED LANGUAGE IS NOT A BROKEN ONE. `/zs loca` prints how far
-- each has got, and `/zs loca deDE` prints exactly which lines are left.
--
-- HOW TO ADD A LINE: put the English sentence in the enUS table, wrap the
-- place it is drawn in L["..."], and the other ten tables are now one line
-- short - which the coverage number says out loud rather than hiding.
--
-- THE STATE OF THE NINE, honestly: German is complete. French, Spanish (both),
-- Italian, Portuguese and Russian carry the whole interface vocabulary and
-- the sentences. Korean and both Chinese carry the vocabulary - the short
-- labels that fill the window - and leave the longer sentences in English,
-- because a wrong sentence in a language nobody here reads cannot be spotted
-- and a missing one falls back to something correct.
---------------------------------------------------------------------------
local _, ns = ...

local Register = ns.Locale.Register

---------------------------------------------------------------------------
-- enUS - the master list
---------------------------------------------------------------------------
Register("enUS", {
    -- The rail
    ["Edit mode"] = true,
    ["Bars"] = true,
    ["M+ and raid stuff"] = true,
    ["System"] = true,
    ["Info"] = true,

    -- Page names. Also the module names, which is not a coincidence - a
    -- feature and its page are one thing with one name.
    ["Cooldowns"] = true,
    ["Co-Tanks"] = true,
    ["Reminders"] = true,
    ["External CD request"] = true,
    ["External CD answer"] = true,
    ["Death-log"] = true,
    ["Raid Bar"] = true,
    ["Invites"] = true,
    ["Settings"] = true,
    ["Profiles"] = true,
    ["Diagnostics"] = true,
    ["About"] = true,
    ["Changelog"] = true,

    -- Words that appear on more than one page
    ["Close"] = true,
    ["Cancel"] = true,
    ["Done"] = true,
    ["Show"] = true,
    ["Hide"] = true,
    ["Colour"] = true,
    ["Texture"] = true,
    ["Thickness"] = true,
    ["Scale"] = true,
    ["Opacity"] = true,
    ["Spacing"] = true,
    ["Rows"] = true,
    ["Columns"] = true,
    ["Runs"] = true,
    ["Across"] = true,
    ["Down"] = true,
    ["Icon size"] = true,
    ["Look"] = true,
    ["Border"] = true,
    ["Backdrop"] = true,
    ["Keys"] = true,
    ["Set keys"] = true,
    ["Test mode"] = true,
    ["Test mode: on"] = true,
    ["Only in a group"] = true,
    ["Only in combat"] = true,
    ["Only in an instance"] = true,
    ["Nothing yet"] = true,
    ["Switch it on"] = true,
    ["Language"] = true,
    ["Same as the game"] = true,
    ["Missing lines are shown in English."] = true,
    ["%s is switched off"] = true,
    ["Right-click clears every marker."] = true,
    ["Right-click takes this one away."] = true,
    ["Right-click cancels it."] = true,

    -- Welcome
    ["Not now"] = true,
    ["Let's go"] = true,
    ["Show the welcome screen"] = true,
    ["NEW"] = true,
    ["HIDDEN"] = true,
    ["Not on screen"] = true,

    -- Settings
    ["Modules"] = true,
    ["Every bar"] = true,
    ["This window"] = true,
    ["Ways in"] = true,
    ["Minimap button"] = true,
    ["Lock its position"] = true,
    ["Game menu entry"] = true,
    ["Bar text"] = true,
    ["Panel font"] = true,
    ["Take the display over"] = true,

    -- Sounds. THE FOUR EVENT NAMES ARE LOOKED UP THROUGH A VARIABLE -
    -- L[event.text] - so the scanner that checks every literal L["..."] is
    -- in this list CANNOT see them. They are here by hand, and anything
    -- added to ns.Sounds.EVENTS has to be added here by hand too.
    ["Sounds"] = true,
    ["When you ask for a cooldown"] = true,
    ["When somebody asks you"] = true,
    ["When a cooldown comes back"] = true,
    ["When a reminder appears"] = true,
    ["The list is every sound your other addons have registered - pick one "
        .. "and you will hear it. |cffffd100None|r is a real answer and "
        .. "silences that moment completely."] = true,
    ["|cffffd100Your addons have not registered any sounds yet.|r They come "
        .. "from whatever else you have installed - BigWigs, Northern Sky "
        .. "and WeakAuras all bring their own. |cffffd100/zs sounds|r lists "
        .. "what is there."] = true,
    ["Where sounds come from"] = true,
    ["%d sounds"] = true,
    ["Switch a pack off and its sounds leave the four lists above. Nothing "
        .. "here changes what you have already chosen - a sound you picked "
        .. "goes on playing even if its pack is switched off."] = true,
    ["A sound belongs to the SPELL, not to the place it sits in - so a "
        .. "cooldown you gave a sound of its own keeps it on the reminder "
        .. "and on the request panel alike."] = true,

    ---------------------------------------------------------------------
    -- Raid Bar
    ---------------------------------------------------------------------
    ["Markers"] = true,
    ["World markers"] = true,
    ["Clear markers"] = true,
    ["Clear world markers"] = true,
    ["Ready check"] = true,
    ["Pull timer"] = true,
    ["Cancel the pull"] = true,
    ["Raid check"] = true,
    ["Countdown"] = true,
    ["Pull"] = true,
    ["Ready"] = true,
    ["Clear"] = true,
    ["Ping"] = true,
    ["Attack"] = true,
    ["Assist"] = true,
    ["On my way"] = true,
    ["Warning"] = true,
    ["Your raid bar"] = true,
    ["Every button"] = true,
    ["Click one to put it on your bar."] = true,
    ["The bar"] = true,
    ["Seconds"] = true,
    ["Right-click seconds"] = true,
    ["Only for the leader"] = true,
    ["Not while in combat"] = true,
    ["You need lead or assist for that."] = true,
    ["You are not in a group."] = true,
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] = true,

    ---------------------------------------------------------------------
    -- Raid check window
    ---------------------------------------------------------------------
    ["Name"] = true,
    ["Item level"] = true,
    ["Durability"] = true,
    ["Food"] = true,
    ["Flask"] = true,
    ["Rune"] = true,
    ["Stamina"] = true,
    ["Intellect"] = true,
    ["Attack power"] = true,
    ["Versatility"] = true,
    ["Mastery"] = true,
    ["Movement"] = true,
    ["Ask the group"] = true,
    ["No answer"] = true,
    ["Waiting for answers"] = true,
    ["Nobody has answered yet."] = true,
    ["Only players running this addon can answer."] = true,
    ["%d of %d answered"] = true,

    ---------------------------------------------------------------------
    -- Invites
    ---------------------------------------------------------------------
    ["Invite"] = true,
    ["Keywords"] = true,
    ["Invite on a whisper"] = true,
    ["Also on say and yell"] = true,
    ["Guild members only"] = true,
    ["Friends only"] = true,
    ["Make it a raid at five"] = true,
    ["Accept invites from friends"] = true,
    ["Promote"] = true,
    ["Disband"] = true,
    ["Invite everyone back"] = true,
    ["Invite the guild"] = true,
    ["Guild rank"] = true,
    ["Any rank"] = true,
    ["Difficulty"] = true,
    ["Normal"] = true,
    ["Heroic"] = true,
    ["Mythic"] = true,
    ["Nobody to invite back."] = true,
    ["Invited %s."] = true,
    ["The group is empty."] = true,
    ["One word per line."] = true,

    ---------------------------------------------------------------------
    -- Sentences. Longer, and the ones a half-finished language leaves in
    -- English rather than getting wrong.
    ---------------------------------------------------------------------
    ["%d features in one addon. Switch off what you do not want."] = true,
    ["Off, the panel never appears."] = true,
    ["Pick a language, then reload."] = true,
    ["The window is drawn when it opens, so a new language reaches it after a |cffffd100/reload|r."] = true,
    ["Rows times columns is how many places there are."] = true,
    ["The gap between two icons."] = true,
    ["How big each button is on your screen."] = true,
    ["On your own there is nobody to ask, so it stays away."] = true,

    -- The page notes. Long sentences, and until 4.81.0 they were the
    -- last English left on three pages whose labels had been translated
    -- for months - which reads as an addon that gave up half way rather
    -- than one that is honestly unfinished.
    ["Pick from the list on the right. Right-click a place to empty it. To put the bar somewhere on your screen, open |cffffd100Edit mode|r at the top of the list on the left."] = 
        true,
    ["|cffffd100Marker, world marker and ping buttons are the game's own protected kind|r - the addon cannot press them for you, and the bar cannot be rearranged while you are in combat. Changes made in a fight appear the moment it ends."] = 
        true,
    ["Out in the world there is nothing to mark. Off, the bar is there whenever you are in a group."] = 
        true,
    ["The countdown is the game's own - the one Blizzard added for exactly this - so a boss mod picks it up by itself and everybody without one still sees the numbers. Right-click the Pull button on the bar to cancel it. The game refuses to start one in combat."] = 
        true,
    ["The first |cffffd100%d|r places on the bar can carry a key, set in the game's own key list under |cffffd100ZwoelfStuff|r. The key belongs to the PLACE, not to what is in it - so rearranging the bar moves what each key does."] = 
        true,
    ["Every icon on your bars, and how they look."] = true,
    ["Every piece of text on every bar, unless a bar has its own font."] = 
        true,
    ["The size of this window on your screen, not of anything on the bars. 100% is the size it was designed at; on a laptop 80% keeps all three columns in view. Takes effect as you change it."] = 
        true,
    ["Lets the scene behind the window through. It fades the whole window at once, on purpose: fading each layer separately makes the values multiply where they overlap and no surface keeps its colour. Judge it in a bright zone, not a dark one."] = 
        true,
    ["The window you are looking at - its labels, values and headings."] = 
        true,
    ["Left click opens this window, right click unlocks the panels for moving, and drag moves the button around the minimap edge."] =
        true,
    ["The button stays where you put it on the minimap edge, and dragging it does nothing until you unlock it again."] = 
        true,
    ["An entry in the game's own addon list."] = true,
    ["Everything on this page is |cffffd100off until you switch it on|r. Nothing here invites, promotes or accepts anything until the switch above it says so."] = 
        true,
    ["Somebody whispers one of the words above and the invitation goes out. A Battle.net whisper names an account rather than a character, which cannot be invited - so that one is answered with a line telling them to whisper the character instead."] = 
        true,
    ["For standing at a summoning stone and shouting. It listens to everybody in earshot, so it belongs to the ten minutes you are filling a group and not to the evening."] = 
        true,
    ["Off, the whole message has to BE the word - \"inv\" invites, \"inv please\" does not. On, the word is found anywhere in the sentence, which also finds it in \"I cannot inv you sorry\"."] = 
        true,
    ["Anybody else who whispers the word is told nothing happened - in your chat frame, not theirs."] = 
        true,
    ["Your friends list, and guild members count as friends here."] = true,
    ["The other direction: an invitation FROM a friend or a guild member is accepted for you and the box goes away. From anybody else the box stays, which is the point."] = 
        true,
    ["A party holds five. Without this the sixth invitation goes nowhere at all - which is the step everybody forgets. Not done in combat: the game refuses."] = 
        true,
    ["One name a line. They are made assistants when they join, and only while you are the leader of a raid. A raid where everybody is an assistant is a raid where anybody can pull."] = 
        true,
    ["A line in your own chat frame for every invitation sent. Worth keeping on: an invite tool that works silently is one you cannot tell from one that has stopped."] = 
        true,
    ["Everybody at that rank and above it. Rank numbers count downwards from the guild master, which is why this reads as \"and above\" rather than \"and below\"."] =
        true,

    -- The Cooldowns page, and the conflict check on the welcome window
    ["Who is managing your cooldowns"] = true,
    ["Nothing else on this account is managing them."] = true,
    ["Also managing cooldowns on this account: %s."] = true,
    ["%d other addons"] = true,
    ["Blizzard's Cooldown Manager"] = true,
    ["What it holds"] = true,
    ["Blizzard owns these frames and only one addon can hold them. Whichever loads second finds them already taken, and what you get on screen depends on the order they happened to load in - which is why this is a choice rather than something either addon can work around. Leave Cooldowns switched off to keep theirs, or switch theirs off and switch this on."] =
        true,
    ["Switch off %s"] = true,
    ["Do it and reload?"] = true,
    ["Switches that addon off, switches Cooldowns on here, and reloads. Nothing is deleted - it is the same tick as in the game's own addon list, and putting it back there puts everything back with it."] =
        true,
    ["Careful: %s would stop loading as well, because it needs that addon."] = true,
    ["Read from what each addon says about itself in its own description, so an addon that manages cooldowns without ever saying so is not found. Addons switched off for this character are not counted."] =
        true,
    ["Everything here comes from Blizzard's Cooldown Manager - it already knows the spells, binds the auras and has the timing, none of which an addon can do for itself on this patch. The reminders, the death log and the spell pickers all read it, and they go on doing so whether this module is on or off."] =
        true,
    ["%s is already managing your cooldowns. Two addons cannot hold the same cooldown frames - one of them loses, and which one depends on the order they loaded. Cooldowns is switched off below; turn it on to use ours instead, and switch theirs off in your addon list."] =
        true,
})

---------------------------------------------------------------------------
-- deDE
---------------------------------------------------------------------------
Register("deDE", {
    ["Edit mode"] = "Bearbeiten",
    ["Bars"] = "Leisten",
    ["M+ and raid stuff"] = "M+ und Schlachtzug",
    ["System"] = "System",
    ["Info"] = "Info",

    ["Cooldowns"] = "Abklingzeiten",
    ["Co-Tanks"] = "Mit-Tanks",
    ["Reminders"] = "Erinnerungen",
    ["External CD request"] = "Externen CD anfragen",
    ["External CD answer"] = "Externen CD geben",
    ["Death-log"] = "Todesprotokoll",
    ["Raid Bar"] = "Schlachtzugsleiste",
    ["Invites"] = "Einladungen",
    ["Settings"] = "Einstellungen",
    ["Profiles"] = "Profile",
    ["Diagnostics"] = "Diagnose",
    ["About"] = "Ãœber",
    ["Changelog"] = "Ã„nderungen",

    ["Close"] = "SchlieÃŸen",
    ["Cancel"] = "Abbrechen",
    ["Done"] = "Fertig",
    ["Show"] = "Anzeigen",
    ["Hide"] = "Ausblenden",
    ["Colour"] = "Farbe",
    ["Texture"] = "Textur",
    ["Thickness"] = "StÃ¤rke",
    ["Scale"] = "Skalierung",
    ["Opacity"] = "Deckkraft",
    ["Spacing"] = "Abstand",
    ["Rows"] = "Zeilen",
    ["Columns"] = "Spalten",
    ["Runs"] = "Verlauf",
    ["Across"] = "Waagerecht",
    ["Down"] = "Senkrecht",
    ["Icon size"] = "SymbolgrÃ¶ÃŸe",
    ["Look"] = "Aussehen",
    ["Border"] = "Rahmen",
    ["Backdrop"] = "Hintergrund",
    ["Keys"] = "Tasten",
    ["Set keys"] = "Tasten belegen",
    ["Test mode"] = "Testmodus",
    ["Test mode: on"] = "Testmodus: an",
    ["Only in a group"] = "Nur in einer Gruppe",
    ["Only in combat"] = "Nur im Kampf",
    ["Only in an instance"] = "Nur in einer Instanz",
    ["Nothing yet"] = "Noch nichts",
    ["Switch it on"] = "Einschalten",
    ["Language"] = "Sprache",
    ["Same as the game"] = "Wie das Spiel",
    ["Missing lines are shown in English."] = "Fehlende Zeilen erscheinen auf Englisch.",
    ["%s is switched off"] = "%s ist ausgeschaltet",
    ["Right-click clears every marker."] = "Rechtsklick entfernt alle Zeichen.",
    ["Right-click takes this one away."] = "Rechtsklick nimmt diese wieder weg.",
    ["Right-click cancels it."] = "Rechtsklick bricht ab.",

    ["Not now"] = "SpÃ¤ter",
    ["Let's go"] = "Los geht's",
    ["Show the welcome screen"] = "Willkommensfenster zeigen",
    ["NEW"] = "NEU",
    ["HIDDEN"] = "VERSTECKT",
    ["Not on screen"] = "Nicht auf dem Bildschirm",

    ["Modules"] = "Module",
    ["Every bar"] = "Alle Leisten",
    ["This window"] = "Dieses Fenster",
    ["Ways in"] = "ZugÃ¤nge",
    ["Minimap button"] = "Minikarten-Knopf",
    ["Lock its position"] = "Position sperren",
    ["Game menu entry"] = "Eintrag im SpielmenÃ¼",
    ["Bar text"] = "Leistentext",
    ["Panel font"] = "Schrift der Fenster",
    ["Take the display over"] = "Anzeige Ã¼bernehmen",

    ["Sounds"] = "TÃ¶ne",
    ["When you ask for a cooldown"] = "Wenn du einen Cooldown anforderst",
    ["When somebody asks you"] = "Wenn dich jemand fragt",
    ["When a cooldown comes back"] = "Wenn ein Cooldown wieder da ist",
    ["When a reminder appears"] = "Wenn eine Erinnerung erscheint",
    ["The list is every sound your other addons have registered - pick one "
        .. "and you will hear it. |cffffd100None|r is a real answer and "
        .. "silences that moment completely."] =
        "Die Liste enthÃ¤lt jeden Ton, den deine anderen Addons angemeldet "
        .. "haben - wÃ¤hle einen und du hÃ¶rst ihn sofort. |cffffd100None|r "
        .. "ist eine echte Antwort und macht diesen Moment ganz stumm.",
    ["|cffffd100Your addons have not registered any sounds yet.|r They come "
        .. "from whatever else you have installed - BigWigs, Northern Sky "
        .. "and WeakAuras all bring their own. |cffffd100/zs sounds|r lists "
        .. "what is there."] =
        "|cffffd100Deine Addons haben noch keine TÃ¶ne angemeldet.|r "
        .. "Sie kommen aus allem anderen, was du installiert hast - BigWigs, "
        .. "Northern Sky und WeakAuras bringen eigene mit. "
        .. "|cffffd100/zs sounds|r zeigt, was da ist.",
    ["Where sounds come from"] = "Woher die TÃ¶ne kommen",
    ["%d sounds"] = "%d TÃ¶ne",
    ["Switch a pack off and its sounds leave the four lists above. Nothing "
        .. "here changes what you have already chosen - a sound you picked "
        .. "goes on playing even if its pack is switched off."] =
        "Schalte ein Paket ab und seine TÃ¶ne verschwinden aus den vier "
        .. "Listen oben. An deiner Auswahl Ã¤ndert das nichts - ein bereits "
        .. "gewÃ¤hlter Ton spielt weiter, auch wenn sein Paket aus ist.",
    ["A sound belongs to the SPELL, not to the place it sits in - so a "
        .. "cooldown you gave a sound of its own keeps it on the reminder "
        .. "and on the request panel alike."] =
        "Ein Ton gehÃ¶rt zum ZAUBER, nicht zu seinem Platz - ein Cooldown "
        .. "mit eigenem Ton behÃ¤lt ihn also auf der Erinnerung wie "
        .. "im Anfrage-Fenster.",

    ["Markers"] = "Zeichen",
    ["World markers"] = "Weltmarkierungen",
    ["Clear markers"] = "Zeichen entfernen",
    ["Clear world markers"] = "Weltmarkierungen entfernen",
    ["Ready check"] = "BereitschaftsprÃ¼fung",
    ["Pull timer"] = "Pull-Timer",
    ["Cancel the pull"] = "Pull abbrechen",
    ["Raid check"] = "Raid-Check",
    ["Countdown"] = "Countdown",
    ["Pull"] = "Pull",
    ["Ready"] = "Bereit",
    ["Clear"] = "LÃ¶schen",
    ["Ping"] = "Ping",
    ["Attack"] = "Angreifen",
    ["Assist"] = "Helfen",
    ["On my way"] = "Bin unterwegs",
    ["Warning"] = "Achtung",
    ["Your raid bar"] = "Deine Schlachtzugsleiste",
    ["Every button"] = "Alle KnÃ¶pfe",
    ["Click one to put it on your bar."] = "Klick einen an, um ihn auf die Leiste zu legen.",
    ["The bar"] = "Die Leiste",
    ["Seconds"] = "Sekunden",
    ["Right-click seconds"] = "Sekunden bei Rechtsklick",
    ["Only for the leader"] = "Nur fÃ¼r den AnfÃ¼hrer",
    ["Not while in combat"] = "Nicht im Kampf",
    ["You need lead or assist for that."] = "DafÃ¼r brauchst du AnfÃ¼hrer oder Assistent.",
    ["You are not in a group."] = "Du bist in keiner Gruppe.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "Die Leiste kann im Kampf nicht neu gebaut werden. Es passiert, sobald du ihn verlÃ¤sst.",

    ["Name"] = "Name",
    ["Item level"] = "Gegenstandsstufe",
    ["Durability"] = "Haltbarkeit",
    ["Food"] = "Essen",
    ["Flask"] = "FlÃ¤schchen",
    ["Rune"] = "Rune",
    ["Stamina"] = "Ausdauer",
    ["Intellect"] = "Intelligenz",
    ["Attack power"] = "Angriffskraft",
    ["Versatility"] = "Vielseitigkeit",
    ["Mastery"] = "Meisterschaft",
    ["Movement"] = "Tempo",
    ["Ask the group"] = "Gruppe fragen",
    ["No answer"] = "Keine Antwort",
    ["Waiting for answers"] = "Warte auf Antworten",
    ["Nobody has answered yet."] = "Noch hat niemand geantwortet.",
    ["Only players running this addon can answer."] =
        "Antworten kÃ¶nnen nur Spieler, die dieses Addon benutzen.",
    ["%d of %d answered"] = "%d von %d haben geantwortet",

    ["Invite"] = "Einladen",
    ["Keywords"] = "SchlÃ¼sselwÃ¶rter",
    ["Invite on a whisper"] = "Bei FlÃ¼stern einladen",
    ["Also on say and yell"] = "Auch bei Sagen und Rufen",
    ["Guild members only"] = "Nur Gildenmitglieder",
    ["Friends only"] = "Nur Freunde",
    ["Make it a raid at five"] = "Bei fÃ¼nf in Schlachtzug umwandeln",
    ["Accept invites from friends"] = "Einladungen von Freunden annehmen",
    ["Promote"] = "BefÃ¶rdern",
    ["Disband"] = "AuflÃ¶sen",
    ["Invite everyone back"] = "Alle zurÃ¼ckholen",
    ["Invite the guild"] = "Gilde einladen",
    ["Guild rank"] = "Gildenrang",
    ["Any rank"] = "Jeder Rang",
    ["Difficulty"] = "Schwierigkeit",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroisch",
    ["Mythic"] = "Mythisch",
    ["Nobody to invite back."] = "Niemanden zurÃ¼ckzuholen.",
    ["Invited %s."] = "%s eingeladen.",
    ["The group is empty."] = "Die Gruppe ist leer.",
    ["One word per line."] = "Ein Wort pro Zeile.",

    ["%d features in one addon. Switch off what you do not want."] =
        "%d Funktionen in einem Addon. Schalte ab, was du nicht willst.",
    ["Off, the panel never appears."] = "Aus erscheint das Fenster nie.",
    ["Pick a language, then reload."] = "Sprache wÃ¤hlen, dann neu laden.",
    ["The window is drawn when it opens, so a new language reaches it after a |cffffd100/reload|r."] =
        "Das Fenster wird beim Ã–ffnen gezeichnet - eine neue Sprache kommt also erst nach einem |cffffd100/reload|r an.",
    ["Rows times columns is how many places there are."] =
        "Zeilen mal Spalten ergibt die Anzahl der PlÃ¤tze.",
    ["The gap between two icons."] = "Der Abstand zwischen zwei Symbolen.",
    ["How big each button is on your screen."] =
        "Wie groÃŸ jeder Knopf auf deinem Bildschirm ist.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Allein gibt es niemanden zu fragen, also bleibt sie weg.",

    -- The page notes. Long sentences, and until 4.81.0 they were the
    -- last English left on three pages whose labels had been translated
    -- for months - which reads as an addon that gave up half way rather
    -- than one that is honestly unfinished.
    ["Pick from the list on the right. Right-click a place to empty it. To put the bar somewhere on your screen, open |cffffd100Edit mode|r at the top of the list on the left."] = 
        "WÃ¤hle rechts aus der Liste. Rechtsklick auf einen Platz leert ihn. Um die Leiste auf dem Bildschirm zu platzieren, Ã¶ffne links oben |cffffd100Bearbeiten|r.",
    ["|cffffd100Marker, world marker and ping buttons are the game's own protected kind|r - the addon cannot press them for you, and the bar cannot be rearranged while you are in combat. Changes made in a fight appear the moment it ends."] = 
        "|cffffd100Markierungen, Weltmarkierungen und Pings sind geschÃ¼tzte KnÃ¶pfe des Spiels|r - das Addon kann sie nicht fÃ¼r dich drÃ¼cken, und die Leiste lÃ¤sst sich im Kampf nicht umbauen. Ã„nderungen im Kampf erscheinen, sobald er vorbei ist.",
    ["Out in the world there is nothing to mark. Off, the bar is there whenever you are in a group."] = 
        "DrauÃŸen in der Welt gibt es nichts zu markieren. Aus, ist die Leiste da, sobald du in einer Gruppe bist.",
    ["The countdown is the game's own - the one Blizzard added for exactly this - so a boss mod picks it up by itself and everybody without one still sees the numbers. Right-click the Pull button on the bar to cancel it. The game refuses to start one in combat."] = 
        "Der Countdown ist der des Spiels - der, den Blizzard genau dafÃ¼r eingebaut hat - also greift ihn ein Boss-Mod von selbst auf, und wer keinen hat, sieht die Zahlen trotzdem. Rechtsklick auf den Pull-Knopf bricht ihn ab. Im Kampf startet das Spiel keinen.",
    ["The first |cffffd100%d|r places on the bar can carry a key, set in the game's own key list under |cffffd100ZwoelfStuff|r. The key belongs to the PLACE, not to what is in it - so rearranging the bar moves what each key does."] = 
        "Die ersten |cffffd100%d|r PlÃ¤tze der Leiste kÃ¶nnen eine Taste tragen, gesetzt in der Tastenbelegung des Spiels unter |cffffd100ZwoelfStuff|r. Die Taste gehÃ¶rt zum PLATZ, nicht zu dem, was darauf liegt - wer die Leiste umbaut, verschiebt also auch, was jede Taste tut.",
    ["Every icon on your bars, and how they look."] = 
        "Jedes Symbol auf deinen Leisten und wie sie aussehen.",
    ["Every piece of text on every bar, unless a bar has its own font."] = 
        "Jeder Text auf jeder Leiste, auÃŸer eine Leiste hat ihre eigene Schrift.",
    ["The size of this window on your screen, not of anything on the bars. 100% is the size it was designed at; on a laptop 80% keeps all three columns in view. Takes effect as you change it."] = 
        "Die GrÃ¶ÃŸe dieses Fensters auf deinem Bildschirm, nicht die von etwas auf den Leisten. 100% ist die GrÃ¶ÃŸe, fÃ¼r die es gestaltet wurde; auf einem Laptop hÃ¤lt 80% alle drei Spalten im Blick. Wirkt sofort beim Ziehen.",
    ["Lets the scene behind the window through. It fades the whole window at once, on purpose: fading each layer separately makes the values multiply where they overlap and no surface keeps its colour. Judge it in a bright zone, not a dark one."] = 
        "LÃ¤sst die Szene hinter dem Fenster durch. Es blendet das ganze Fenster auf einmal ab, mit Absicht: blendet man jede Ebene einzeln, multiplizieren sich die Werte an den Ãœberlappungen und keine FlÃ¤che behÃ¤lt ihre Farbe. Beurteile es in einer hellen Gegend, nicht in einer dunklen.",
    ["The window you are looking at - its labels, values and headings."] = 
        "Das Fenster, das du gerade ansiehst - seine Beschriftungen, Werte und Ãœberschriften.",
    ["Left click opens this window, right click unlocks the panels for moving, and drag moves the button around the minimap edge."] =
        "Linksklick Ã¶ffnet dieses Fenster, Rechtsklick gibt die Panels zum Verschieben frei, und Ziehen bewegt den Knopf am Rand der Minikarte.",
    ["The button stays where you put it on the minimap edge, and dragging it does nothing until you unlock it again."] = 
        "Der Knopf bleibt, wo du ihn am Rand der Minikarte abgelegt hast, und Ziehen tut nichts, bis du ihn wieder freigibst.",
    ["An entry in the game's own addon list."] = 
        "Ein Eintrag in der Addon-Liste des Spiels.",
    ["Everything on this page is |cffffd100off until you switch it on|r. Nothing here invites, promotes or accepts anything until the switch above it says so."] = 
        "Alles auf dieser Seite ist |cffffd100aus, bis du es einschaltest|r. Nichts hier lÃ¤dt ein, befÃ¶rdert oder nimmt an, bevor der Schalter darÃ¼ber es sagt.",
    ["Somebody whispers one of the words above and the invitation goes out. A Battle.net whisper names an account rather than a character, which cannot be invited - so that one is answered with a line telling them to whisper the character instead."] = 
        "Jemand flÃ¼stert eines der WÃ¶rter oben, und die Einladung geht raus. Ein Battle.net-FlÃ¼stern nennt ein Konto statt eines Charakters, und ein Konto kann man nicht einladen - darauf kommt deshalb eine Zeile zurÃ¼ck, die um ein FlÃ¼stern an den Charakter bittet.",
    ["For standing at a summoning stone and shouting. It listens to everybody in earshot, so it belongs to the ten minutes you are filling a group and not to the evening."] = 
        "FÃ¼rs Rufen am BeschwÃ¶rungsstein. Es hÃ¶rt jedem in HÃ¶rweite zu, gehÃ¶rt also zu den zehn Minuten, in denen du eine Gruppe fÃ¼llst, und nicht zum ganzen Abend.",
    ["Off, the whole message has to BE the word - \"inv\" invites, \"inv please\" does not. On, the word is found anywhere in the sentence, which also finds it in \"I cannot inv you sorry\"."] = 
        "Aus, muss die ganze Nachricht das Wort SEIN - \"inv\" lÃ¤dt ein, \"inv bitte\" nicht. An, wird das Wort Ã¼berall im Satz gefunden, also auch in \"kann dich leider nicht inv\".",
    ["Anybody else who whispers the word is told nothing happened - in your chat frame, not theirs."] = 
        "Wenn sonst jemand das Wort flÃ¼stert, passiert nichts - und das steht in deinem Chatfenster, nicht in seinem.",
    ["Your friends list, and guild members count as friends here."] = 
        "Deine Freundesliste, und Gildenmitglieder zÃ¤hlen hier als Freunde.",
    ["The other direction: an invitation FROM a friend or a guild member is accepted for you and the box goes away. From anybody else the box stays, which is the point."] = 
        "Die andere Richtung: eine Einladung VON einem Freund oder Gildenmitglied wird fÃ¼r dich angenommen und das Fenster verschwindet. Von allen anderen bleibt es stehen, und genau darum geht es.",
    ["A party holds five. Without this the sixth invitation goes nowhere at all - which is the step everybody forgets. Not done in combat: the game refuses."] = 
        "Eine Gruppe fasst fÃ¼nf. Ohne das geht die sechste Einladung schlicht ins Leere - der Schritt, den alle vergessen. Im Kampf passiert es nicht: das Spiel lehnt ab.",
    ["One name a line. They are made assistants when they join, and only while you are the leader of a raid. A raid where everybody is an assistant is a raid where anybody can pull."] = 
        "Ein Name pro Zeile. Sie werden beim Beitreten zu Assistenten ernannt, und nur solange du AnfÃ¼hrer eines Schlachtzugs bist. Ein Schlachtzug, in dem jeder Assistent ist, ist einer, in dem jeder pullen kann.",
    ["A line in your own chat frame for every invitation sent. Worth keeping on: an invite tool that works silently is one you cannot tell from one that has stopped."] = 
        "Eine Zeile in deinem eigenen Chatfenster fÃ¼r jede verschickte Einladung. Lohnt sich anzulassen: ein Einladungswerkzeug, das stumm arbeitet, ist von einem, das stehengeblieben ist, nicht zu unterscheiden.",
    ["Everybody at that rank and above it. Rank numbers count downwards from the guild master, which is why this reads as \"and above\" rather than \"and below\"."] = 
        "Jeder in diesem Rang und darÃ¼ber. Rangnummern zÃ¤hlen vom Gildenmeister abwÃ¤rts, deshalb heiÃŸt es hier \"und darÃ¼ber\" und nicht \"und darunter\".",

    -- Die Cooldowns-Seite und die KonfliktprÃ¼fung im Willkommensfenster
    ["Who is managing your cooldowns"] = "Wer deine Cooldowns verwaltet",
    ["Nothing else on this account is managing them."] =
        "Sonst verwaltet sie auf diesem Account niemand.",
    ["Also managing cooldowns on this account: %s."] =
        "Verwalten auf diesem Account ebenfalls Cooldowns: %s.",
    ["%d other addons"] = "%d andere Addons",
    ["Blizzard's Cooldown Manager"] = "Blizzards Cooldown-Manager",
    ["What it holds"] = "Was er hÃ¤lt",
    ["Blizzard owns these frames and only one addon can hold them. Whichever loads second finds them already taken, and what you get on screen depends on the order they happened to load in - which is why this is a choice rather than something either addon can work around. Leave Cooldowns switched off to keep theirs, or switch theirs off and switch this on."] =
        "Diese Frames gehÃ¶ren Blizzard, und nur ein Addon kann sie halten. Wer als Zweiter lÃ¤dt, findet sie besetzt vor, und was auf dem Bildschirm landet, hÃ¤ngt an der Reihenfolge, in der zufÃ¤llig geladen wurde - deshalb ist das eine Entscheidung und nichts, was eines der beiden Addons umgehen kÃ¶nnte. Lass Cooldowns aus, um bei deren LÃ¶sung zu bleiben, oder schalte deren Addon ab und das hier an.",
    ["Switch off %s"] = "%s abschalten",
    ["Do it and reload?"] = "Wirklich, mit Neuladen?",
    ["Switches that addon off, switches Cooldowns on here, and reloads. Nothing is deleted - it is the same tick as in the game's own addon list, and putting it back there puts everything back with it."] =
        "Schaltet dieses Addon ab, schaltet Cooldowns hier an und lÃ¤dt neu. Es wird nichts gelÃ¶scht - es ist dasselbe HÃ¤kchen wie in der Addon-Liste des Spiels, und wer es dort zurÃ¼cksetzt, bekommt alles wieder.",
    ["Careful: %s would stop loading as well, because it needs that addon."] =
        "Achtung: %s wÃ¼rde ebenfalls nicht mehr laden, weil es dieses Addon braucht.",
    ["Read from what each addon says about itself in its own description, so an addon that manages cooldowns without ever saying so is not found. Addons switched off for this character are not counted."] =
        "Gelesen aus dem, was jedes Addon in seiner eigenen Beschreibung Ã¼ber sich sagt - ein Addon, das Cooldowns verwaltet, ohne das je zu erwÃ¤hnen, wird also nicht gefunden. FÃ¼r diesen Charakter abgeschaltete Addons zÃ¤hlen nicht mit.",
    ["Everything here comes from Blizzard's Cooldown Manager - it already knows the spells, binds the auras and has the timing, none of which an addon can do for itself on this patch. The reminders, the death log and the spell pickers all read it, and they go on doing so whether this module is on or off."] =
        "Alles hier kommt aus Blizzards Cooldown-Manager - er kennt die Zauber bereits, bindet die Auren und hat das Timing, und nichts davon kann ein Addon auf diesem Patch selbst leisten. Die Erinnerungen, das Todesprotokoll und die Zauberlisten lesen ihn alle, und sie tun das weiter, ob dieses Modul an ist oder aus.",
    ["%s is already managing your cooldowns. Two addons cannot hold the same cooldown frames - one of them loses, and which one depends on the order they loaded. Cooldowns is switched off below; turn it on to use ours instead, and switch theirs off in your addon list."] =
        "%s verwaltet deine Cooldowns bereits. Zwei Addons kÃ¶nnen dieselben Cooldown-Frames nicht gemeinsam halten - eines verliert, und welches, hÃ¤ngt an der Ladereihenfolge. Cooldowns ist unten ausgeschaltet; schalte es an, um stattdessen unseres zu nutzen, und deren Addon in deiner Addon-Liste ab.",
})

---------------------------------------------------------------------------
-- frFR
---------------------------------------------------------------------------
Register("frFR", {
    ["Edit mode"] = "Mode Ã©dition",
    ["Bars"] = "Barres",
    ["M+ and raid stuff"] = "M+ et raid",
    ["System"] = "SystÃ¨me",
    ["Info"] = "Infos",

    ["Cooldowns"] = "Temps de recharge",
    ["Co-Tanks"] = "Autres tanks",
    ["Reminders"] = "Rappels",
    ["External CD request"] = "Demander un externe",
    ["External CD answer"] = "Donner un externe",
    ["Death-log"] = "Journal des morts",
    ["Raid Bar"] = "Barre de raid",
    ["Invites"] = "Invitations",
    ["Settings"] = "RÃ©glages",
    ["Profiles"] = "Profils",
    ["Diagnostics"] = "Diagnostic",
    ["About"] = "Ã€ propos",
    ["Changelog"] = "NouveautÃ©s",

    ["Close"] = "Fermer",
    ["Cancel"] = "Annuler",
    ["Done"] = "TerminÃ©",
    ["Show"] = "Afficher",
    ["Hide"] = "Masquer",
    ["Colour"] = "Couleur",
    ["Texture"] = "Texture",
    ["Thickness"] = "Ã‰paisseur",
    ["Scale"] = "Ã‰chelle",
    ["Opacity"] = "OpacitÃ©",
    ["Spacing"] = "Espacement",
    ["Rows"] = "Lignes",
    ["Columns"] = "Colonnes",
    ["Runs"] = "Sens",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Taille des icÃ´nes",
    ["Look"] = "Apparence",
    ["Border"] = "Bordure",
    ["Backdrop"] = "Fond",
    ["Keys"] = "Touches",
    ["Set keys"] = "Assigner les touches",
    ["Test mode"] = "Mode test",
    ["Test mode: on"] = "Mode test : actif",
    ["Only in a group"] = "Seulement en groupe",
    ["Only in combat"] = "Seulement en combat",
    ["Only in an instance"] = "Seulement en instance",
    ["Nothing yet"] = "Rien pour l'instant",
    ["Switch it on"] = "Activer",
    ["Language"] = "Langue",
    ["Same as the game"] = "Comme le jeu",
    ["Missing lines are shown in English."] = "Les lignes manquantes restent en anglais.",
    ["%s is switched off"] = "%s est dÃ©sactivÃ©",
    ["Right-click clears every marker."] = "Le clic droit efface tous les symboles.",
    ["Right-click takes this one away."] = "Le clic droit retire celle-ci.",
    ["Right-click cancels it."] = "Le clic droit annule.",

    ["Not now"] = "Plus tard",
    ["Let's go"] = "C'est parti",
    ["Show the welcome screen"] = "Afficher l'accueil",
    ["NEW"] = "NOUVEAU",
    ["HIDDEN"] = "MASQUÃ‰",
    ["Not on screen"] = "Pas Ã  l'Ã©cran",

    ["Modules"] = "Modules",
    ["Every bar"] = "Toutes les barres",
    ["This window"] = "Cette fenÃªtre",
    ["Ways in"] = "AccÃ¨s",
    ["Minimap button"] = "Bouton de minicarte",
    ["Lock its position"] = "Verrouiller sa position",
    ["Game menu entry"] = "EntrÃ©e dans le menu du jeu",
    ["Bar text"] = "Texte des barres",
    ["Panel font"] = "Police des fenÃªtres",
    ["Take the display over"] = "Reprendre l'affichage",

    ["Markers"] = "Symboles",
    ["World markers"] = "Balises de zone",
    ["Clear markers"] = "Effacer les symboles",
    ["Clear world markers"] = "Effacer les balises",
    ["Ready check"] = "VÃ©rification",
    ["Pull timer"] = "Compte Ã  rebours",
    ["Cancel the pull"] = "Annuler le pull",
    ["Raid check"] = "ContrÃ´le du raid",
    ["Countdown"] = "Compte Ã  rebours",
    ["Pull"] = "Pull",
    ["Ready"] = "PrÃªt",
    ["Clear"] = "Effacer",
    ["Ping"] = "Ping",
    ["Attack"] = "Attaquer",
    ["Assist"] = "Aider",
    ["On my way"] = "J'arrive",
    ["Warning"] = "Attention",
    ["Your raid bar"] = "Votre barre de raid",
    ["Every button"] = "Tous les boutons",
    ["Click one to put it on your bar."] = "Cliquez pour l'ajouter Ã  votre barre.",
    ["The bar"] = "La barre",
    ["Seconds"] = "Secondes",
    ["Right-click seconds"] = "Secondes au clic droit",
    ["Only for the leader"] = "Seulement pour le chef",
    ["Not while in combat"] = "Pas en combat",
    ["You need lead or assist for that."] = "Il faut Ãªtre chef ou assistant.",
    ["You are not in a group."] = "Vous n'Ãªtes pas en groupe.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "La barre ne peut pas Ãªtre reconstruite en combat. Ce sera fait dÃ¨s que vous en sortirez.",

    ["Name"] = "Nom",
    ["Item level"] = "Niveau d'objet",
    ["Durability"] = "DurabilitÃ©",
    ["Food"] = "Nourriture",
    ["Flask"] = "Flacon",
    ["Rune"] = "Rune",
    ["Stamina"] = "Endurance",
    ["Intellect"] = "Intelligence",
    ["Attack power"] = "Puissance d'attaque",
    ["Versatility"] = "Polyvalence",
    ["Mastery"] = "MaÃ®trise",
    ["Movement"] = "DÃ©placement",
    ["Ask the group"] = "Demander au groupe",
    ["No answer"] = "Pas de rÃ©ponse",
    ["Waiting for answers"] = "En attente de rÃ©ponses",
    ["Nobody has answered yet."] = "Personne n'a encore rÃ©pondu.",
    ["Only players running this addon can answer."] =
        "Seuls les joueurs qui utilisent cet addon peuvent rÃ©pondre.",
    ["%d of %d answered"] = "%d sur %d ont rÃ©pondu",

    ["Invite"] = "Inviter",
    ["Keywords"] = "Mots-clÃ©s",
    ["Invite on a whisper"] = "Inviter sur chuchotement",
    ["Also on say and yell"] = "Aussi sur dire et crier",
    ["Guild members only"] = "Guilde seulement",
    ["Friends only"] = "Amis seulement",
    ["Make it a raid at five"] = "Passer en raid Ã  cinq",
    ["Accept invites from friends"] = "Accepter les invitations des amis",
    ["Promote"] = "Promouvoir",
    ["Disband"] = "Dissoudre",
    ["Invite everyone back"] = "RÃ©inviter tout le monde",
    ["Invite the guild"] = "Inviter la guilde",
    ["Guild rank"] = "Rang de guilde",
    ["Any rank"] = "Tous les rangs",
    ["Difficulty"] = "DifficultÃ©",
    ["Normal"] = "Normal",
    ["Heroic"] = "HÃ©roÃ¯que",
    ["Mythic"] = "Mythique",
    ["Nobody to invite back."] = "Personne Ã  rÃ©inviter.",
    ["Invited %s."] = "%s invitÃ©.",
    ["The group is empty."] = "Le groupe est vide.",
    ["One word per line."] = "Un mot par ligne.",

    ["%d features in one addon. Switch off what you do not want."] =
        "%d fonctions dans un addon. DÃ©sactivez ce que vous ne voulez pas.",
    ["Off, the panel never appears."] = "DÃ©sactivÃ©, la fenÃªtre n'apparaÃ®t jamais.",
    ["Pick a language, then reload."] = "Choisissez une langue, puis rechargez.",
    ["Rows times columns is how many places there are."] =
        "Lignes fois colonnes donne le nombre de places.",
    ["The gap between two icons."] = "L'Ã©cart entre deux icÃ´nes.",
    ["How big each button is on your screen."] =
        "La taille de chaque bouton Ã  l'Ã©cran.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Seul, il n'y a personne Ã  qui demander : elle reste cachÃ©e.",
})

---------------------------------------------------------------------------
-- esES
---------------------------------------------------------------------------
Register("esES", {
    ["Edit mode"] = "Modo ediciÃ³n",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ y banda",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Reutilizaciones",
    ["Co-Tanks"] = "Otros tanques",
    ["Reminders"] = "Recordatorios",
    ["External CD request"] = "Pedir un externo",
    ["External CD answer"] = "Dar un externo",
    ["Death-log"] = "Registro de muertes",
    ["Raid Bar"] = "Barra de banda",
    ["Invites"] = "Invitaciones",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfiles",
    ["Diagnostics"] = "DiagnÃ³stico",
    ["About"] = "Acerca de",
    ["Changelog"] = "Novedades",

    ["Close"] = "Cerrar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Hecho",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Color",
    ["Texture"] = "Textura",
    ["Thickness"] = "Grosor",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidad",
    ["Spacing"] = "Espaciado",
    ["Rows"] = "Filas",
    ["Columns"] = "Columnas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "TamaÃ±o de icono",
    ["Look"] = "Aspecto",
    ["Border"] = "Borde",
    ["Backdrop"] = "Fondo",
    ["Keys"] = "Teclas",
    ["Set keys"] = "Asignar teclas",
    ["Test mode"] = "Modo prueba",
    ["Test mode: on"] = "Modo prueba: activo",
    ["Only in a group"] = "Solo en grupo",
    ["Only in combat"] = "Solo en combate",
    ["Only in an instance"] = "Solo en una instancia",
    ["Nothing yet"] = "Nada todavÃ­a",
    ["Switch it on"] = "Activar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Como el juego",
    ["Missing lines are shown in English."] = "Las lÃ­neas que faltan salen en inglÃ©s.",
    ["%s is switched off"] = "%s estÃ¡ desactivado",
    ["Right-click clears every marker."] = "El clic derecho quita todas las marcas.",
    ["Right-click takes this one away."] = "El clic derecho quita esta.",
    ["Right-click cancels it."] = "El clic derecho lo cancela.",

    ["Not now"] = "Ahora no",
    ["Let's go"] = "Adelante",
    ["Show the welcome screen"] = "Mostrar la bienvenida",
    ["NEW"] = "NUEVO",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "No estÃ¡ en pantalla",

    ["Modules"] = "MÃ³dulos",
    ["Every bar"] = "Todas las barras",
    ["This window"] = "Esta ventana",
    ["Ways in"] = "Accesos",
    ["Minimap button"] = "BotÃ³n del minimapa",
    ["Lock its position"] = "Bloquear su posiciÃ³n",
    ["Game menu entry"] = "Entrada en el menÃº del juego",
    ["Bar text"] = "Texto de las barras",
    ["Panel font"] = "Fuente de las ventanas",
    ["Take the display over"] = "Tomar el control de la pantalla",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de zona",
    ["Clear markers"] = "Quitar marcas",
    ["Clear world markers"] = "Quitar marcas de zona",
    ["Ready check"] = "Comprobar preparaciÃ³n",
    ["Pull timer"] = "Cuenta atrÃ¡s",
    ["Cancel the pull"] = "Cancelar el pull",
    ["Raid check"] = "RevisiÃ³n de banda",
    ["Countdown"] = "Cuenta atrÃ¡s",
    ["Pull"] = "Pull",
    ["Ready"] = "Listo",
    ["Clear"] = "Limpiar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ayudar",
    ["On my way"] = "Voy de camino",
    ["Warning"] = "Cuidado",
    ["Your raid bar"] = "Tu barra de banda",
    ["Every button"] = "Todos los botones",
    ["Click one to put it on your bar."] = "Haz clic para ponerlo en la barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos con clic derecho",
    ["Only for the leader"] = "Solo para el lÃ­der",
    ["Not while in combat"] = "No en combate",
    ["You need lead or assist for that."] = "Necesitas ser lÃ­der o asistente.",
    ["You are not in a group."] = "No estÃ¡s en un grupo.",
    ["The bar cannot be rebuilt while you are in combat. It is done the moment you leave it."] =
        "La barra no puede rehacerse en combate. Se harÃ¡ en cuanto salgas de Ã©l.",

    ["Name"] = "Nombre",
    ["Item level"] = "Nivel de objeto",
    ["Durability"] = "Durabilidad",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Aguante",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidad",
    ["Mastery"] = "MaestrÃ­a",
    ["Movement"] = "Movimiento",
    ["Ask the group"] = "Preguntar al grupo",
    ["No answer"] = "Sin respuesta",
    ["Waiting for answers"] = "Esperando respuestas",
    ["Nobody has answered yet."] = "Nadie ha respondido todavÃ­a.",
    ["Only players running this addon can answer."] =
        "Solo pueden responder los jugadores con este addon.",
    ["%d of %d answered"] = "%d de %d han respondido",

    ["Invite"] = "Invitar",
    ["Keywords"] = "Palabras clave",
    ["Invite on a whisper"] = "Invitar al susurrar",
    ["Also on say and yell"] = "TambiÃ©n al decir y gritar",
    ["Guild members only"] = "Solo la hermandad",
    ["Friends only"] = "Solo amigos",
    ["Make it a raid at five"] = "Convertir en banda con cinco",
    ["Accept invites from friends"] = "Aceptar invitaciones de amigos",
    ["Promote"] = "Ascender",
    ["Disband"] = "Disolver",
    ["Invite everyone back"] = "Volver a invitar a todos",
    ["Invite the guild"] = "Invitar a la hermandad",
    ["Guild rank"] = "Rango de hermandad",
    ["Any rank"] = "Cualquier rango",
    ["Difficulty"] = "Dificultad",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "MÃ­tico",
    ["Nobody to invite back."] = "No hay a quiÃ©n volver a invitar.",
    ["Invited %s."] = "%s invitado.",
    ["The group is empty."] = "El grupo estÃ¡ vacÃ­o.",
    ["One word per line."] = "Una palabra por lÃ­nea.",

    ["%d features in one addon. Switch off what you do not want."] =
        "%d funciones en un addon. Desactiva lo que no quieras.",
    ["Off, the panel never appears."] = "Desactivado, la ventana no aparece nunca.",
    ["Pick a language, then reload."] = "Elige un idioma y recarga.",
    ["Rows times columns is how many places there are."] =
        "Filas por columnas son los sitios que hay.",
    ["The gap between two icons."] = "El hueco entre dos iconos.",
    ["How big each button is on your screen."] =
        "El tamaÃ±o de cada botÃ³n en tu pantalla.",
    ["On your own there is nobody to ask, so it stays away."] =
        "Solo no hay a quiÃ©n pedir nada, asÃ­ que no aparece.",
})

---------------------------------------------------------------------------
-- esMX - the same language, and the differences are real ones. Everything
-- not listed here falls through to... nothing: there is no inheritance
-- between tables on purpose (a chain is a second rule to get wrong), so the
-- untranslated lines fall back to English like everywhere else.
---------------------------------------------------------------------------
Register("esMX", {
    ["Edit mode"] = "Modo ediciÃ³n",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ y banda",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Reutilizaciones",
    ["Co-Tanks"] = "Otros tanques",
    ["Reminders"] = "Recordatorios",
    ["External CD request"] = "Pedir un externo",
    ["External CD answer"] = "Dar un externo",
    ["Death-log"] = "Registro de muertes",
    ["Raid Bar"] = "Barra de banda",
    ["Invites"] = "Invitaciones",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfiles",
    ["Diagnostics"] = "DiagnÃ³stico",
    ["About"] = "Acerca de",
    ["Changelog"] = "Novedades",

    ["Close"] = "Cerrar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Listo",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Color",
    ["Texture"] = "Textura",
    ["Thickness"] = "Grosor",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidad",
    ["Spacing"] = "Espaciado",
    ["Rows"] = "Filas",
    ["Columns"] = "Columnas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "TamaÃ±o de icono",
    ["Look"] = "Aspecto",
    ["Border"] = "Borde",
    ["Backdrop"] = "Fondo",
    ["Keys"] = "Teclas",
    ["Set keys"] = "Asignar teclas",
    ["Test mode"] = "Modo prueba",
    ["Test mode: on"] = "Modo prueba: activo",
    ["Only in a group"] = "Solo en grupo",
    ["Only in combat"] = "Solo en combate",
    ["Only in an instance"] = "Solo en una instancia",
    ["Nothing yet"] = "Nada todavÃ­a",
    ["Switch it on"] = "Activar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Como el juego",
    ["Missing lines are shown in English."] = "Las lÃ­neas que faltan salen en inglÃ©s.",
    ["%s is switched off"] = "%s estÃ¡ desactivado",
    ["Right-click clears every marker."] = "El clic derecho quita todas las marcas.",
    ["Right-click takes this one away."] = "El clic derecho quita esta.",
    ["Right-click cancels it."] = "El clic derecho lo cancela.",

    ["Not now"] = "Ahora no",
    ["Let's go"] = "Vamos",
    ["Show the welcome screen"] = "Mostrar la bienvenida",
    ["NEW"] = "NUEVO",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "No estÃ¡ en pantalla",

    ["Modules"] = "MÃ³dulos",
    ["Every bar"] = "Todas las barras",
    ["This window"] = "Esta ventana",
    ["Ways in"] = "Accesos",
    ["Minimap button"] = "BotÃ³n del minimapa",
    ["Lock its position"] = "Bloquear su posiciÃ³n",
    ["Game menu entry"] = "Entrada en el menÃº del juego",
    ["Bar text"] = "Texto de las barras",
    ["Panel font"] = "Fuente de las ventanas",
    ["Take the display over"] = "Tomar el control de la pantalla",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de zona",
    ["Clear markers"] = "Quitar marcas",
    ["Clear world markers"] = "Quitar marcas de zona",
    ["Ready check"] = "Comprobar preparaciÃ³n",
    ["Pull timer"] = "Cuenta regresiva",
    ["Cancel the pull"] = "Cancelar el pull",
    ["Raid check"] = "RevisiÃ³n de banda",
    ["Countdown"] = "Cuenta regresiva",
    ["Pull"] = "Pull",
    ["Ready"] = "Listo",
    ["Clear"] = "Limpiar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ayudar",
    ["On my way"] = "Voy en camino",
    ["Warning"] = "Cuidado",
    ["Your raid bar"] = "Tu barra de banda",
    ["Every button"] = "Todos los botones",
    ["Click one to put it on your bar."] = "Haz clic para ponerlo en la barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos con clic derecho",
    ["Only for the leader"] = "Solo para el lÃ­der",
    ["Not while in combat"] = "No en combate",
    ["You need lead or assist for that."] = "Necesitas ser lÃ­der o asistente.",
    ["You are not in a group."] = "No estÃ¡s en un grupo.",

    ["Name"] = "Nombre",
    ["Item level"] = "Nivel de objeto",
    ["Durability"] = "Durabilidad",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Aguante",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidad",
    ["Mastery"] = "MaestrÃ­a",
    ["Movement"] = "Movimiento",
    ["Ask the group"] = "Preguntar al grupo",
    ["No answer"] = "Sin respuesta",
    ["Waiting for answers"] = "Esperando respuestas",
    ["Nobody has answered yet."] = "Nadie ha respondido todavÃ­a.",
    ["%d of %d answered"] = "%d de %d respondieron",

    ["Invite"] = "Invitar",
    ["Keywords"] = "Palabras clave",
    ["Invite on a whisper"] = "Invitar al susurrar",
    ["Also on say and yell"] = "TambiÃ©n al decir y gritar",
    ["Guild members only"] = "Solo la hermandad",
    ["Friends only"] = "Solo amigos",
    ["Make it a raid at five"] = "Convertir en banda con cinco",
    ["Accept invites from friends"] = "Aceptar invitaciones de amigos",
    ["Promote"] = "Ascender",
    ["Disband"] = "Disolver",
    ["Invite everyone back"] = "Volver a invitar a todos",
    ["Invite the guild"] = "Invitar a la hermandad",
    ["Guild rank"] = "Rango de hermandad",
    ["Any rank"] = "Cualquier rango",
    ["Difficulty"] = "Dificultad",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "MÃ­tico",
    ["The group is empty."] = "El grupo estÃ¡ vacÃ­o.",
    ["One word per line."] = "Una palabra por lÃ­nea.",
})

---------------------------------------------------------------------------
-- itIT
---------------------------------------------------------------------------
Register("itIT", {
    ["Edit mode"] = "Modifica",
    ["Bars"] = "Barre",
    ["M+ and raid stuff"] = "M+ e incursione",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Recuperi",
    ["Co-Tanks"] = "Altri tank",
    ["Reminders"] = "Promemoria",
    ["External CD request"] = "Chiedi un esterno",
    ["External CD answer"] = "Dai un esterno",
    ["Death-log"] = "Registro morti",
    ["Raid Bar"] = "Barra incursione",
    ["Invites"] = "Inviti",
    ["Settings"] = "Impostazioni",
    ["Profiles"] = "Profili",
    ["Diagnostics"] = "Diagnostica",
    ["About"] = "Informazioni",
    ["Changelog"] = "NovitÃ ",

    ["Close"] = "Chiudi",
    ["Cancel"] = "Annulla",
    ["Done"] = "Fatto",
    ["Show"] = "Mostra",
    ["Hide"] = "Nascondi",
    ["Colour"] = "Colore",
    ["Texture"] = "Trama",
    ["Thickness"] = "Spessore",
    ["Scale"] = "Scala",
    ["Opacity"] = "OpacitÃ ",
    ["Spacing"] = "Spaziatura",
    ["Rows"] = "Righe",
    ["Columns"] = "Colonne",
    ["Runs"] = "Direzione",
    ["Across"] = "Orizzontale",
    ["Down"] = "Verticale",
    ["Icon size"] = "Dimensione icone",
    ["Look"] = "Aspetto",
    ["Border"] = "Bordo",
    ["Backdrop"] = "Sfondo",
    ["Keys"] = "Tasti",
    ["Set keys"] = "Assegna i tasti",
    ["Test mode"] = "ModalitÃ  prova",
    ["Test mode: on"] = "ModalitÃ  prova: attiva",
    ["Only in a group"] = "Solo in gruppo",
    ["Only in combat"] = "Solo in combattimento",
    ["Only in an instance"] = "Solo in un'istanza",
    ["Nothing yet"] = "Ancora niente",
    ["Switch it on"] = "Attiva",
    ["Language"] = "Lingua",
    ["Same as the game"] = "Come il gioco",
    ["Missing lines are shown in English."] = "Le righe mancanti restano in inglese.",
    ["%s is switched off"] = "%s Ã¨ disattivato",
    ["Right-click clears every marker."] = "Il tasto destro toglie tutti i simboli.",
    ["Right-click takes this one away."] = "Il tasto destro toglie questo.",
    ["Right-click cancels it."] = "Il tasto destro annulla.",

    ["Not now"] = "Non ora",
    ["Let's go"] = "Andiamo",
    ["Show the welcome screen"] = "Mostra il benvenuto",
    ["NEW"] = "NUOVO",
    ["HIDDEN"] = "NASCOSTO",
    ["Not on screen"] = "Non Ã¨ sullo schermo",

    ["Modules"] = "Moduli",
    ["Every bar"] = "Tutte le barre",
    ["This window"] = "Questa finestra",
    ["Ways in"] = "Accessi",
    ["Minimap button"] = "Pulsante minimappa",
    ["Lock its position"] = "Blocca la posizione",
    ["Game menu entry"] = "Voce nel menu di gioco",
    ["Bar text"] = "Testo delle barre",
    ["Panel font"] = "Carattere delle finestre",
    ["Take the display over"] = "Prendi il controllo",

    ["Markers"] = "Simboli",
    ["World markers"] = "Segnalini",
    ["Clear markers"] = "Togli i simboli",
    ["Clear world markers"] = "Togli i segnalini",
    ["Ready check"] = "Controllo pronti",
    ["Pull timer"] = "Conto alla rovescia",
    ["Cancel the pull"] = "Annulla il pull",
    ["Raid check"] = "Controllo incursione",
    ["Countdown"] = "Conto alla rovescia",
    ["Pull"] = "Pull",
    ["Ready"] = "Pronto",
    ["Clear"] = "Pulisci",
    ["Ping"] = "Ping",
    ["Attack"] = "Attacca",
    ["Assist"] = "Aiuta",
    ["On my way"] = "Sto arrivando",
    ["Warning"] = "Attenzione",
    ["Your raid bar"] = "La tua barra",
    ["Every button"] = "Tutti i pulsanti",
    ["Click one to put it on your bar."] = "Clicca per metterlo sulla barra.",
    ["The bar"] = "La barra",
    ["Seconds"] = "Secondi",
    ["Right-click seconds"] = "Secondi col tasto destro",
    ["Only for the leader"] = "Solo per il capo",
    ["Not while in combat"] = "Non in combattimento",
    ["You need lead or assist for that."] = "Serve essere capo o assistente.",
    ["You are not in a group."] = "Non sei in un gruppo.",

    ["Name"] = "Nome",
    ["Item level"] = "Livello oggetti",
    ["Durability"] = "IntegritÃ ",
    ["Food"] = "Cibo",
    ["Flask"] = "Fiala",
    ["Rune"] = "Runa",
    ["Stamina"] = "Tempra",
    ["Intellect"] = "Intelletto",
    ["Attack power"] = "Potere d'attacco",
    ["Versatility"] = "VersatilitÃ ",
    ["Mastery"] = "Maestria",
    ["Movement"] = "Movimento",
    ["Ask the group"] = "Chiedi al gruppo",
    ["No answer"] = "Nessuna risposta",
    ["Waiting for answers"] = "In attesa di risposte",
    ["Nobody has answered yet."] = "Non ha ancora risposto nessuno.",
    ["%d of %d answered"] = "%d su %d hanno risposto",

    ["Invite"] = "Invita",
    ["Keywords"] = "Parole chiave",
    ["Invite on a whisper"] = "Invita su sussurro",
    ["Also on say and yell"] = "Anche su dire e urlare",
    ["Guild members only"] = "Solo la gilda",
    ["Friends only"] = "Solo amici",
    ["Make it a raid at five"] = "Converti in incursione a cinque",
    ["Accept invites from friends"] = "Accetta gli inviti degli amici",
    ["Promote"] = "Promuovi",
    ["Disband"] = "Sciogli",
    ["Invite everyone back"] = "Reinvita tutti",
    ["Invite the guild"] = "Invita la gilda",
    ["Guild rank"] = "Grado di gilda",
    ["Any rank"] = "Qualsiasi grado",
    ["Difficulty"] = "DifficoltÃ ",
    ["Normal"] = "Normale",
    ["Heroic"] = "Eroica",
    ["Mythic"] = "Mitica",
    ["The group is empty."] = "Il gruppo Ã¨ vuoto.",
    ["One word per line."] = "Una parola per riga.",
})

---------------------------------------------------------------------------
-- ptBR
---------------------------------------------------------------------------
Register("ptBR", {
    ["Edit mode"] = "Modo de ediÃ§Ã£o",
    ["Bars"] = "Barras",
    ["M+ and raid stuff"] = "M+ e raide",
    ["System"] = "Sistema",
    ["Info"] = "Info",

    ["Cooldowns"] = "Recargas",
    ["Co-Tanks"] = "Outros tanques",
    ["Reminders"] = "Lembretes",
    ["External CD request"] = "Pedir um externo",
    ["External CD answer"] = "Dar um externo",
    ["Death-log"] = "Registro de mortes",
    ["Raid Bar"] = "Barra de raide",
    ["Invites"] = "Convites",
    ["Settings"] = "Ajustes",
    ["Profiles"] = "Perfis",
    ["Diagnostics"] = "DiagnÃ³stico",
    ["About"] = "Sobre",
    ["Changelog"] = "Novidades",

    ["Close"] = "Fechar",
    ["Cancel"] = "Cancelar",
    ["Done"] = "Pronto",
    ["Show"] = "Mostrar",
    ["Hide"] = "Ocultar",
    ["Colour"] = "Cor",
    ["Texture"] = "Textura",
    ["Thickness"] = "Espessura",
    ["Scale"] = "Escala",
    ["Opacity"] = "Opacidade",
    ["Spacing"] = "EspaÃ§amento",
    ["Rows"] = "Linhas",
    ["Columns"] = "Colunas",
    ["Runs"] = "Sentido",
    ["Across"] = "Horizontal",
    ["Down"] = "Vertical",
    ["Icon size"] = "Tamanho do Ã­cone",
    ["Look"] = "AparÃªncia",
    ["Border"] = "Borda",
    ["Backdrop"] = "Fundo",
    ["Keys"] = "Teclas",
    ["Set keys"] = "Definir teclas",
    ["Test mode"] = "Modo de teste",
    ["Test mode: on"] = "Modo de teste: ativo",
    ["Only in a group"] = "SÃ³ em grupo",
    ["Only in combat"] = "SÃ³ em combate",
    ["Only in an instance"] = "SÃ³ em uma masmorra",
    ["Nothing yet"] = "Nada ainda",
    ["Switch it on"] = "Ativar",
    ["Language"] = "Idioma",
    ["Same as the game"] = "Igual ao jogo",
    ["Missing lines are shown in English."] = "As linhas que faltam aparecem em inglÃªs.",
    ["%s is switched off"] = "%s estÃ¡ desligado",
    ["Right-click clears every marker."] = "O clique direito limpa todas as marcas.",
    ["Right-click takes this one away."] = "O clique direito tira esta.",
    ["Right-click cancels it."] = "O clique direito cancela.",

    ["Not now"] = "Agora nÃ£o",
    ["Let's go"] = "Vamos",
    ["Show the welcome screen"] = "Mostrar as boas-vindas",
    ["NEW"] = "NOVO",
    ["HIDDEN"] = "OCULTO",
    ["Not on screen"] = "NÃ£o estÃ¡ na tela",

    ["Modules"] = "MÃ³dulos",
    ["Every bar"] = "Todas as barras",
    ["This window"] = "Esta janela",
    ["Ways in"] = "Acessos",
    ["Minimap button"] = "BotÃ£o do minimapa",
    ["Lock its position"] = "Travar a posiÃ§Ã£o",
    ["Game menu entry"] = "Entrada no menu do jogo",
    ["Bar text"] = "Texto das barras",
    ["Panel font"] = "Fonte das janelas",
    ["Take the display over"] = "Assumir o visor",

    ["Markers"] = "Marcas",
    ["World markers"] = "Marcas de Ã¡rea",
    ["Clear markers"] = "Limpar marcas",
    ["Clear world markers"] = "Limpar marcas de Ã¡rea",
    ["Ready check"] = "Verificar prontidÃ£o",
    ["Pull timer"] = "Contagem regressiva",
    ["Cancel the pull"] = "Cancelar o pull",
    ["Raid check"] = "Checagem do raide",
    ["Countdown"] = "Contagem regressiva",
    ["Pull"] = "Pull",
    ["Ready"] = "Pronto",
    ["Clear"] = "Limpar",
    ["Ping"] = "Ping",
    ["Attack"] = "Atacar",
    ["Assist"] = "Ajudar",
    ["On my way"] = "Estou indo",
    ["Warning"] = "AtenÃ§Ã£o",
    ["Your raid bar"] = "Sua barra de raide",
    ["Every button"] = "Todos os botÃµes",
    ["Click one to put it on your bar."] = "Clique para colocar na barra.",
    ["The bar"] = "A barra",
    ["Seconds"] = "Segundos",
    ["Right-click seconds"] = "Segundos no botÃ£o direito",
    ["Only for the leader"] = "SÃ³ para o lÃ­der",
    ["Not while in combat"] = "NÃ£o em combate",
    ["You need lead or assist for that."] = "VocÃª precisa ser lÃ­der ou assistente.",
    ["You are not in a group."] = "VocÃª nÃ£o estÃ¡ em um grupo.",

    ["Name"] = "Nome",
    ["Item level"] = "NÃ­vel de item",
    ["Durability"] = "Durabilidade",
    ["Food"] = "Comida",
    ["Flask"] = "Frasco",
    ["Rune"] = "Runa",
    ["Stamina"] = "Vigor",
    ["Intellect"] = "Intelecto",
    ["Attack power"] = "Poder de ataque",
    ["Versatility"] = "Versatilidade",
    ["Mastery"] = "Maestria",
    ["Movement"] = "Movimento",
    ["Ask the group"] = "Perguntar ao grupo",
    ["No answer"] = "Sem resposta",
    ["Waiting for answers"] = "Aguardando respostas",
    ["Nobody has answered yet."] = "NinguÃ©m respondeu ainda.",
    ["%d of %d answered"] = "%d de %d responderam",

    ["Invite"] = "Convidar",
    ["Keywords"] = "Palavras-chave",
    ["Invite on a whisper"] = "Convidar ao sussurrar",
    ["Also on say and yell"] = "TambÃ©m ao falar e gritar",
    ["Guild members only"] = "SÃ³ a guilda",
    ["Friends only"] = "SÃ³ amigos",
    ["Make it a raid at five"] = "Virar raide com cinco",
    ["Accept invites from friends"] = "Aceitar convites de amigos",
    ["Promote"] = "Promover",
    ["Disband"] = "Desfazer o grupo",
    ["Invite everyone back"] = "Convidar todos de volta",
    ["Invite the guild"] = "Convidar a guilda",
    ["Guild rank"] = "Cargo na guilda",
    ["Any rank"] = "Qualquer cargo",
    ["Difficulty"] = "Dificuldade",
    ["Normal"] = "Normal",
    ["Heroic"] = "Heroico",
    ["Mythic"] = "MÃ­tico",
    ["The group is empty."] = "O grupo estÃ¡ vazio.",
    ["One word per line."] = "Uma palavra por linha.",
})

---------------------------------------------------------------------------
-- ruRU
---------------------------------------------------------------------------
Register("ruRU", {
    ["Edit mode"] = "Ð ÐµÐ¶Ð¸Ð¼ Ð¿Ñ€Ð°Ð²ÐºÐ¸",
    ["Bars"] = "ÐŸÐ°Ð½ÐµÐ»Ð¸",
    ["M+ and raid stuff"] = "Ðœ+ Ð¸ Ñ€ÐµÐ¹Ð´",
    ["System"] = "Ð¡Ð¸ÑÑ‚ÐµÐ¼Ð°",
    ["Info"] = "Ð˜Ð½Ñ„Ð¾",

    ["Cooldowns"] = "Ð’Ð¾ÑÑÑ‚Ð°Ð½Ð¾Ð²Ð»ÐµÐ½Ð¸Ðµ",
    ["Co-Tanks"] = "Ð”Ñ€ÑƒÐ³Ð¸Ðµ Ñ‚Ð°Ð½ÐºÐ¸",
    ["Reminders"] = "ÐÐ°Ð¿Ð¾Ð¼Ð¸Ð½Ð°Ð½Ð¸Ñ",
    ["External CD request"] = "ÐŸÑ€Ð¾ÑÐ¸Ñ‚ÑŒ Ð²Ð½ÐµÑˆÐ½Ð¸Ð¹ ÐšÐ”",
    ["External CD answer"] = "Ð”Ð°Ñ‚ÑŒ Ð²Ð½ÐµÑˆÐ½Ð¸Ð¹ ÐšÐ”",
    ["Death-log"] = "Ð–ÑƒÑ€Ð½Ð°Ð» ÑÐ¼ÐµÑ€Ñ‚ÐµÐ¹",
    ["Raid Bar"] = "Ð ÐµÐ¹Ð´Ð¾Ð²Ð°Ñ Ð¿Ð°Ð½ÐµÐ»ÑŒ",
    ["Invites"] = "ÐŸÑ€Ð¸Ð³Ð»Ð°ÑˆÐµÐ½Ð¸Ñ",
    ["Settings"] = "ÐÐ°ÑÑ‚Ñ€Ð¾Ð¹ÐºÐ¸",
    ["Profiles"] = "ÐŸÑ€Ð¾Ñ„Ð¸Ð»Ð¸",
    ["Diagnostics"] = "Ð”Ð¸Ð°Ð³Ð½Ð¾ÑÑ‚Ð¸ÐºÐ°",
    ["About"] = "Ðž Ð´Ð¾Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ð¸",
    ["Changelog"] = "Ð˜Ð·Ð¼ÐµÐ½ÐµÐ½Ð¸Ñ",

    ["Close"] = "Ð—Ð°ÐºÑ€Ñ‹Ñ‚ÑŒ",
    ["Cancel"] = "ÐžÑ‚Ð¼ÐµÐ½Ð°",
    ["Done"] = "Ð“Ð¾Ñ‚Ð¾Ð²Ð¾",
    ["Show"] = "ÐŸÐ¾ÐºÐ°Ð·Ð°Ñ‚ÑŒ",
    ["Hide"] = "Ð¡ÐºÑ€Ñ‹Ñ‚ÑŒ",
    ["Colour"] = "Ð¦Ð²ÐµÑ‚",
    ["Texture"] = "Ð¢ÐµÐºÑÑ‚ÑƒÑ€Ð°",
    ["Thickness"] = "Ð¢Ð¾Ð»Ñ‰Ð¸Ð½Ð°",
    ["Scale"] = "ÐœÐ°ÑÑˆÑ‚Ð°Ð±",
    ["Opacity"] = "ÐÐµÐ¿Ñ€Ð¾Ð·Ñ€Ð°Ñ‡Ð½Ð¾ÑÑ‚ÑŒ",
    ["Spacing"] = "ÐžÑ‚ÑÑ‚ÑƒÐ¿",
    ["Rows"] = "Ð¡Ñ‚Ñ€Ð¾ÐºÐ¸",
    ["Columns"] = "Ð¡Ñ‚Ð¾Ð»Ð±Ñ†Ñ‹",
    ["Runs"] = "ÐÐ°Ð¿Ñ€Ð°Ð²Ð»ÐµÐ½Ð¸Ðµ",
    ["Across"] = "ÐŸÐ¾ Ð³Ð¾Ñ€Ð¸Ð·Ð¾Ð½Ñ‚Ð°Ð»Ð¸",
    ["Down"] = "ÐŸÐ¾ Ð²ÐµÑ€Ñ‚Ð¸ÐºÐ°Ð»Ð¸",
    ["Icon size"] = "Ð Ð°Ð·Ð¼ÐµÑ€ Ð·Ð½Ð°Ñ‡ÐºÐ°",
    ["Look"] = "Ð’Ð¸Ð´",
    ["Border"] = "Ð Ð°Ð¼ÐºÐ°",
    ["Backdrop"] = "ÐŸÐ¾Ð´Ð»Ð¾Ð¶ÐºÐ°",
    ["Keys"] = "ÐšÐ»Ð°Ð²Ð¸ÑˆÐ¸",
    ["Set keys"] = "ÐÐ°Ð·Ð½Ð°Ñ‡Ð¸Ñ‚ÑŒ ÐºÐ»Ð°Ð²Ð¸ÑˆÐ¸",
    ["Test mode"] = "Ð¢ÐµÑÑ‚Ð¾Ð²Ñ‹Ð¹ Ñ€ÐµÐ¶Ð¸Ð¼",
    ["Test mode: on"] = "Ð¢ÐµÑÑ‚Ð¾Ð²Ñ‹Ð¹ Ñ€ÐµÐ¶Ð¸Ð¼: Ð²ÐºÐ»",
    ["Only in a group"] = "Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð² Ð³Ñ€ÑƒÐ¿Ð¿Ðµ",
    ["Only in combat"] = "Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð² Ð±Ð¾ÑŽ",
    ["Only in an instance"] = "Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð² Ð¿Ð¾Ð´Ð·ÐµÐ¼ÐµÐ»ÑŒÐµ",
    ["Nothing yet"] = "ÐŸÐ¾ÐºÐ° Ð¿ÑƒÑÑ‚Ð¾",
    ["Switch it on"] = "Ð’ÐºÐ»ÑŽÑ‡Ð¸Ñ‚ÑŒ",
    ["Language"] = "Ð¯Ð·Ñ‹Ðº",
    ["Same as the game"] = "ÐšÐ°Ðº Ð² Ð¸Ð³Ñ€Ðµ",
    ["Missing lines are shown in English."] = "ÐÐµÐ¿ÐµÑ€ÐµÐ²ÐµÐ´Ñ‘Ð½Ð½Ñ‹Ðµ ÑÑ‚Ñ€Ð¾ÐºÐ¸ Ð¿Ð¾ÐºÐ°Ð·Ð°Ð½Ñ‹ Ð½Ð° Ð°Ð½Ð³Ð»Ð¸Ð¹ÑÐºÐ¾Ð¼.",
    ["%s is switched off"] = "%s Ð²Ñ‹ÐºÐ»ÑŽÑ‡ÐµÐ½",
    ["Right-click clears every marker."] = "ÐŸÑ€Ð°Ð²Ð°Ñ ÐºÐ½Ð¾Ð¿ÐºÐ° ÑƒÐ±Ð¸Ñ€Ð°ÐµÑ‚ Ð²ÑÐµ Ð¼ÐµÑ‚ÐºÐ¸.",
    ["Right-click takes this one away."] = "ÐŸÑ€Ð°Ð²Ð°Ñ ÐºÐ½Ð¾Ð¿ÐºÐ° ÑƒÐ±Ð¸Ñ€Ð°ÐµÑ‚ ÑÑ‚Ñƒ Ð¼ÐµÑ‚ÐºÑƒ.",
    ["Right-click cancels it."] = "ÐŸÑ€Ð°Ð²Ð°Ñ ÐºÐ½Ð¾Ð¿ÐºÐ° Ð¾Ñ‚Ð¼ÐµÐ½ÑÐµÑ‚.",

    ["Not now"] = "ÐÐµ ÑÐµÐ¹Ñ‡Ð°Ñ",
    ["Let's go"] = "ÐŸÐ¾ÐµÑ…Ð°Ð»Ð¸",
    ["Show the welcome screen"] = "ÐŸÐ¾ÐºÐ°Ð·Ð°Ñ‚ÑŒ Ð¿Ñ€Ð¸Ð²ÐµÑ‚ÑÑ‚Ð²Ð¸Ðµ",
    ["NEW"] = "ÐÐžÐ’ÐžÐ•",
    ["HIDDEN"] = "Ð¡ÐšÐ Ð«Ð¢Ðž",
    ["Not on screen"] = "ÐÐµÑ‚ Ð½Ð° ÑÐºÑ€Ð°Ð½Ðµ",

    ["Modules"] = "ÐœÐ¾Ð´ÑƒÐ»Ð¸",
    ["Every bar"] = "Ð’ÑÐµ Ð¿Ð°Ð½ÐµÐ»Ð¸",
    ["This window"] = "Ð­Ñ‚Ð¾ Ð¾ÐºÐ½Ð¾",
    ["Ways in"] = "Ð¡Ð¿Ð¾ÑÐ¾Ð±Ñ‹ Ð¾Ñ‚ÐºÑ€Ñ‹Ñ‚ÑŒ",
    ["Minimap button"] = "ÐšÐ½Ð¾Ð¿ÐºÐ° Ñƒ Ð¼Ð¸Ð½Ð¸ÐºÐ°Ñ€Ñ‚Ñ‹",
    ["Lock its position"] = "Ð—Ð°ÐºÑ€ÐµÐ¿Ð¸Ñ‚ÑŒ Ð¿Ð¾Ð»Ð¾Ð¶ÐµÐ½Ð¸Ðµ",
    ["Game menu entry"] = "ÐŸÑƒÐ½ÐºÑ‚ Ð² Ð¸Ð³Ñ€Ð¾Ð²Ð¾Ð¼ Ð¼ÐµÐ½ÑŽ",
    ["Bar text"] = "Ð¢ÐµÐºÑÑ‚ Ð½Ð° Ð¿Ð°Ð½ÐµÐ»ÑÑ…",
    ["Panel font"] = "Ð¨Ñ€Ð¸Ñ„Ñ‚ Ð¾ÐºÐ¾Ð½",
    ["Take the display over"] = "Ð’Ð·ÑÑ‚ÑŒ Ð¾Ñ‚Ð¾Ð±Ñ€Ð°Ð¶ÐµÐ½Ð¸Ðµ Ð½Ð° ÑÐµÐ±Ñ",

    ["Markers"] = "ÐœÐµÑ‚ÐºÐ¸",
    ["World markers"] = "ÐœÐµÑ‚ÐºÐ¸ Ð½Ð° Ð·ÐµÐ¼Ð»Ðµ",
    ["Clear markers"] = "Ð£Ð±Ñ€Ð°Ñ‚ÑŒ Ð¼ÐµÑ‚ÐºÐ¸",
    ["Clear world markers"] = "Ð£Ð±Ñ€Ð°Ñ‚ÑŒ Ð¼ÐµÑ‚ÐºÐ¸ Ð½Ð° Ð·ÐµÐ¼Ð»Ðµ",
    ["Ready check"] = "ÐŸÑ€Ð¾Ð²ÐµÑ€ÐºÐ° Ð³Ð¾Ñ‚Ð¾Ð²Ð½Ð¾ÑÑ‚Ð¸",
    ["Pull timer"] = "ÐžÑ‚ÑÑ‡Ñ‘Ñ‚ Ð´Ð¾ Ð¿ÑƒÐ»Ð°",
    ["Cancel the pull"] = "ÐžÑ‚Ð¼ÐµÐ½Ð¸Ñ‚ÑŒ Ð¿ÑƒÐ»",
    ["Raid check"] = "ÐŸÑ€Ð¾Ð²ÐµÑ€ÐºÐ° Ñ€ÐµÐ¹Ð´Ð°",
    ["Countdown"] = "ÐžÑ‚ÑÑ‡Ñ‘Ñ‚",
    ["Pull"] = "ÐŸÑƒÐ»",
    ["Ready"] = "Ð“Ð¾Ñ‚Ð¾Ð²",
    ["Clear"] = "ÐžÑ‡Ð¸ÑÑ‚Ð¸Ñ‚ÑŒ",
    ["Ping"] = "ÐŸÐ¸Ð½Ð³",
    ["Attack"] = "ÐÑ‚Ð°ÐºÐ°",
    ["Assist"] = "ÐŸÐ¾Ð¼Ð¾Ñ‰ÑŒ",
    ["On my way"] = "Ð˜Ð´Ñƒ",
    ["Warning"] = "Ð’Ð½Ð¸Ð¼Ð°Ð½Ð¸Ðµ",
    ["Your raid bar"] = "Ð’Ð°ÑˆÐ° Ñ€ÐµÐ¹Ð´Ð¾Ð²Ð°Ñ Ð¿Ð°Ð½ÐµÐ»ÑŒ",
    ["Every button"] = "Ð’ÑÐµ ÐºÐ½Ð¾Ð¿ÐºÐ¸",
    ["Click one to put it on your bar."] = "ÐÐ°Ð¶Ð¼Ð¸Ñ‚Ðµ, Ñ‡Ñ‚Ð¾Ð±Ñ‹ Ð´Ð¾Ð±Ð°Ð²Ð¸Ñ‚ÑŒ Ð½Ð° Ð¿Ð°Ð½ÐµÐ»ÑŒ.",
    ["The bar"] = "ÐŸÐ°Ð½ÐµÐ»ÑŒ",
    ["Seconds"] = "Ð¡ÐµÐºÑƒÐ½Ð´Ñ‹",
    ["Right-click seconds"] = "Ð¡ÐµÐºÑƒÐ½Ð´Ñ‹ Ð¿Ð¾ Ð¿Ñ€Ð°Ð²Ð¾Ð¹ ÐºÐ½Ð¾Ð¿ÐºÐµ",
    ["Only for the leader"] = "Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð´Ð»Ñ Ð»Ð¸Ð´ÐµÑ€Ð°",
    ["Not while in combat"] = "ÐÐµ Ð² Ð±Ð¾ÑŽ",
    ["You need lead or assist for that."] = "ÐÑƒÐ¶Ð½Ñ‹ Ð¿Ñ€Ð°Ð²Ð° Ð»Ð¸Ð´ÐµÑ€Ð° Ð¸Ð»Ð¸ Ð¿Ð¾Ð¼Ð¾Ñ‰Ð½Ð¸ÐºÐ°.",
    ["You are not in a group."] = "Ð’Ñ‹ Ð½Ðµ Ð² Ð³Ñ€ÑƒÐ¿Ð¿Ðµ.",

    ["Name"] = "Ð˜Ð¼Ñ",
    ["Item level"] = "Ð£Ñ€Ð¾Ð²ÐµÐ½ÑŒ Ð¿Ñ€ÐµÐ´Ð¼ÐµÑ‚Ð¾Ð²",
    ["Durability"] = "ÐŸÑ€Ð¾Ñ‡Ð½Ð¾ÑÑ‚ÑŒ",
    ["Food"] = "Ð•Ð´Ð°",
    ["Flask"] = "ÐÐ°ÑÑ‚Ð¾Ð¹",
    ["Rune"] = "Ð ÑƒÐ½Ð°",
    ["Stamina"] = "Ð’Ñ‹Ð½Ð¾ÑÐ»Ð¸Ð²Ð¾ÑÑ‚ÑŒ",
    ["Intellect"] = "Ð˜Ð½Ñ‚ÐµÐ»Ð»ÐµÐºÑ‚",
    ["Attack power"] = "Ð¡Ð¸Ð»Ð° Ð°Ñ‚Ð°ÐºÐ¸",
    ["Versatility"] = "Ð£Ð½Ð¸Ð²ÐµÑ€ÑÐ°Ð»ÑŒÐ½Ð¾ÑÑ‚ÑŒ",
    ["Mastery"] = "Ð˜ÑÐºÑƒÑÐ½Ð¾ÑÑ‚ÑŒ",
    ["Movement"] = "Ð¡ÐºÐ¾Ñ€Ð¾ÑÑ‚ÑŒ",
    ["Ask the group"] = "Ð¡Ð¿Ñ€Ð¾ÑÐ¸Ñ‚ÑŒ Ð³Ñ€ÑƒÐ¿Ð¿Ñƒ",
    ["No answer"] = "ÐÐµÑ‚ Ð¾Ñ‚Ð²ÐµÑ‚Ð°",
    ["Waiting for answers"] = "ÐžÐ¶Ð¸Ð´Ð°Ð½Ð¸Ðµ Ð¾Ñ‚Ð²ÐµÑ‚Ð¾Ð²",
    ["Nobody has answered yet."] = "ÐŸÐ¾ÐºÐ° Ð½Ð¸ÐºÑ‚Ð¾ Ð½Ðµ Ð¾Ñ‚Ð²ÐµÑ‚Ð¸Ð».",
    ["%d of %d answered"] = "ÐžÑ‚Ð²ÐµÑ‚Ð¸Ð»Ð¸ %d Ð¸Ð· %d",

    ["Invite"] = "ÐŸÑ€Ð¸Ð³Ð»Ð°ÑÐ¸Ñ‚ÑŒ",
    ["Keywords"] = "ÐšÐ»ÑŽÑ‡ÐµÐ²Ñ‹Ðµ ÑÐ»Ð¾Ð²Ð°",
    ["Invite on a whisper"] = "ÐŸÑ€Ð¸Ð³Ð»Ð°ÑˆÐ°Ñ‚ÑŒ Ð¿Ð¾ ÑˆÑ‘Ð¿Ð¾Ñ‚Ñƒ",
    ["Also on say and yell"] = "Ð¢Ð°ÐºÐ¶Ðµ Ð¿Ð¾ Â«ÑÐºÐ°Ð·Ð°Ñ‚ÑŒÂ» Ð¸ Â«ÐºÑ€Ð¸ÐºÐ½ÑƒÑ‚ÑŒÂ»",
    ["Guild members only"] = "Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð³Ð¸Ð»ÑŒÐ´Ð¸Ñ",
    ["Friends only"] = "Ð¢Ð¾Ð»ÑŒÐºÐ¾ Ð´Ñ€ÑƒÐ·ÑŒÑ",
    ["Make it a raid at five"] = "Ð¡Ð¾Ð±Ñ€Ð°Ñ‚ÑŒ Ñ€ÐµÐ¹Ð´ Ð¿Ñ€Ð¸ Ð¿ÑÑ‚Ð¸",
    ["Accept invites from friends"] = "ÐŸÑ€Ð¸Ð½Ð¸Ð¼Ð°Ñ‚ÑŒ Ð¿Ñ€Ð¸Ð³Ð»Ð°ÑˆÐµÐ½Ð¸Ñ Ð´Ñ€ÑƒÐ·ÐµÐ¹",
    ["Promote"] = "ÐŸÐ¾Ð²Ñ‹ÑÐ¸Ñ‚ÑŒ",
    ["Disband"] = "Ð Ð°ÑÐ¿ÑƒÑÑ‚Ð¸Ñ‚ÑŒ",
    ["Invite everyone back"] = "ÐŸÑ€Ð¸Ð³Ð»Ð°ÑÐ¸Ñ‚ÑŒ Ð²ÑÐµÑ… Ð¾Ð±Ñ€Ð°Ñ‚Ð½Ð¾",
    ["Invite the guild"] = "ÐŸÑ€Ð¸Ð³Ð»Ð°ÑÐ¸Ñ‚ÑŒ Ð³Ð¸Ð»ÑŒÐ´Ð¸ÑŽ",
    ["Guild rank"] = "Ð Ð°Ð½Ð³ Ð² Ð³Ð¸Ð»ÑŒÐ´Ð¸Ð¸",
    ["Any rank"] = "Ð›ÑŽÐ±Ð¾Ð¹ Ñ€Ð°Ð½Ð³",
    ["Difficulty"] = "Ð¡Ð»Ð¾Ð¶Ð½Ð¾ÑÑ‚ÑŒ",
    ["Normal"] = "ÐžÐ±Ñ‹Ñ‡Ð½Ñ‹Ð¹",
    ["Heroic"] = "Ð“ÐµÑ€Ð¾Ð¸Ñ‡ÐµÑÐºÐ¸Ð¹",
    ["Mythic"] = "Ð­Ð¿Ð¾Ñ…Ð°Ð»ÑŒÐ½Ñ‹Ð¹",
    ["The group is empty."] = "Ð“Ñ€ÑƒÐ¿Ð¿Ð° Ð¿ÑƒÑÑ‚Ð°.",
    ["One word per line."] = "ÐŸÐ¾ Ð¾Ð´Ð½Ð¾Ð¼Ñƒ ÑÐ»Ð¾Ð²Ñƒ Ð² ÑÑ‚Ñ€Ð¾ÐºÐµ.",
})

---------------------------------------------------------------------------
-- koKR - the vocabulary. See the header: the short labels are here, the
-- sentences are left in English on purpose rather than guessed at.
---------------------------------------------------------------------------
Register("koKR", {
    ["Edit mode"] = "íŽ¸ì§‘ ëª¨ë“œ",
    ["Bars"] = "ë°”",
    ["System"] = "ì‹œìŠ¤í…œ",
    ["Info"] = "ì •ë³´",

    ["Cooldowns"] = "ìž¬ì‚¬ìš© ëŒ€ê¸°ì‹œê°„",
    ["Reminders"] = "ì•Œë¦¼",
    ["Death-log"] = "ì£½ìŒ ê¸°ë¡",
    ["Raid Bar"] = "ê³µê²©ëŒ€ ë°”",
    ["Invites"] = "ì´ˆëŒ€",
    ["Settings"] = "ì„¤ì •",
    ["Profiles"] = "í”„ë¡œí•„",
    ["Diagnostics"] = "ì§„ë‹¨",
    ["About"] = "ì •ë³´",
    ["Changelog"] = "ë³€ê²½ ë‚´ì—­",

    ["Close"] = "ë‹«ê¸°",
    ["Cancel"] = "ì·¨ì†Œ",
    ["Done"] = "ì™„ë£Œ",
    ["Show"] = "í‘œì‹œ",
    ["Hide"] = "ìˆ¨ê¸°ê¸°",
    ["Colour"] = "ìƒ‰ìƒ",
    ["Texture"] = "í…ìŠ¤ì²˜",
    ["Thickness"] = "ë‘ê»˜",
    ["Scale"] = "í¬ê¸°",
    ["Opacity"] = "ë¶ˆíˆ¬ëª…ë„",
    ["Spacing"] = "ê°„ê²©",
    ["Rows"] = "í–‰",
    ["Columns"] = "ì—´",
    ["Icon size"] = "ì•„ì´ì½˜ í¬ê¸°",
    ["Look"] = "ëª¨ì–‘",
    ["Border"] = "í…Œë‘ë¦¬",
    ["Backdrop"] = "ë°°ê²½",
    ["Keys"] = "ë‹¨ì¶•í‚¤",
    ["Language"] = "ì–¸ì–´",
    ["Switch it on"] = "ì¼œê¸°",
    ["Modules"] = "ëª¨ë“ˆ",
    ["Not now"] = "ë‚˜ì¤‘ì—",

    ["Markers"] = "í‘œì  ì§€ì •",
    ["World markers"] = "ì§€ì—­ í‘œì‹œ",
    ["Ready check"] = "ì¤€ë¹„ í™•ì¸",
    ["Pull timer"] = "í’€ íƒ€ì´ë¨¸",
    ["Raid check"] = "ê³µê²©ëŒ€ ì ê²€",
    ["Ready"] = "ì¤€ë¹„",
    ["Clear"] = "ì§€ìš°ê¸°",
    ["Ping"] = "í•‘",
    ["Attack"] = "ê³µê²©",
    ["Assist"] = "ì§€ì›",
    ["Warning"] = "ê²½ê³ ",
    ["Seconds"] = "ì´ˆ",

    ["Name"] = "ì´ë¦„",
    ["Item level"] = "ì•„ì´í…œ ë ˆë²¨",
    ["Durability"] = "ë‚´êµ¬ë„",
    ["Food"] = "ìŒì‹",
    ["Flask"] = "ì˜ì•½",
    ["Rune"] = "ë£¬",
    ["Stamina"] = "ì²´ë ¥",
    ["Intellect"] = "ì§€ëŠ¥",
    ["Attack power"] = "ê³µê²©ë ¥",
    ["Versatility"] = "íŠ¹í™”",
    ["Mastery"] = "íŠ¹í™”",
    ["Movement"] = "ì´ë™ ì†ë„",
    ["No answer"] = "ì‘ë‹µ ì—†ìŒ",

    ["Invite"] = "ì´ˆëŒ€",
    ["Keywords"] = "í‚¤ì›Œë“œ",
    ["Promote"] = "ìŠ¹ê¸‰",
    ["Disband"] = "í•´ì‚°",
    ["Difficulty"] = "ë‚œì´ë„",
    ["Normal"] = "ì¼ë°˜",
    ["Heroic"] = "ì˜ì›…",
    ["Mythic"] = "ì‹ í™”",
})

---------------------------------------------------------------------------
-- zhCN
---------------------------------------------------------------------------
Register("zhCN", {
    ["Edit mode"] = "ç¼–è¾‘æ¨¡å¼",
    ["Bars"] = "æ¡",
    ["System"] = "ç³»ç»Ÿ",
    ["Info"] = "ä¿¡æ¯",

    ["Cooldowns"] = "å†·å´",
    ["Reminders"] = "æé†’",
    ["Death-log"] = "æ­»äº¡è®°å½•",
    ["Raid Bar"] = "å›¢é˜Ÿæ ",
    ["Invites"] = "é‚€è¯·",
    ["Settings"] = "è®¾ç½®",
    ["Profiles"] = "é…ç½®",
    ["Diagnostics"] = "è¯Šæ–­",
    ["About"] = "å…³äºŽ",
    ["Changelog"] = "æ›´æ–°æ—¥å¿—",

    ["Close"] = "å…³é—­",
    ["Cancel"] = "å–æ¶ˆ",
    ["Done"] = "å®Œæˆ",
    ["Show"] = "æ˜¾ç¤º",
    ["Hide"] = "éšè—",
    ["Colour"] = "é¢œè‰²",
    ["Texture"] = "æè´¨",
    ["Thickness"] = "ç²—ç»†",
    ["Scale"] = "ç¼©æ”¾",
    ["Opacity"] = "ä¸é€æ˜Žåº¦",
    ["Spacing"] = "é—´è·",
    ["Rows"] = "è¡Œ",
    ["Columns"] = "åˆ—",
    ["Icon size"] = "å›¾æ ‡å¤§å°",
    ["Look"] = "å¤–è§‚",
    ["Border"] = "è¾¹æ¡†",
    ["Backdrop"] = "èƒŒæ™¯",
    ["Keys"] = "æŒ‰é”®",
    ["Language"] = "è¯­è¨€",
    ["Switch it on"] = "å¼€å¯",
    ["Modules"] = "æ¨¡å—",
    ["Not now"] = "æš‚ä¸",

    ["Markers"] = "æ ‡è®°",
    ["World markers"] = "åœºæ™¯æ ‡è®°",
    ["Ready check"] = "å‡†å¤‡ç¡®è®¤",
    ["Pull timer"] = "å¼€æ€ªå€’è®¡æ—¶",
    ["Raid check"] = "å›¢é˜Ÿæ£€æŸ¥",
    ["Ready"] = "å‡†å¤‡",
    ["Clear"] = "æ¸…é™¤",
    ["Ping"] = "æ ‡ç‚¹",
    ["Attack"] = "æ”»å‡»",
    ["Assist"] = "ååŠ©",
    ["Warning"] = "è­¦å‘Š",
    ["Seconds"] = "ç§’",

    ["Name"] = "åå­—",
    ["Item level"] = "è£…ç­‰",
    ["Durability"] = "è€ä¹…åº¦",
    ["Food"] = "é£Ÿç‰©",
    ["Flask"] = "åˆå‰‚",
    ["Rune"] = "ç¬¦æ–‡",
    ["Stamina"] = "è€åŠ›",
    ["Intellect"] = "æ™ºåŠ›",
    ["Attack power"] = "æ”»å‡»å¼ºåº¦",
    ["Versatility"] = "å…¨èƒ½",
    ["Mastery"] = "ç²¾é€š",
    ["Movement"] = "ç§»åŠ¨é€Ÿåº¦",
    ["No answer"] = "æ— å›žåº”",

    ["Invite"] = "é‚€è¯·",
    ["Keywords"] = "å…³é”®è¯",
    ["Promote"] = "æå‡",
    ["Disband"] = "è§£æ•£",
    ["Difficulty"] = "éš¾åº¦",
    ["Normal"] = "æ™®é€š",
    ["Heroic"] = "è‹±é›„",
    ["Mythic"] = "å²è¯—",
})

---------------------------------------------------------------------------
-- zhTW
---------------------------------------------------------------------------
Register("zhTW", {
    ["Edit mode"] = "ç·¨è¼¯æ¨¡å¼",
    ["Bars"] = "åˆ—",
    ["System"] = "ç³»çµ±",
    ["Info"] = "è³‡è¨Š",

    ["Cooldowns"] = "å†·å»",
    ["Reminders"] = "æé†’",
    ["Death-log"] = "æ­»äº¡è¨˜éŒ„",
    ["Raid Bar"] = "åœ˜éšŠåˆ—",
    ["Invites"] = "é‚€è«‹",
    ["Settings"] = "è¨­å®š",
    ["Profiles"] = "è¨­å®šæª”",
    ["Diagnostics"] = "è¨ºæ–·",
    ["About"] = "é—œæ–¼",
    ["Changelog"] = "æ›´æ–°è¨˜éŒ„",

    ["Close"] = "é—œé–‰",
    ["Cancel"] = "å–æ¶ˆ",
    ["Done"] = "å®Œæˆ",
    ["Show"] = "é¡¯ç¤º",
    ["Hide"] = "éš±è—",
    ["Colour"] = "é¡è‰²",
    ["Texture"] = "æè³ª",
    ["Thickness"] = "ç²—ç´°",
    ["Scale"] = "ç¸®æ”¾",
    ["Opacity"] = "ä¸é€æ˜Žåº¦",
    ["Spacing"] = "é–“è·",
    ["Rows"] = "åˆ—æ•¸",
    ["Columns"] = "è¡Œæ•¸",
    ["Icon size"] = "åœ–ç¤ºå¤§å°",
    ["Look"] = "å¤–è§€",
    ["Border"] = "é‚Šæ¡†",
    ["Backdrop"] = "èƒŒæ™¯",
    ["Keys"] = "æŒ‰éµ",
    ["Language"] = "èªžè¨€",
    ["Switch it on"] = "é–‹å•Ÿ",
    ["Modules"] = "æ¨¡çµ„",
    ["Not now"] = "ç¨å¾Œ",

    ["Markers"] = "æ¨™è¨˜",
    ["World markers"] = "å ´æ™¯æ¨™è¨˜",
    ["Ready check"] = "æº–å‚™ç¢ºèª",
    ["Pull timer"] = "é–‹æ€ªå€’æ•¸",
    ["Raid check"] = "åœ˜éšŠæª¢æŸ¥",
    ["Ready"] = "æº–å‚™",
    ["Clear"] = "æ¸…é™¤",
    ["Ping"] = "æ¨™é»ž",
    ["Attack"] = "æ”»æ“Š",
    ["Assist"] = "å”åŠ©",
    ["Warning"] = "è­¦å‘Š",
    ["Seconds"] = "ç§’",

    ["Name"] = "åå­—",
    ["Item level"] = "è£ç­‰",
    ["Durability"] = "è€ä¹…åº¦",
    ["Food"] = "é£Ÿç‰©",
    ["Flask"] = "åˆåŠ‘",
    ["Rune"] = "ç¬¦æ–‡",
    ["Stamina"] = "è€åŠ›",
    ["Intellect"] = "æ™ºåŠ›",
    ["Attack power"] = "æ”»æ“Šå¼·åº¦",
    ["Versatility"] = "è‡¨æ©Ÿæ‡‰è®Š",
    ["Mastery"] = "ç²¾é€š",
    ["Movement"] = "ç§»å‹•é€Ÿåº¦",
    ["No answer"] = "ç„¡å›žæ‡‰",

    ["Invite"] = "é‚€è«‹",
    ["Keywords"] = "é—œéµå­—",
    ["Promote"] = "æ™‰å‡",
    ["Disband"] = "è§£æ•£",
    ["Difficulty"] = "é›£åº¦",
    ["Normal"] = "æ™®é€š",
    ["Heroic"] = "è‹±é›„",
    ["Mythic"] = "å²è©©",
})
